### ISSUE TITLE
Populate this repository with a subset of wptdashboard

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1]
Land the first commit to this repository based on the master of https://github.com/w3c/wptdashboard.

We could keep all the existing history, or produce a single commit in the style of https://github.com/KDE/khtml/commit/d9b7bfb9acfa4c36f0ef9f382d7c840e1e5ae11d. That commit has stuck with me, because I like source code archaeology and it was so helpful.

This is part of https://github.com/w3c/wptdashboard/issues/533.

**Comment by lukebjerring** [comment]
Just working on trimming down the docker files before creating a PR.

**Comment by foolip** [comment]
The very first commit to master will have to be pushed without review (PR), but sounds good!

**Comment by lukebjerring** [comment]
[image: pasted1]
