### ISSUE TITLE
Edge/Safari pre-release warning bogus

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#10]
_From @gsnedders on January 29, 2018 16:36_

We have at the top of the results:

> Also note that tested Edge and Safari are not pre-release versions (#109, #110).

Except now all browsers are not pre-release versions, and only Safari is the latest stable release. And #110 was closed as a dupe of #112.

_Copied from original issue: w3c/wptdashboard#410_

**Comment by lukebjerring** [comment]
_From @mattl on January 29, 2018 16:56_

Seems like this message appears in a few different places. https://github.com/w3c/wptdashboard/search?utf8=%E2%9C%93&q=109&type=

But I agree it shouldn't be there right now, however we have a plan to bring back dev browsers.

**Comment by foolip** [comment]
This has already been fixed, the message is now "Each browser listed here is currently tested at its latest stable release."
