### ISSUE TITLE
Fetch full runs from Azure Pipelines daily runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1020]
https://github.com/web-platform-tests/wpt/issues/14836 tracks performing daily runs of Safari on Azure Pipelines. There's an unresolved problem with actually triggering the runs in the main wpt repo, but https://dev.azure.com/foolip/wpt/_build/results?buildId=343 is an example of what it will look like. Using that repository to develop the code to ingest these results should work.

@lukebjerring @Hexcles is this in either of your ballparks?

**Comment by lukebjerring** [comment]
Currently the Azure handler expects exactly one report in the artifact. We'll need to tweak this code to pull out and attach all of the artifact's report shards.

https://github.com/web-platform-tests/wpt.fyi/blob/master/api/azure/webhook.go#L132

**Comment by lukebjerring** [comment]
This is now fixed and exposed for notification via #1054
