### ISSUE TITLE
Filter not applied on individual test pages

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt.fyi#1048]
On a browser comparison page like:

https://staging.wpt.fyi/results/dom?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=%21firefox%3Apass+%21firefox%3Aok+%28chrome%3Apass%7Cchrome%3Aok%29+%28safari%3Apass%7Csafari%3Aok%29+dom

one gets directory-level results for tests that pass in one browser but fail in others e.g. currently on that link you get 0/3 for firefox on `historical.html`, reflecting the fact that 3 subtests match the filter and by construction none of them pass in Firefox. But if you click on the individual test link you suddenly see all the subtests in that file, not just the ones that matched the applied filter, which is confusing and kind of defeats the point of the feature in cases where files have a large number of subtests.

**Comment by lukebjerring** [comment]
The `/api/search` request, handled by `searchcache`, is designed to return aggregated numbers.
We'll need to expand the functionality of the search to return included subtests, either via a query param, or whenever the path is a test-file (the latter is simpler, so probably that).

**Comment by lukebjerring** [comment]
Duplicate of and old issue https://github.com/web-platform-tests/wpt.fyi/issues/81
Back then, we worked around it by just not having a search box, but we can now actually search subtests via the searchcache, so revisiting it to provide an actual fix.
