### ISSUE TITLE
wpt.fyi fails to load in Safari Tech Preview

### ISSUE THREAD

**Issue by beaufortfrancois** [web-platform-tests/wpt.fyi#1055]
wpt.fyi fails to load in Safari Tech Preview while it works great in Safari.

![image](https://user-images.githubusercontent.com/634478/51530626-b0d28080-1e3b-11e9-960c-1ea296d3d84f.png)

@lukebjerring

**Comment by foolip** [comment]
I wonder why we're trying to use XHR?

**Comment by lukebjerring** [comment]
"We" is Google analytics, at a wild guess from the requested domain.
@gsnedders had mentioned tech preview was fully crashing on wpt.fyi, so at least this is less bad..

**Comment by gsnedders** [comment]
What release of STP are you on? In STP 73, you should just be hitting https://bugs.webkit.org/show_bug.cgi?id=191633, which should hopefully be fixed in STP 74…

**Comment by beaufortfrancois** [comment]
Release 73 indeed.

**Comment by gsnedders** [comment]
STP 74 shipped today, and this WFM now, as expected.
