### ISSUE TITLE
Newly added tests show up as flakiness

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1076]
Using the insight tab and tweaking a bit to get Safari TP runs for Azure Pipelines, I finally ended up at this view:
https://wpt.fyi/results/xhr/sync-xhr-supported-by-feature-policy.html?run_id=5701098400645120&run_id=5648138584981504&run_id=5164405260025856&run_id=6496107718770688&run_id=5458240213090304

Here, the test was added on Jan 24, so reporting it as flakiness is not helpful. As flakiness is improved, the view ought to become dominated by recently added tests.

**Comment by lukebjerring** [comment]
This is no longer the case - flakes require a test going from pass to fail _and_ fail to pass.
