### ISSUE TITLE
Browser upgrade reported as flakiness

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1078]
Similar to https://github.com/web-platform-tests/wpt.fyi/issues/1076, I'm looking at this search:
https://wpt.fyi/results/?label=azure&label=master&label=experimental&max-count=10&product=safari&q=%28safari%3APASS%7Csafari%3AOK%29+%28safari%3AUNKNOWN%7Csafari%3AERROR%7Csafari%3ATIMEOUT%7Csafari%3ANOTRUN%7Csafari%3AFAIL%7Csafari%3ACRASH%7Csafari%3ASKIP%7Csafari%3AASSERT%29

With runs held constant and manually working around https://github.com/web-platform-tests/wpt.fyi/issues/1077:

https://wpt.fyi/results/?q=%28safari%3APASS%7Csafari%3AOK%29+%28safari%3AUNKNOWN%7Csafari%3AERROR%7Csafari%3ATIMEOUT%7Csafari%3ANOTRUN%7Csafari%3AFAIL%7Csafari%3ACRASH%7Csafari%3ASKIP%7Csafari%3AASSERT%29&run_id=5701098400645120&run_id=5648138584981504&run_id=5164405260025856&run_id=6496107718770688&run_id=5458240213090304

Screenshot:
![image](https://user-images.githubusercontent.com/498917/51831019-76605c00-22f1-11e9-9c8c-7098d8e494ef.png)

As can be seen visually, the rightmost column for Safari Technology Preview 73 is the most red. Drilling down that's almost entirely because of https://github.com/web-platform-tests/wpt.fyi/issues/1076, but there's also one case of a test being fixed that shows up as flakiness:
https://wpt.fyi/results/audio-output/setSinkId.html?q=%28safari%3APASS%7Csafari%3AOK%29+%28safari%3AUNKNOWN%7Csafari%3AERROR%7Csafari%3ATIMEOUT%7Csafari%3ANOTRUN%7Csafari%3AFAIL%7Csafari%3ACRASH%7Csafari%3ASKIP%7Csafari%3AASSERT%29&run_id=5701098400645120&run_id=5648138584981504&run_id=5164405260025856&run_id=6496107718770688&run_id=5458240213090304

Old status was CRASH, and now the test runs but fails.

**Comment by lukebjerring** [comment]
This is a limitation in the infrastructure; we can't (yet) search for state-before vs state-after, nor for counts-of-status.

A query like `n(status:OK or status:PASS, 2) n-plus-1(status:!OK and status:!PASS)` would be needed (ignore the syntax, it hasn't been though about  for more than 30 seconds).

**Comment by foolip** [comment]
I tried `product=safari-74` but that didn't work, but perhaps we could generate links that only match the current latest browser version?

**Comment by lukebjerring** [comment]
With the `seq` operator implemented, the equivalent query (same runs) is now 
https://wpt.fyi/results/?q=seq%28%28status%3Apass%7Cstatus%3Aok%29+%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29%29+seq%28%28status%3A%21pass%26status%3A%21ok%26status%3A%21unknown%29+%28status%3Apass%7Cstatus%3Aok%29%29&run_id=5701098400645120&run_id=5648138584981504&run_id=5164405260025856&run_id=6496107718770688&run_id=5458240213090304
