### ISSUE TITLE
Browser links from /runs are broken

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1090]
In https://wpt.fyi/runs?label=master&from=2019-01-23T00%3A00, the Safari link for sha 6924817 is https://wpt.fyi/results?sha=692481793b&label=experimental

However, that URL shows no results at all, and a toast about label=master. These links could probably use `run_id` now?

The https://wpt.fyi/?sha=692481793b link does work, so I've used that.

**Comment by lukebjerring** [comment]
It's 500ing because of a missing index. Building the index now.
