### ISSUE TITLE
Receive results from multiple browsers on the same Azure Pipelines build

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1091]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5330 is the first successful full Edge run on Azure Pipelines that we could consider ingesting, although it's not for a commit on master on thus of limited utility.

This is related to changes required for https://github.com/web-platform-tests/wpt/pull/15110, but working on Edge runs I realized there's a drawback with the current wpt.fyi hook. If we have runs that take very different amounts of time to finish, we'd either have to wait until they've all finished and delay ingestion of the fastest, or we'd have to call the wpt.fyi hook multiple times and count on the receiver to deduplicate.

Proposed fix: include the artifact name to be ingested in the hook.

@thejohnjansen @mustjab FYI

**Comment by lukebjerring** [comment]
We could (and maybe should) whitelist artifact names. Especially if they're prone to timing out / exceeding other limits.

**Comment by foolip** [comment]
This was fixed by https://github.com/web-platform-tests/wpt/pull/15498.
