### ISSUE TITLE
Results on wpt.fyi for "nightly" builds are close to a month old.

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt.fyi#1093]
If I just load "https://wpt.fyi/", I get redirected to <https://wpt.fyi/results/?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned> which is showing results from wpt revision 71e901c.

Per <https://wpt.fyi/runs?label=master&max-count=500&from=2019-01-01T00%3A00> it looks like that's the last revision that has data for runs for all four browsers, mostly because Edge is almost never run.  If we just look for the last run that has Safari/Chrome/Firefox data, that happened earlier today.  And twice yesterday.  And once day before yesterday, etc.

Is there something we can do to show more-updated data here?

**Comment by Hexcles** [comment]
This is because we haven't had an Edge (insider) run for a while. @foolip
is trying to get it up and running again. Meanwhile, if you remove the
"&aligned" part from the query you'll see more recent runs.

**Comment by bzbarsky** [comment]
Ah, thanks, removing `&aligned` gets me the data I want!
