### ISSUE TITLE
Rename of test with failures treated as regression

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1095]
### Check
https://github.com/web-platform-tests/wpt/pull/15164/checks?check_run_id=56899006

### Description
https://wpt.fyi/results/workers?diff&run_id=5664859949629440&run_id=4922180244602880 shows that the results are the same, just renamed.

There's already rename detection is place, but it might not work for .any.js?

**Comment by lukebjerring** [comment]
This is out of our hands; GitHub's API doesn't detect it as a rename.
https://github.com/web-platform-tests/wpt/compare/master...8b7800c

**Comment by foolip** [comment]
Ah. `git diff --find-renames=10 merge_pr_15164~ merge_pr_15164` detects this as a rename with "similarity index 45%", so this was just below the 50% threshold. Without a principled reason to pick another threshold I agree we should do nothing about this.

**Comment by Hexcles** [comment]
And GitHub API does not allow us to specify the threshold IIRC.
