### ISSUE TITLE
Delete/hide run 4812189890248704

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1110]
https://wpt.fyi/results/?run_id=4812189890248704 is a result of https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5664, a dummy job to upload the results of https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5644 after modifying them locally.

It came from https://github.com/web-platform-tests/wpt/commit/2ad1997697.

The sha is taken from the actual commit and not what was in the reports, and this commit wasn't on master. Just deleting this run is probably best.

**Comment by lukebjerring** [comment]
Deleted.

**Comment by foolip** [comment]
Hmm, someone when trying to upload the same results manually, they still got 2ad1997 as the revision even though that's not what was in the reports. Probably because of deduping at some layer as the files were exactly the same as before just uploaded differently.

So this needs deleting now: https://staging.wpt.fyi/results/?run_id=4638308961353728

**Comment by lukebjerring** [comment]
You can find/delete the Test run entity in the "Datastore" tab on appengine. 
Filter with Key is equal to `key(Test run, [id])`

**Comment by foolip** [comment]
Is deleting the way to do it, or do you rename to bad_something as has happened in the past?
