### ISSUE TITLE
Drilling down into subtest results of diff view doesn't work

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#112]
Start at https://master-dot-wptdashboard.appspot.com/results/?before=chrome@latest&after=safari@latest

Drill down into any testharness.js test, like https://master-dot-wptdashboard.appspot.com/results/dom/historical.html?before=eyJicm93c2VyX25hbWUiOiJjaHJvbWUiLCJicm93c2VyX3ZlcnNpb24iOiI2Ni4wLjMzNTkuMTM5Iiwib3NfbmFtZSI6ImxpbnV4Iiwib3NfdmVyc2lvbiI6IjQuNCIsInJldmlzaW9uIjoiYzgzYzUzZTBjYyIsInJlc3VsdHNfdXJsIjoiaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3dwdGQvYzgzYzUzZTBjYy9jaHJvbWUtc3RhYmxlLWxpbnV4LXN1bW1hcnkuanNvbi5neiIsImNyZWF0ZWRfYXQiOiIyMDE4LTA1LTAyVDA4OjA2OjMwLjU2OTU5OVoiLCJzdWJ0ZXN0cyI6eyJUZXN0IGZpbGUiOnsic3RhdHVzIjoiRkFJTCJ9fX0=&after=eyJicm93c2VyX25hbWUiOiJzYWZhcmkiLCJicm93c2VyX3ZlcnNpb24iOiIxMS4wIiwib3NfbmFtZSI6Im1hY29zIiwib3NfdmVyc2lvbiI6IjEwLjEyIiwicmV2aXNpb24iOiI0M2RkMjVjODg4IiwicmVzdWx0c191cmwiOiJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vd3B0ZC80M2RkMjVjODg4L3NhZmFyaS0xMS4wLW1hY29zLTEwLjEyLXNhdWNlLXN1bW1hcnkuanNvbi5neiIsImNyZWF0ZWRfYXQiOiIyMDE4LTA1LTAyVDAzOjQ1OjE2LjI0OTgxMVoiLCJzdWJ0ZXN0cyI6eyJUZXN0IGZpbGUiOnsic3RhdHVzIjoiRkFJTCJ9fX0=

There, the third column is just gray.

**Comment by lukebjerring** [comment]
It doesn't do anything, sure, but what's the resolution here?

- Drop the column
- Show something in the column
- Add filtering button for only showing results which differ?

**Comment by foolip** [comment]
I'd like to see subtests that differ highlighted, with at least a simplified binary pass/not-pass interpretation of the subtest results. (If we include everything, in particular the exception messages, we'll see more flakiness that is for "good" reasons which shouldn't be fixed by changing the tests.)

**Comment by foolip** [comment]
https://staging.wpt.fyi/results/?product=chrome[experimental]&product=safari[experimental]&diff=true should be the equivalent URL now. Drilling down into https://staging.wpt.fyi/results/dom/historical.html?product=chrome[experimental]&product=safari[experimental]&diff=true now hides diff column after https://github.com/web-platform-tests/wpt.fyi/pull/417.
