### ISSUE TITLE
Are diff URLs stable?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#113]
This URL mentioned in https://github.com/web-platform-tests/wpt.fyi/issues/112:
https://master-dot-wptdashboard.appspot.com/results/dom/historical.html?before=eyJicm93c2VyX25hbWUiOiJjaHJvbWUiLCJicm93c2VyX3ZlcnNpb24iOiI2Ni4wLjMzNTkuMTM5Iiwib3NfbmFtZSI6ImxpbnV4Iiwib3NfdmVyc2lvbiI6IjQuNCIsInJldmlzaW9uIjoiYzgzYzUzZTBjYyIsInJlc3VsdHNfdXJsIjoiaHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3dwdGQvYzgzYzUzZTBjYy9jaHJvbWUtc3RhYmxlLWxpbnV4LXN1bW1hcnkuanNvbi5neiIsImNyZWF0ZWRfYXQiOiIyMDE4LTA1LTAyVDA4OjA2OjMwLjU2OTU5OVoiLCJzdWJ0ZXN0cyI6eyJUZXN0IGZpbGUiOnsic3RhdHVzIjoiRkFJTCJ9fX0=&after=eyJicm93c2VyX25hbWUiOiJzYWZhcmkiLCJicm93c2VyX3ZlcnNpb24iOiIxMS4wIiwib3NfbmFtZSI6Im1hY29zIiwib3NfdmVyc2lvbiI6IjEwLjEyIiwicmV2aXNpb24iOiI0M2RkMjVjODg4IiwicmVzdWx0c191cmwiOiJodHRwczovL3N0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vd3B0ZC80M2RkMjVjODg4L3NhZmFyaS0xMS4wLW1hY29zLTEwLjEyLXNhdWNlLXN1bW1hcnkuanNvbi5neiIsImNyZWF0ZWRfYXQiOiIyMDE4LTA1LTAyVDAzOjQ1OjE2LjI0OTgxMVoiLCJzdWJ0ZXN0cyI6eyJUZXN0IGZpbGUiOnsic3RhdHVzIjoiRkFJTCJ9fX0=

Is that long string off stuff stable, can it be kept working over the years as we migrate things to new technology stacks?

**Comment by lukebjerring** [comment]
The URL you're looking at is a Base64 encoding of a TestRun (before & after params). Provided the Model doesn't change too much, they'll be fine.

**Comment by foolip** [comment]
Ah, so that first part is `{"browser_name":"chrome","browser_version":"66.0.3359.139","os_name":"linux","os_version":"4.4","revision":"c83c53e0cc","results_url":"https://storage.googleapis.com/wptd/c83c53e0cc/chrome-stable-linux-summary.json.gz","created_at":"2018-05-02T08:06:30.569599Z","subtests":{"Test file":{"status":"FAIL"}}}`, interesting! That doesn't include a unique `configuration_id` (@Hexcles) but perhaps if that becomes the identifier perhaps some pretty trivial code could be written to derive one and keep supporting those URLs indefinitely even if the model changes.

**Comment by foolip** [comment]
@lukebjerring, this is obsolete, right?

**Comment by lukebjerring** [comment]
Yes; diff urls are now stable.
