### ISSUE TITLE
Duplicate (partial) runs from Azure Pipelines

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1130]
https://wpt.fyi/runs?label=master&max-count=100&from=2019-02-04T00%3A00 now looks like this:
![image](https://user-images.githubusercontent.com/498917/52557512-f1e10380-2def-11e9-8783-ec8d215e9dea.png)

At least for Azure Pipelines, there shouldn't have been this many actual runs on master.

@lukebjerring @Hexcles is it possible to find the source of each of these? I see that the raw report URLs and timestamps aren't the same, so maybe there's something wrong on the Azure Pipelines side?

**Comment by lukebjerring** [comment]
Yeah, this feels more like WAI from wpt.fyi's side. If the runs have different results (which, they will, because of flaky tests) and the processor gets told about a new report, it'll be consumed.

Buildbot is simple to explain (it ran 4 times, and the SHA didn't change). I'll leave it to you to work out why Azure re-triggered.

**Comment by Hexcles** [comment]
> Buildbot is simple to explain (it ran 4 times, and the SHA didn't change).

Is this a recent change?

**Comment by lukebjerring** [comment]
It runs twice? a day, and nothing got committed to the master branch between runs, so it ran the same SHA.

**Comment by foolip** [comment]
For Safari, looks like there are 4 runs every time now. Here are the latest side-by-side:
https://wpt.fyi/results/?run_id=5768297660284928&run_id=5696020138688512&run_id=5639321101008896&run_id=5635272658124800

There are 4 builds on Azure Pipelines related to "Fix canonical form of rotate property":
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=6446 (branch build for chromium-export-cl-1447844, nothing run)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=6447 (PR build for https://github.com/web-platform-tests/wpt/pull/15205, ran affected tests)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=6450 (branch build for master, nothing run)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=6454 (scheduled build for epochs/six_hourly, ran all the tests)

I downloaded the artifacts from Azure Pipelines and the raw reports from wpt.fyi. File sizes:
```
-rw-r--r--@ 1 foolip  eng    42M Feb 11 23:37 wpt_report_1.json
-rw-r--r--@ 1 foolip  eng    36M Feb 11 23:37 wpt_report_2.json
-rw-r--r--@ 1 foolip  eng    40M Feb 11 23:37 wpt_report_3.json
-rw-r--r--@ 1 foolip  eng    48M Feb 11 23:37 wpt_report_4.json
```

```
-rw-r--r--  1 foolip  eng    88M Feb 12 00:41 5635272658124800.json
-rw-r--r--  1 foolip  eng   166M Feb 12 00:40 5639321101008896.json
-rw-r--r--  1 foolip  eng   124M Feb 12 00:40 5696020138688512.json
-rw-r--r--  1 foolip  eng    40M Feb 12 00:39 5768297660284928.json
```

The size of a merged report should be 166, and that is the size of the largest. But the sizes of the other runs suggest they are reports with 1, 2 and 3 of the shards respectively.

@lukebjerring if the code hasn't changed recently, perhaps there is something about the Azure Pipelines API that's changed to cause this mishap?

When resolved, we should also delete the partial runs. Results receiver-side validation of runs would also have helped stop the bad runs from appearing on wpt.fyi.

**Comment by foolip** [comment]
looks at the start and end time also support something like that. The start time is the same but the end time varies, which would happen if the shard that started first is included in all.

**Comment by foolip** [comment]
I've checked the logs and /api/checks/azure/7093 for https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=7093 appears only once and still there are 10 duplicates runs for commit 3a43f99.

@lukebjerring what are the other callbacks that will cause us to fetch results from Azure Pipelines? Perhaps Azure Pipelines have begun updating checks or statuses, and we're reacting to those?

**Comment by foolip** [comment]
Looks like the order of arrival of the dupes isn't reliable, so the wpt.fyi now included an incomplete Safari run:
https://wpt.fyi/results/?run_id=5131360788283392&run_id=6330953542664192&run_id=5168126949851136&run_id=5648322245165056

I noticed when trying to use https://github.com/web-platform-tests/wpt.fyi/pull/1150, because of the missing Safari results there also appeared to be much fewer Chrome-only failures (200) than expected (800).

Looking at https://github.com/web-platform-tests/wpt/commits/3a43f99a56a4c016e3f1cda41330f1a2c0e780ff I think I see the problem now. https://github.com/web-platform-tests/wpt/runs/64967165 is showing a run for each job, i.e. scheduled builds on Azure Pipelines no longer need the wpt.fyi hook workaround that we had.

In addition to removing that workaround, we also need some logic to wait for all Azure Pipelines jobs to finish before trying to ingest the results. The easiest would be to just wait for the whole suite to finish, but that would mean that if we're running multiple browsers in the same build, the slowest would block the rest showing up in wpt.fyi.

@lukebjerring @Hexcles do either of you have the free cycles to rejig the Azure integration for this?

**Comment by Hexcles** [comment]
Is there no way to define a nested job (a job containing multiple subtasks) on Azure? It sounds like a common feature of CI systems (useful whenever tests need sharding). In addition to duplicated runs on wpt.fyi, the GitHub Checks UI isn't pretty too (with lots of jobs under Azure).

**Comment by foolip** [comment]
@Hexcles this is https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#strategies, described as "strategies for duplicating a job". Even when the jobs depend on other jobs in a DAG, I don't think it's possible to get the DAG out at the other end, it's just a flat list of jobs.

I agree the Checks UI looks pretty terrible now, I've asked Microsoft about a way to just have one check run per pipeline.

**Comment by foolip** [comment]
Reopening because all the partial runs still need to be deleted.

**Comment by foolip** [comment]
I'm not proficient with go, so I wrote this JS code to do it
```js
'use strict';

const assert = require('assert');
const fetch = require('node-fetch');
const {Datastore} = require('@google-cloud/datastore');

async function deletePartialSafariRuns() {
  const datastore = new Datastore({ projectId: 'wptdashboard-staging' });

  const url = 'https://staging.wpt.fyi/api/runs?product=safari&labels=azure,master&max-count=500';
  const runs = await (await fetch(url)).json();
  for (const run of runs) {
    const summary = await (await fetch(run.results_url)).json();
    const testNames = Object.keys(summary);
    console.log(`Considering https://staging.wpt.fyi/results/?run_id=${run.id} with ${testNames.length} tests @${run.revision}`);
    if (testNames.length < 24000) {
      console.log(`Deleting ${run.id}...`);
      const key = datastore.key(['TestRun', run.id]);
      const records = await datastore.get(key);
      assert(records.length === 1);
      const record = records[0];
      const labels = new Set(record.Labels);
      for (const expectedLabel of ['azure', 'safari', 'master', 'experimental', 'preview']) {
          assert(labels.has(expectedLabel), expectedLabel);
      }
      const result = await datastore.delete(record[datastore.KEY]);
      console.log(result);
    }
  }
}

deletePartialSafariRuns();
```

I've run it and looks good for staging, will do it on prod now.

**Comment by foolip** [comment]
Alright, here's what I ran for prod:
```js
'use strict';

const assert = require('assert');
const fetch = require('node-fetch');
const {Datastore} = require('@google-cloud/datastore');

async function deletePartialSafariRuns() {
  const datastore = new Datastore({ projectId: 'wptdashboard' });

  const url = 'https://wpt.fyi/api/runs?product=safari&labels=azure,master&max-count=500';
  const runs = await (await fetch(url)).json();
  for (const run of runs) {
    const summary = await (await fetch(run.results_url)).json();
    const testNames = Object.keys(summary);
    if (testNames.length < 30000) {
      console.log(`Deleting https://wpt.fyi/results/?run_id=${run.id} with ${testNames.length} tests @${run.revision}`);
      const key = datastore.key(['TestRun', run.id]);
      const records = await datastore.get(key);
      assert(records.length === 1);
      const record = records[0];
      const labels = new Set(record.Labels);
      for (const expectedLabel of ['azure', 'safari', 'master', 'experimental', 'preview']) {
          assert(labels.has(expectedLabel), expectedLabel);
      }
      const result = await datastore.delete(record[datastore.KEY]);
      console.log(result);
    } else {
      console.log(`Keeping https://wpt.fyi/results/?run_id=${run.id} with ${testNames.length} tests @${run.revision}`);
    }
  }
}

deletePartialSafariRuns();
```

**Comment by foolip** [comment]
Reopening again, until there's a new prod release of wpt.fyi, dupes will keep happening there. When it's been deployed, those dupes have to be removed one final time.

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/wpt.fyi/issues/1171

**Comment by Hexcles** [comment]
Let's leave this open until we clean up all the partial runs from prod.

@lukebjerring let me know when all pieces are in place in prod and there's no more partial/duplicate runs being produced. I'll run a batch script to mark & clean all the partial runs.

**Comment by Hexcles** [comment]
@foolip said he'd already made the script. Then we just need to run it again when the prod release is completed.

**Comment by foolip** [comment]
Yep, it's https://github.com/web-platform-tests/wpt.fyi/issues/1130#issuecomment-466391715, a fun mix of any API backed by datastore and poking datastore directly :)

**Comment by foolip** [comment]
With https://github.com/web-platform-tests/wpt.fyi/issues/1171 done, and I've run the cleanup script again. Thanks @lukebjerring and @Hexcles for helping sort this out!
