### ISSUE TITLE
Structured Queries issue: query builder clears search box

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1133]
### Search
A link to the search containing my issue:
 
https://wpt.fyi/results/?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=%28chrome%3A%21pass%26chrome%3A%21ok%29+%28edge%3Apass%7Cedge%3Aok%29+%28firefox%3Apass%7Cfirefox%3Aok%29+%28safari%3Apass%7Csafari%3Aok%29

### Description

From that link, click edit to change the set of browsers and delete Edge. Submit and be redirected to https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned without the search filter.

**Comment by lukebjerring** [comment]
Weirdly, also works as expected the second time it's submitted. Seems to be reverting the search state on submit.
