### ISSUE TITLE
In /runs, link to /results/run_id=...

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1138]
Trying to understand an issue like https://github.com/web-platform-tests/wpt.fyi/issues/1130, it would be most helpful if one could get to each individual run by clicking the browser icons. This should now be possible with the `run_id` parameter.

**Comment by lukebjerring** [comment]
Fixed via https://github.com/web-platform-tests/wpt.fyi/pull/1164
