### ISSUE TITLE
"Only show differences" has no effect

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt.fyi#1146]
Steps to reproduce

1. Visit https://staging.wpt.fyi/runs
2. Select "Edit"
3. Remove two products
4. Enable "Show diff"
5. Click "Submit"
6. Click the button labeled "Toggle filtering to only show differences"

Expected result: UI is refreshed to display only differing test results

Actual result: UI does not change (and no information is printed to the developer console)

Tested in Firefox 65 and Chromium 71.0.3578.98

**Comment by Hexcles** [comment]
Seems like a regression: I wasn't able to reproduce the issue at first, but after Ctrl+F5 I can now reproduce (which is also concerning: is something wrong with the cache invalidation in our service worker?).

**Comment by lukebjerring** [comment]
Service workers can take a few reloads to kick in (install/activate).

**Comment by lukebjerring** [comment]
This is likely a consequence of https://github.com/web-platform-tests/wpt.fyi/pull/1129

The diff may be failing to omit empty entries when the diff `filter` param doesn't include `U`
