### ISSUE TITLE
No "safari[experimental]" check

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1160]
### Check
A link to the GitHub Check run containing my issue:
https://github.com/web-platform-tests/wpt/pull/15475/checks

### Description

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=7349 ran the affected tests, but the results didn't show up on staging.wpt.fyi:
https://staging.wpt.fyi/results/?sha=ed55be4

It did show up in prod:
https://wpt.fyi/results/?sha=ed55be4

**Comment by foolip** [comment]
Filed https://github.com/web-platform-tests/wpt.fyi/issues/1161 about the checks not showing up for wpt.fyi.

**Comment by foolip** [comment]
This was a problem in https://github.com/web-platform-tests/wpt/pull/15577.

Looking at https://wpt.fyi/runs?label=pr_head there's definitely something weird going on, Safari results are appearing but not for the same SHAs as Chrome and Firefox. It looks like the SHAs of the synthetic merge commits are being used.

@lukebjerring where does the sha rewriting happen?

**Comment by foolip** [comment]
This also explains why I've been seeing br_base results for Safari showing up for shas from master when not filtered to the mater label, but haven't been seeing the same for Chrome and Firefox.

**Comment by lukebjerring** [comment]
The last time pr_head was aligned was Feb 25 @ 10.59
3744dfb93c787a634bdb5908b8399cece157ae5e was committed at 11:13... I smell a suspect.

**Comment by lukebjerring** [comment]
Well that was a false lead, but it was definitely switching to the hook that did it. We just need to fetch a little extra from the Azure Pipelines build info.

**Comment by foolip** [comment]
Ah, that makes sense.
