### ISSUE TITLE
Azure webhook is incorrectly labelling all runs as 'master'

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1167]
https://staging.wpt.fyi/results/?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned&q=%28firefox%3A%21pass%26firefox%3A%21ok%29+%28chrome%3Apass%7Cchrome%3Aok%29+%28edge%3Apass%7Cedge%3Aok%29+%28safari%3Apass%7Csafari%3Aok%29

I got this link from https://staging.wpt.fyi/insights

**Comment by lukebjerring** [comment]
This is WAI - the edge run is empty.

**Comment by lukebjerring** [comment]
Let's change this issue to correctly reflect the reason for the problem and go from there.

**Comment by lukebjerring** [comment]
The master label is actually correct - this is #1130 in action again.
