### ISSUE TITLE
Deploy 03bc0e6 to production (2019-02-22)

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1171]
Changelist df6142a...03bc0e6
 - Improved autocomplete to help discover structured query atoms
 - Increased the width of the UI
 - Compute diffs using the searchcache (compares actual subtests, not summary counts)
 - Change the way we handle azure artifacts

**Comment by lukebjerring** [comment]
Rolled 03bc0e6 out for 50% webapp and 100% all other services.

**Comment by Hexcles** [comment]
Everything is 100% now. Closing the issue.
