### ISSUE TITLE
Azure artifacts filtering doesn't work

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1174]
The filtering added in https://github.com/web-platform-tests/wpt.fyi/pull/1162 doesn't appear to work, at least not with post parameters.

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=7836 ran both Edge and Safari in the same build, and invoked the hook twice. Safari finished first and when the hook was invoked it appears the partial Edge results were ingested too. I took this screenshot while the Azure Pipelines build was still running the remaining Edge jobs to show it in action:
![screenshot_20190223-150735](https://user-images.githubusercontent.com/498917/53288898-c4e90500-378e-11e9-8282-0c0931678faa.png)

By now the build has finished and there are two runs, one partial:
https://staging.wpt.fyi/results/?run_id=6395795523764224&run_id=5352350130634752

These Edge runs aren't showing up in prod yet, but they are in datastore with product name edge_webdriver. If we rename those later to show them, we should delete the partial runs. Scripts in https://github.com/web-platform-tests/wpt.fyi/issues/1130 can be used.

**Comment by lukebjerring** [comment]
The received request did not contain a filter parameter. It was just `/api/checks/azure/7836`.

**Comment by foolip** [comment]
Fixed on master but not deployed yet.

**Comment by lukebjerring** [comment]
Fixed in 3744dfb93c787a634bdb5908b8399cece157ae5e 
Deployment covered by #1187

**Comment by foolip** [comment]
Sweet, once this is in prod we can start running more than one browser in scheduled builds.
