### ISSUE TITLE
Handle Taskcluster via checks API

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1182]
After https://github.com/web-platform-tests/wpt/pull/14859 was merged the wpt.fyi checks stopped working. I reverted in https://github.com/web-platform-tests/wpt/pull/15576.

In hindsight it's obvious that this wouldn't work, wpt.fyi uses the status API and would now have to look at the checks API.

Hopefully looking at these PRs which did use the checks reporting can reveal what the integration needs to be:
https://github.com/web-platform-tests/wpt/pull/15575/checks?check_run_id=69693004
https://github.com/web-platform-tests/wpt/pull/15577/checks?check_run_id=69709294

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1183
