### ISSUE TITLE
Deploy e98abaa to production (2019-02-28)

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1187]
Changelist 03bc0e6...e98abaa:
 - CheckRunEvent handling fixes
 - Screenshot storage API

**Comment by lukebjerring** [comment]
@Hexcles, I'll hand this over to you to ensure new indexes are set up etc.

**Comment by Hexcles** [comment]
webapp is running at 50%; everything else is running at 100%.

**Comment by Hexcles** [comment]
The new bucket `wptd-screenshots` has been created in prod with the proper permissions and CORS settings. Datastore index for `Screenshot` is created but may take a while to finish indexing (we don't have any screenshots yet, so it doesn't really matter).

**Comment by Hexcles** [comment]
webapp 100%

**Comment by lukebjerring** [comment]
Following up with a push of bd141e0 for webapp too, to resolve #1160
