### ISSUE TITLE
Safari runs from Azure Pipelines not labeled as master

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1195]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=8620

This is a run that finished but wasn't labeled as master on prod or staging:
https://wpt.fyi/results/?run_id=5700126081286144
https://staging.wpt.fyi/results/?run_id=5158773538684928

Perhaps a regression from https://github.com/web-platform-tests/wpt.fyi/pull/1180, @lukebjerring?

**Comment by foolip** [comment]
Script to list runs which could be master runs:
```js
'use strict';

const fetch = require('node-fetch');

async function listMissingMasterLabels() {
  const url = 'https://wpt.fyi/api/runs?product=safari&labels=azure&max-count=500';
  const runs = await (await fetch(url)).json();
  for (const run of runs) {
    const labels = new Set(run.labels);
    if (!['master', 'pr_base', 'pr_head'].some(l => labels.has(l))) {
      console.log(`https://wpt.fyi/results/?run_id=${run.id}`);
    }
  }
}

listMissingMasterLabels();
```

It currently lists:
https://wpt.fyi/results/?run_id=5700126081286144
https://wpt.fyi/results/?run_id=5768958401576960
https://wpt.fyi/results/?run_id=5762029780467712

**Comment by lukebjerring** [comment]
Looks like I forgot to actually use the epoch regex.

**Comment by lukebjerring** [comment]
https://dev.azure.com/web-platform-tests/wpt/_apis/build/builds/8683

> "sourceBranch": "refs/heads/epochs/six_hourly"

**Comment by foolip** [comment]
@lukebjerring will there be a new prod release with this fix soon?

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/wpt.fyi/issues/1203

**Comment by foolip** [comment]
There are still some runs that need to be labeled to prod. @Hexcles, I don't know how to add a label, can you tweak a go script to do it?

**Comment by Hexcles** [comment]
Retroactive labelling was done in #1175
