### ISSUE TITLE
API regularly returned 422 No Reason Phrase

### ISSUE THREAD

**Issue by AutomatedTester** [web-platform-tests/wpt.fyi#1199]
I have been using https://jgraham.github.io/wptdash to track firefox only failures and it regularly hits a 422 error from wpt.fyi

This was happening when we were accessing staging so we have moved to prod and the issue continues. The URL in question is below.

https://wpt.fyi/api/search?label=master&product=chrome%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D 

I am not sure if this is a variation of #759?

**Comment by lukebjerring** [comment]
422 is Unprocessable Entity, which is the error code we use when a run you're querying for has not been loaded into the searchcache (yet). We have a write-on-read behaviour that will begin loading it the first time it's requested.

wpt.fyi has a 5 retries 5 seconds apart behaviour built in; that's the toast message (trying again...) you may have seen.

**Comment by Hexcles** [comment]
@AutomatedTester the API should no longer return 422. Sorry that the prod release took a bit longer than we'd like due to some internal hiccups.

However, @jgraham 's dashboard is now complaining about error 500 from some Taskcluster API...

**Comment by Hexcles** [comment]
Fixed by #1212 .
