### ISSUE TITLE
Diffing feature of reftest analyzer does not work on Firefox

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1225]
Example: https://staging.wpt.fyi/analyzer?screenshot=sha1%3A339d253814be71ad2052253c38020082d003598c&screenshot=sha1%3A26802d00e57a78123a7a789c81502f0cafee27ab

Reported by @gsnedders

**Comment by Hexcles** [comment]
@foolip I imagine something is wrong with our SVG magics. Before I dive into the details, do you know off the top of your head what might not work on Firefox? Here's the SVG template: https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/components/reftest-analyzer.js#L84

**Comment by foolip** [comment]
No, I can't immediately tell by looking in Firefox devtools what's causing this. What is the input that the filters are acting on, can you first verify that it's not the input that's empty?

**Comment by gsnedders** [comment]
It appears to be that the DOM is getting constructed incorrectly, not the SVG going wrong. Dumping the DOM from Chrome and loading it in Firefox shows it working fine.

**Comment by gsnedders** [comment]
The rect seems to be 0x0 on Firefox.

The first notable difference is:

```
<style>
  rect {
      width: 100%;
      height: 100%;
  }
</style>

<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600">
  <rect fill="blue"></rect>
</svg>
```

This results in no output in Firefox, but does in Chrome. This is changed behaviour in SVG2 (making it styleable by CSS). Not totally sure there is a bug in Bugzilla for that.

**Comment by gsnedders** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1536469
