### ISSUE TITLE
Reftest "compare" results seem to be showing broken images

### ISSUE THREAD

**Issue by tabatkins** [web-platform-tests/wpt.fyi#1245]
In a test like <https://staging.wpt.fyi/results/css/css-content/element-replacement.html?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned>, the reftest "compare" button loads up a page that just shows broken images <https://staging.wpt.fyi/analyzer?screenshot=sha1%3A3e5e80df178687ec83e24ecfe57582a99992ad17&screenshot=sha1%3A232ebf37746e2fbd2b27f003c2cd9196632ba4bc>.

**Comment by tabatkins** [comment]
ping @Hexcles

**Comment by Hexcles** [comment]
This run is from BuildBot. I forgot to change results-collection to enable the screenshot logging.

**Comment by foolip** [comment]
@Hexcles I guess additional work needed for https://github.com/web-platform-tests/wpt/pull/16107 and https://github.com/web-platform-tests/wpt/pull/16108 to get screenshots as well?

**Comment by Hexcles** [comment]
#16107 is fine; the necessary command line arg was already added. I commented on #16108 .

**Comment by Hexcles** [comment]
I'm closing this as "fixed", because 1. new runs should have screenshots; 2. when historical runs are missing screenshots, we now show an error message with a link to file an issue.
