### ISSUE TITLE
500 Internal Server Error in Azure Pipelines webhook

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1288]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=14311&view=logs says:
```
curl -f -s -S -d "artifact=safari-preview-affected-tests" -X POST https://wpt.fyi/api/checks/azure/14311
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/1f3640c5-07d2-4390-8bce-066d93476d2d.sh
curl: (22) The requested URL returned error: 500 Internal Server Error
```

This was for https://github.com/web-platform-tests/wpt/pull/16453/checks?check_run_id=114711407 and it doesn't matter too much, but if this happens for full runs we could lose a day of aligned runs.

**Comment by foolip** [comment]
@lukebjerring does this happening result in some automated notification? Or put differently, if this started happen consistently, would we notice?

**Comment by lukebjerring** [comment]
No; it would only get noticed on the PR (in absence). Let's tie this into the lifecycle/validation

**Comment by foolip** [comment]
@Hexcles ^

**Comment by foolip** [comment]
Dupe of https://github.com/web-platform-tests/wpt.fyi/issues/1406 which is newer but had more cases.
