### ISSUE TITLE
wpt.fyi/* routes are future hostile

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#13]
_From @rwaldron on January 18, 2018 20:40_

If https://github.com/w3c/web-platform-tests were to ever grow a new top level directory for some hypothetical spec named "api", "interop", "results", or "test-run", then routing in webapp/main.go becomes ambiguous. 

_Copied from original issue: w3c/wptdashboard#374_

**Comment by lukebjerring** [comment]
_From @boazsender on January 19, 2018 17:38_

+1, test results routes should be name spaced.

For the `/interop` example in #372, it's worth mentioning that the [compat spec](https://compat.spec.whatwg.org) could have just as easily been called "interop". We have tests for that spec, and the `/compat` route is in the global name space (see https://wpt.fyi/compat).

**Comment by lukebjerring** [comment]
_From @rwaldron on January 19, 2018 17:48_

Honestly, the only truly safe solution is the one that breaks all the existing inbound links, ie. wpt.fyi/test/path.html => wpt.fyi/some-safe-path/test/path.html, but that might be the price to pay for rushing this out.

**Comment by lukebjerring** [comment]
We can redirect the current wildcard matches to /some-safe-path/, mitigating breakages to current links to clashes only.

**Comment by lukebjerring** [comment]
_From @rwaldron on January 19, 2018 19:23_

@lukebjerring yep, that's what was I thinking (and what brought me back here just now to follow up on). I don't want to rush into this yet.

**Comment by lukebjerring** [comment]
This issue is related to the Q1 OKR of switching the default view to the interop view:
https://docs.google.com/document/d/1ojlLDiRruI4e95Z7JQ10JQPRMiQHd_40rBkYCL6IJqw/edit#heading=h.v93ez0y7fvmy

**Comment by Hexcles** [comment]
I came across this when writing my design doc for the results receiver.

Currently, we have a few API endpoints in `wptf.fyi/api`. Shall we perhaps use `wpt.fyi/_api/` instead, especially considering most of these APIs are internal to the project?

**Comment by lukebjerring** [comment]
Not an important distinction, IMHO. After https://github.com/web-platform-tests/wpt.fyi/pull/47, there won't be a clash, and there currently isn't a clash, so should be no existing (incorrect) links.

`/api/` links will be in a fair few pieces of code already.

**Comment by lukebjerring** [comment]
Resolved by https://github.com/web-platform-tests/wpt.fyi/pull/47
