### ISSUE TITLE
PR results fail to load

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1308]
### Check
A link to the GitHub Check run containing my issue:
https://github.com/web-platform-tests/wpt/pull/16788/checks?check_run_id=124826939
https://github.com/web-platform-tests/wpt/pull/16788/checks?check_run_id=124827047
https://github.com/web-platform-tests/wpt/pull/16788/checks?check_run_id=124825192

### Description
Following the "Visual comparison of the results" links doesn't work, they say "Failed to fetch test runs" and in the devtools network tab I see a POST to https://wpt.fyi/api/search?diff=true&filter=ADC which failed with 500, response being "Error connecting to search API cache".

**Comment by foolip** [comment]
I suspected something related to the service worker, but loading https://wpt.fyi/results/?diff&filter=ADC&run_id=5707609709477888&run_id=6213144875630592 in an incognito window still doesn't work.

**Comment by Hexcles** [comment]
Closing this as fixed. Feel free to reopen if this happens again.

**Comment by foolip** [comment]
Confirmed my link works now.
