### ISSUE TITLE
`npm install` is broken on Travis

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1330]
Example: https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/204013637

```
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/content-v2/sha512/0b/00'
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/index-v5/b8/3c'
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/content-v2/sha512/0b/a9'
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/user/.npm/_cacache/index-v5/b8/36'
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-29T19_27_04_108Z-debug.log
Makefile:91: recipe for target 'webdriver_node_deps' failed
make: *** [webdriver_node_deps] Error 1
```

**Comment by Hexcles** [comment]
Apparently the problem is more general: `npm install` is now broken on Travis. Disabling just `puppeteer_chrome_test` does NOT fix the problem, and now we are seeing the same error in other tests as well. We haven't changed anything regarding the npm setup, nor have we updated our `package-lock.json` recently. I have no idea why this is happening. cc @foolip who also played a lot with `npm` recently.

**Comment by foolip** [comment]
I've never seen anything like this before where npm claims the bug is with itself. Have you tried locking down the node version to something other than the latest release, to roll back? Not sure if that also changes the version of npm, but I suspect it does.

**Comment by Hexcles** [comment]
@foolip yes I've tried creating a fresh Docker image & instance locally but couldn't reproduce the error. Everything happens inside Docker so supposedly I should get the same `npm` as on Travis.

**Comment by Hexcles** [comment]
Oh FML. Turns out, it's the `sudo npm install -g npm` that broke everything:
https://github.com/web-platform-tests/wpt.fyi/blob/a2baf053e36159205a4e70caef621642d7c50817/Makefile#L118

This is extremely tricky to debug because usually this step is a no-op as the Docker image is newly built and `npm` comes with the freshly installed `nodejs` package from Nodesource. However, when there is a newer version of `npm` than the one in the `nodejs` package:
1. The line above will try to install it using **root**.
2. And due to some env var mishap, `/home/user/.npm` is still used as the cache directory even though we are running as `root`.
3. A bunch of subdirectories will get created there that belong to `root` during the install process.
4. Later when we do `npm install` as `user`, we don't have enough permission to modify those directories created in step 3.
