### ISSUE TITLE
Edge Dev run incorrectly labeled as stable

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1344]
https://wpt.fyi/results/?run_id=230810012 is the first run from https://github.com/web-platform-tests/wpt/pull/16920.

It came from this build:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=18447

Maybe it would be fixed by https://github.com/web-platform-tests/wpt/pull/17224, but I wonder if the run_info shouldn't include this information anyway/already?

**Comment by Hexcles** [comment]
Thanks, Philip! I'm fairly certain https://github.com/web-platform-tests/wpt/pull/17224 is the fix; I missed that during code review.

We do need to explicitly set that flag, unfortunately. wptrunner does not infer the browser channel itself.

**Comment by Hexcles** [comment]
Also manually fixed the existing test runs on prod and staging.

**Comment by foolip** [comment]
Confirmed fix in https://wpt.fyi/runs and looks like you relabeled the previous runs?

**Comment by Hexcles** [comment]
Yes, I did.
