### ISSUE TITLE
Use new official Edge logos

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1347]
We need to update our Edge icons: https://www.microsoftedgeinsider.com/en-us/download/

Besides, the channel <-> logo mapping for Edge seems wrong (we're showing the beta logo for the dev channel at the moment).

**Comment by lukebjerring** [comment]
Previously, Beta was the only logo that existed (and dev was a wpt.fyi classification, not a Microsoft name). 

That's changed recently, apparently!
