### ISSUE TITLE
Use Renovate or Dependabot to stay on top of `npm audit` issues

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1355]
Running `npm audit` in webapp/ currently shows issues.

The situation was pretty bad in https://github.com/GoogleChromeLabs/confluence and took some work to fix, but feels much easier to keep in good shape after setting up. https://renovatebot.com/. There's also https://dependabot.com/ which was acquired by GitHub and I've had success switching from Renovate to that in https://github.com/foolip/mdn-bcd-collector/.

Recommendation: try enabling Dependabot, see how it goes.

**Comment by Hexcles** [comment]
All `npm audit` issues are transitive dependencies of our testing (dev) dependencies. And they are already at the newest the versions our immediate dev deps would allow -- the most annoying case is `web-component-tester` which is being deprecated, hasn't been updated for a long time and bundles in a *lot* of outdated libraries.

So while using Renovate is a good idea, it wouldn't really get us out of the security warnings. We might have to move to the new `wct-mocha` package.

**Comment by foolip** [comment]
Ah, have you been running `npm up` regularly, or why haven't our deps gone stale?

**Comment by Hexcles** [comment]
Once in a while, whenever I'm trying to fix front-end test breakage (which unfortunately happens quite often).

**Comment by Hexcles** [comment]
Fixed by #1555 .
