### ISSUE TITLE
Virtual navigation is causing searches to have + instead of spaces

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1375]
Steps to repro:
- Load wpt.fyi
- Write a query with 2 atoms, separated by a space, e.g. `chrome:fail safari:pass`
- Submit said query
- Copy the URL in the address bar, paste it another tab
- Results fail to load.
- Search bar now contains a +

The URL copied from the LINK button in the info bar seems to work fine.

**Comment by Hexcles** [comment]
Playing with the previous versions in prod, I can confirm that the regression happened in this push: https://github.com/web-platform-tests/wpt.fyi/issues/1342 (i.e. bbe393a...5c27b47), so most likely another breakage caused by `app-route`.
