### ISSUE TITLE
Add support for displaying subtest in wpt-metadata 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#1401]
Per James Graham comments in the email thread, it is important to support triaging 
use cases where different subtests may be affected by entirely different 
bugs.

Documentation changes:
Add an optional subtest field in wpt-metadata repo README
Documentation changes

API changes:
api/metadata? will return one additional data field - subtest

Display Metadata UI changes:
Displaying subtest in the metadata
-  If path is a subfolder, only show the tests which have been triaged, do not display subtest information.
- if path is a test, show all subtests under this test which have been triaged

Amend Metdata UI changes:
support amending subtests in the UI

**Comment by KyleJu** [comment]
@lukebjerring thoughts on the UI changes to display subtests?

**Comment by lukebjerring** [comment]
If _any_ of the visible set of results is relevant to the metadata/link, it should be shown. For that reason, it might be best to return metadata from the searchcache, and only use a separate fetch when looking at an unfiltered view.

But, regarding subtests, if the subtests is being included in the summary numbers, include the metadata/link.

**Comment by KyleJu** [comment]
> If _any_ of the visible set of results is relevant to the metadata/link, it should be shown. For that reason, it might be best to return metadata from the searchcache, and only use a separate fetch when looking at an unfiltered view.

Good point. Alternatively, we can filter metadata based on directories displayed ( from displayedNodes) on the page

> 
> But, regarding subtests, if the subtests is being included in the summary numbers, include the metadata/link.

I am afraid that it might be too many subtests at some points. What if we only display subtests in the subtest result page

**Comment by KyleJu** [comment]
This has been fixed
