### ISSUE TITLE
Using unminified, unbundled modules is very slow and inefficient

### ISSUE THREAD

**Issue by chris-morgan** [web-platform-tests/wpt.fyi#1405]
When you load the website, it’s loading unminified source spread across a large number of files, using many `import` statements. In total it loads about 222 files.

This is unreasonable. Browsers supporting modules natively is not a valid excuse for using many small files, which will inevitably perform worse than bundling all the JS into one file, since it has to load files before it can know which further files need to be fetched (so some of the loading is serial). In Australia (>150ms latency, and the server is regularly taking a *lot* longer than that to respond), it’s taking more than 12 seconds just to fetch it all, when it should be taking less than one second.

All of the code should be fed through a tool like Rollup, to reduce those more than two hundred requests down to, at a guess, five. Preferably through a tool like Terser too for minification, because the 2MB of JS could probably be shrunk quite a bit that way.

Doing this will immediately improve load performance *vastly*, and reduce the load on the server substantially too.

**Comment by lukebjerring** [comment]
Hi Chris, thanks for the report. FWIW, this is a known issue, and we are making refactoring steps towards being able to leverage the polymer-cli build step, which indeeds bundles all the deps (using Babel to transpile, I believe.)

The site was originally written in Polymer 1 with HTML imports, so the migration/improvement takes several steps (each causing a range of regressions on poorly tested areas).

**Comment by Hexcles** [comment]
Merged into #1581
