### ISSUE TITLE
Revision announcer returned wrong commit

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1416]
https://github.com/web-platform-tests/wpt-pr-bot/issues/74 has evidence (logs from wpt-pr-bot) that at one point the revision announcer return a commit (0c69b971f41f48daf39199963f96af76a9ad7fb2) which wasn't the last before 6:00 UTC.

This should never happen, as the revision announcer should wait for long enough after 6:00 UTC to be certain that any commits before then are observed.

@Hexcles do we have logs that might reveal the timing here? Do you know what things might add delay to the system, in particular is the Go in-memory Git implementation used here and being updated with some delay?

**Comment by foolip** [comment]
I believe that all builders that run WPT on a schedule now use the epochs/* branches, so if fixing this in the revision announcer is complex, we could also consider migrating to some other way of updating those branches. However, it seems unavoidable that *something* needs to look at the current time and make guesses about what GitHub's time is and how long it might take at most for change to propagate.

(One solution that would avoid polling is to let the branch track the first commit *after* the cutoff point, using GitHub actions triggered by the commit itself to update the branch. However, this would delay results if there happens to not be a commit for a long time, which is why we went with the commit *before* the cutoff time originally.)

**Comment by foolip** [comment]
@Hexcles did you review the code for the revision announcer, any guess on why this might be happening?

**Comment by Hexcles** [comment]
Closing as wontfix (see #1738 )
