### ISSUE TITLE
Tests with slashes in query string not shown correctly

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1430]
https://github.com/web-platform-tests/wpt/pull/18414 introduced a test which uses variants like this:
```html
<meta name="variant" content="?q=cts:buffers/create_mapped:">
<meta name="variant" content="?q=cts:buffers/map:">
<meta name="variant" content="?q=cts:buffers/map_detach:">
<meta name="variant" content="?q=cts:buffers/map_oom:">
<meta name="variant" content="?q=cts:canvas/context_creation:">
<meta name="variant" content="?q=cts:command_buffer/basic:">
<meta name="variant" content="?q=cts:command_buffer/compute/basic:">
<meta name="variant" content="?q=cts:command_buffer/copies:">
<meta name="variant" content="?q=cts:command_buffer/render/basic:">
<meta name="variant" content="?q=cts:command_buffer/render/rendering:">
<meta name="variant" content="?q=cts:examples:">
<meta name="variant" content="?q=cts:fences:">
```

The results of these tests should be here:
https://wpt.fyi/results/webgpu?run_id=306280007&run_id=292860002&run_id=289070005&run_id=294680004

But:
![image](https://user-images.githubusercontent.com/498917/63420359-cd04c300-c406-11e9-8603-142adccd2908.png)

Because of the slash in the query string, some of these are treated as directories, but drilling down into the directories doesn't work.

Note that this is new, when I wrote this no tests like this existed:
https://github.com/foolip/ad-hoc-wpt-results-analysis/blob/4c5210e1ab96e92fdd99841112bab3dc4e43763a/git-write.js#L111-L112

The problem might be just in the UI, but possibly also in results processing and in the search cache.

@lukebjerring @Hexcles

**Comment by foolip** [comment]
@kainino0x in case you've looked at those results and wondered what's wrong, this is what's wrong :)

**Comment by lukebjerring** [comment]
This is almost surely a consequence of a  string.split on /

**Comment by foolip** [comment]
Yep, question is just in how many places :)

**Comment by kainino0x** [comment]
Oh yes, I keep forgetting to look into this. It's clear this has never been done before - we had a bug in Chromium's infra as well for the same reason.

Would it be easier if we just stopped using slashes in the variant strings?

**Comment by kainino0x** [comment]
BTW, I wasn't looking at the wpt.fyi results - this is a problem in the reports that `./wpt run` generates as well.
