### ISSUE TITLE
Front page not showing aligned runs by default

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1434]
This used to be the case. @lukebjerring

**Comment by lukebjerring** [comment]
Not sure when/how this got turned off - re-enabled the `experimentalAligned` feature.

**Comment by foolip** [comment]
Thanks!

**Comment by Hexcles** [comment]
Perhaps we need to better distinguish /flags and /admin/flags, otherwise
someone might accidentally flip the flags?
