### ISSUE TITLE
Deploy de18971 to production

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1446]
Changelist 4a1621e...de18971 :

- Screenshots in expanded mode when viewing failed reftests
- Diff filtering in single-file results views
- Fix bad URL decoding of space to + in searches
- Fix anomalies insight to use the master label
- Pressing n / p when focused on the body will move to next/prev test file
- `subtest:[subtest name]` test result filtering in structured search

**Comment by Hexcles** [comment]
webapp to 100%

Not promoting processor, waiting for #1451
