### ISSUE TITLE
Upgrade to Golang 1.11 before Oct 1

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1447]
https://cloud.google.com/appengine/docs/standard/go112/go-differences?hl=en_GB&_ga=2.146296567.-298454716.1563825783

Attempted in #1267 (so far, unsuccessfully).

**Comment by lukebjerring** [comment]
So uh, it's Oct 1. I'm rushing https://github.com/web-platform-tests/wpt.fyi/issues/1520 through, but I think we'll be blocked on future releases?

**Comment by lukebjerring** [comment]
https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/241467972

We're now unable to run the web_server.sh script in a fresh docker.

**Comment by Hexcles** [comment]
This has been completed.
