### ISSUE TITLE
Missing wpt.fyi checks

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1457]
In https://github.com/web-platform-tests/wpt/pull/18722 the Chrome and Firefox wpt.fyi checks weren't created, either for staging or prod.

Taskcluster as a whole did pass, so it's not because of stability checks failing which I first suspected.

**Comment by lukebjerring** [comment]
@foolip - this is actually working as intended; Taskcluster's use of `wpt job` ignores any changes to the `resources/` directory.

https://github.com/web-platform-tests/wpt/pull/18500 is the "fix", just waiting on review - it is distinguishing the stability check vs single-run cases, and letting idlharness.js trigger a single run.

**Comment by foolip** [comment]
Oh, so the reason we got Safari results is because we unconditionally run affected tests. (I did that to have results as fast as possible and most PRs do affect tests.)

**Comment by stephenmcgruer** [comment]
So the only remaining work here would be (if its not already happened) to make Safari runs not run unconditionally? Is that something we want to pursue @foolip or is it time to close this as fixed by #18500 ?

**Comment by foolip** [comment]
@stephenmcgruer this was resolved the other way around, after https://github.com/web-platform-tests/wpt/pull/18500 touching idlharness.js runs all of the idlharness tests, and https://github.com/web-platform-tests/wpt/pull/19611/checks shows it in action.
