### ISSUE TITLE
Missing ability to filter by *any* difference to spot changes in behavior

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1460]
In https://github.com/web-platform-tests/wpt/pull/11024#issuecomment-527248462 I was looking at this view:
https://wpt.fyi/results/?diff&filter=ADC&run_id=289790006&run_id=285580005

The two runs differ only by a change to testharness.js, and I'd like to see *any* difference. I suspect that `status:unknown` shows the interesting differences, but if anything else has changed without changing the overall pass rates, this wouldn't be visible.

**Comment by lukebjerring** [comment]
Need to think of a good name for this atom. Would probably lump it in the is:[meta info], e.g. is:flaky.

Maybe is:different, which filters to any row where the status aren't all identical (regardless of number of columns?)

**Comment by foolip** [comment]
`is:different` would certainly do the trick.

It's a different issue, but I'm not sure how this should interact with the diff view and API endpoint though. I guess switching to use the search cache for diffing on the server side would achieve much of the same effect, but that there's a UI challenge in representing changes from one type of failing to another.
