### ISSUE TITLE
Is `status:unknown` and `status:missing` the same?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1468]
https://github.com/web-platform-tests/wpt.fyi/blob/master/api/query/README.md#status doesn't document `status:missing`, is it just an alias of `status:unknown`?

**Comment by lukebjerring** [comment]
Yes, as per #1449. I'll leave this open until that's documented. The intention here was just to catch cases where users were using the UI representation as inspiration, since the backend representation is never shown visibly (besides the docs).
