### ISSUE TITLE
Implement uploader authentication

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#147]
#142 doesn't have authentication yet.

According to the [design doc](https://docs.google.com/document/d/1F3GWJ6lA8C3S5WgyJgXxmTFzu92mqF-1ddGije67ork/edit?ts=5ade260c#heading=h.2u8ziqsev0mm), the plan is to use HTTP basic authentication, and the registration is done manually by admins.

We'd need to store the usernames and (generated) tokens somewhere (probably Datastore). And when the incoming POST isn't from an admin, we need to check the basic authentication header against our DB, and probably log the access.

Lastly, it's very important to double check we have HSTS in place.

**Comment by lukebjerring** [comment]
@Hexcles - could you jot down a tasklist of what we would consider complete for this work?

**Comment by Hexcles** [comment]
@lukebjerring I think the code is complete for this issue. Could you generate and store some random tokens for existing runners? I'm thinking the following list of uploaders/runners:

* buildbot
* edge
* taskcluster

Alternatively, we can use their respective organizations as the names.

**Comment by Hexcles** [comment]
Moving the secret generation task to #192 and closing this issue as the implementation part is completed.

**Comment by lukebjerring** [comment]
Generated for buildbot, edge, taskcluster, travis. See appengine datastore for passwords when needed.
