### ISSUE TITLE
Support chunked wptreports (from Taskcluster)

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#148]
Taskcluster doesn't have a results merger as of now. In order to receive results from it, we'd need the following pieces:

## An adapter reacting to GitHub webhooks

When all Taskcluster jobs for a commit on master finish, the build status on GitHub of that commit will be updated. Listening to this build status event will tell us the list of Taskcluster jobs, from which we can infer the URLs of artifacts, and then we can simply send the list of URLs to the receiver.

## Results merger in processor

The receiver in #142 already supports downloading and passing multiple files to the processor (cuz it's easy to implement). The MVP for the processor #146 , on the other hand, won't have the results merger in the first iteration, so this issue also covers that task.

**Comment by jugglinmike** [comment]
Elsewhere, @jgraham noted:

> I know that the TaskCluster team were talking about making it easier to write this kind of decision task for GitHub, but I think it is possible at present using the raw task-scheduling APIs (unless there's some unexpected permission problem)

James was writing specifically about skipping irrelevant tasks during pull request validation, but I believe this same pattern could be used to consolidate and upload results instead of an independent service.
