### ISSUE TITLE
Reftest analyzer should suggest fuzzy parameters for failing reftests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1490]
This came up at TPAC, requested by @frivoal.

@dbaron says that the Gecko reftest analyzer already does this, so this would be useful.

Promoting the information to the wpt.fyi checks or somewhere closer to the failure could also be a good idea.

**Comment by dbaron** [comment]
In Gecko it's not in the analyzer, it's [in the harness](https://searchfox.org/mozilla-central/rev/7ed8e2d3d1d7a1464ba42763a33fd2e60efcaedc/layout/tools/reftest/reftest.jsm#1209-1210).

**Comment by foolip** [comment]
I see. Does that mean you need to read the logs to find it, or is it extracted and surfaced somewhere?

Where would it make the most sense to surface it for wpt's CI?

**Comment by lukebjerring** [comment]
Related to https://github.com/web-platform-tests/wpt.fyi/issues/1228
