### ISSUE TITLE
Add support for arbitrary labeling of tests / results.

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#1491]
This represents part of the design for the wpt-metadata repository.
https://docs.google.com/document/d/1oWYVkc2ztANCGUxwNVTQHlWV32zq6Ifq9jkkbYNbSAg/edit#heading=h.mv91jownsl1e

- Add a format for appending labels to wpt-metadata META.yml files.
- Add UI for displaying the labels, and for appending new labels

**Comment by lukebjerring** [comment]
This relates to #1489, in that there are meta flags in the contents of test files that are a different way of denominating the part of a spec that a test applies to (not just the spec as a whole).

This feature is blocking a feature request from the CSSWG (surfacing the flags inside a test as labels of the tests that we can filter the results by). In theory, once we can label arbitrarily, we can also write a bot that scrapes the flags metadata inside a test file and updates the labels in wpt-metadata.

**Comment by KyleJu** [comment]
This feature has been implemented
