### ISSUE TITLE
Filtering by count inequality

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1496]
We support `none(status:pass)` and `count:1(status:pass)` queries, but for judging transition to REC it would be good to be filter by test that have 2 or more passes.

Proposal: `count>=2(status:pass)`.

@fantasai @frivoal @plinss @tabatkins

**Comment by lukebjerring** [comment]
FWIW the ugly way to do this right now is enumerate the possibilities, e.g. >=2 `!none(status:pass) !one(status:pass)`

And for larger numbers, e.g. >=3 `three(status:pass) or all(status:pass)` is shorter.

**Comment by foolip** [comment]
It'd be fine for this to be translated before it hits the API, but I'm guessing this isn't that hard to add all the way down? It's pretty likely that the CSSWG will want to interact with the API to produce reports at some point.
