### ISSUE TITLE
Show interop score in interop view

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt.fyi#150]
Here's a mockup I did today

<img width="1033" alt="screen shot 2018-05-15 at 14 12 33" src="https://user-images.githubusercontent.com/244772/40057224-f00c7dd2-584d-11e8-8696-8df2823db24d.png">

The "0 / 4" and "4 / 4" have a multiplier of 1, the "1 / 4" and "3 / 4" have a multiplier of 0.5, and "2 / 4" has a multiplier of 0, and those scores are then added together, setting the <progress>.value to something between 0 and 1. I made the colors of the columns represent these weights. The idea is that "2 / 4" is the worst case, interop-wise.

There could be other ways to calculate the score that may be better; after all 0/4 really means that the interop score is "unknown" since tests can fail for different reasons (but the feature under test is most probably not usable by web developers). An alternative way to calculate is N/M, i.e., "0 / 4" has a multiplier of 0, "1 / 4" has a multiplier of 0.25, etc.

Thoughts @lukebjerring @foolip @isaacdurazo @boazsender

**Comment by foolip** [comment]
Also cc @mdittmer.

Originally we didn't compute a score and went with purple across all columns to avoid deciding what we think is "good" or "bad". See [WPT Dashboard Interop Stats PRD (comment)](https://docs.google.com/document/d/1g22NuZ82RqPUYEOUzihc3quCuWqZ2NcearOGOIYlF20/edit?disco=AAAABhioaHU) for some of that background.

However, if we just accept that we want tests to pass, then it's straightforward to say that more browser passing is better. Until we have some semi-robust notion of coverage I'm still a bit hesitant about scores, but keen to hear what others think. It'd be interesting to see which directories would have the highest and lowest scores, to see if that matches our hunches about what's interoperable and not.

In https://github.com/web-platform-tests/wpt.fyi/issues/132 I suggested another UI change to make it easier to find problems.

**Comment by zcorpan** [comment]
<img width="1033" alt="screen shot 2018-05-15 at 15 45 05" src="https://user-images.githubusercontent.com/244772/40060493-0dd3c0e2-5857-11e8-9caf-104aa73bb569.png">

This has N/M scores.

**Comment by foolip** [comment]
I think that looks pretty nice. Apart from the score, is the only difference what the color is which is faded in/out for each column? Do the intensities still add up to 1?

**Comment by zcorpan** [comment]
May want to flip the text color to white on the most red cells, to aid readability (especially for people who are color blind).
