### ISSUE TITLE
Conjunction (`and`) with `none` query seems to not work

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1507]
On [this page](https://wpt.fyi/results/?diff&filter=ADC&q=none%28status%3Amissing%29%20and%20is%3Adifferent&run_id=320340002&run_id=322080003), the query is `none(status:missing) and is:different` but the `and` doesn't seem to work, all results are returned.

**Comment by foolip** [comment]
That that loading and reloading the page there seems to be something weird going on. I see "Failed to fetch test runs" consistently now, even when changing the query to something that I hadn't asked for before.

**Comment by lukebjerring** [comment]
I suspect this will be fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1500 which changes the root query(s) to be combined with an `and` conjunction.

**Comment by foolip** [comment]
I can confirm that `none(status:missing) and is:different` has a more plausible result with https://github.com/web-platform-tests/wpt.fyi/pull/1500.

**Comment by lukebjerring** [comment]
As mentioned in #1500, the query needs to be `none(status:missing) is:different` (which is the equivalent of `none(status:missing) exists(is:different)`. Explicitly writing `and` is interpreted incorrectly as a pattern (test name containing `and`)
