### ISSUE TITLE
Not possible to search for all(status:fail) and filter by path

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1513]
The `idlharness all(status:fail)` query on wpt.fyi and staging.wpt.fyi both point to a single test:
https://wpt.fyi/results/requestidlecallback/idlharness.window.html?label=master&label=experimental&aligned&q=idlharness%20all%28status%3Afail%29

This test doesn't have any consistent failures, so is not what I was looking for.

Is it not possible to combine the implicit path substring query with an `all` query?

I also tried `path:*idlharness*` hoping that being explicit would trigger another path in the parser, but we don't seem to support that.

**Comment by lukebjerring** [comment]
https://staging.wpt.fyi/results/?label=master&label=experimental&aligned&q=all%28idlharness%20status%3Afail%29

`all(idlharness status:fail)` does what you want (all queries inside a all root have to apply to all columns, and test names always apply to all columns). Not launched to prod yet.

Wildcards in path are not supported, just use the substring match of pattern (i.e. no prefix of path:)

**Comment by lukebjerring** [comment]
https://staging.wpt.fyi/results/?label=master&label=experimental&aligned&q=all%28status%3Afail%29%20idlharness

Weirdly I didn't try this first, but `all(status:fail) idlharness` also works (all fail and exists a result with idlharness in the test name). Was it the path wildcard part that was going wrong?

**Comment by foolip** [comment]
The only difference between `all(status:fail) idlharness` and the query I reported this against seems to be there order, right?

`all(idlharness status:fail)` is something I couldn't guess, because the `all` is about the columns, and the path filter is filtering the rows. At least visually.

**Comment by lukebjerring** [comment]
Ok, `idlharness all(status:fail)` (order matters)
I see what is going on here. By the time we hit idlharness, we're assumed to be inside an exists query wrapping the whole root. all(... is interpreted as a pattern, not as another root query.

Should be fixable!

**Comment by lukebjerring** [comment]
Will be fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1511 (in https://github.com/web-platform-tests/wpt.fyi/pull/1511/commits/25663a561ee0f23a68a31f7049ad98fb15310fb2)

**Comment by lukebjerring** [comment]
> the all is about the columns, and the path filter is filtering the rows. At least visually.

Only visually. In practice, all filtering is per-column; it just so happens that pattern atoms (and path atoms) get the same outcome for every single column (independent of the result), so it feels like row-level filtering.
