### ISSUE TITLE
Use alrra/browser-logos for browser logos

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1538]
Our Firefox logos need to need to be updated, and https://github.com/alrra/browser-logos/blob/master/src/README.md#firefox already has them.

It also has logos we could use for WebKitGTK and Epiphany:
https://github.com/alrra/browser-logos/blob/master/src/README.md#web
https://github.com/alrra/browser-logos/blob/master/src/README.md#webkit

**Comment by alrra** [comment]
@foolip Duplicate of: #1414? (see also: https://github.com/whatwg/whatwg.org/pull/265).

**Comment by foolip** [comment]
Yep, it's a dupe. Thanks!
