### ISSUE TITLE
Salvage chrome-experimental and firefox-experimental runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1540]
There are a bunch of Chrome and Firefox runs with -experimental in the product name, which this code tries (but fails) to deal with:
https://github.com/web-platform-tests/wpt.fyi/blob/4a1621ee74a070d320a7b855eb902fbe7b3704ec/webapp/components/display-logo.js#L121-L129

They can't be found via /runs or /api/runs, but here are two found via the Datastore admin UI:
https://wpt.fyi/results/?run_id=4697703762100224
https://wpt.fyi/results/?run_id=4739633715871744

It should be pretty simple to fix up the product name of these and add the appropriate labels. They don't have the master label, but that could be added for the subset which are for a commit with a merge_pr_* label.

Why? To allow removing that workaround, and make more runs available for historical trends.

**Comment by foolip** [comment]
@Hexcles with this like https://github.com/web-platform-tests/wpt.fyi/issues/1175 would it help if I produced a list of run IDs and what edits should be applied to them?

I ask mainly because some of these are probably also labeled incorrectly, so handling them before https://github.com/web-platform-tests/wpt.fyi/issues/1175 probably makes sense.

**Comment by Hexcles** [comment]
This has already been done: https://github.com/web-platform-tests/data-migration/blob/master/tagger/browser_name.go

However, the condition might have been a bit too strict (requiring the "stable" label) so it's possible that we missed a bunch.

**Comment by Hexcles** [comment]
If you have a list of run IDs, we can do fix them. There shouldn't be too many.

**Comment by foolip** [comment]
Why did it require the stable label? I'd expect all of these to be Firefox Nightly and Chrome Dev...

**Comment by Hexcles** [comment]
Sorry, I meant requiring the absence of the stable label, which is totally reasonable but there could be old runs that were mislabelled.

**Comment by foolip** [comment]
@stephenmcgruer since you've had fun with datastore recently, do you want to own this too?

**Comment by stephenmcgruer** [comment]
API links for the runs in the OP:

https://wpt.fyi/api/runs/4697703762100224
```
{"id":4697703762100224,"browser_name":"chrome-experimental","browser_version":"68.0.3440.7","os_name":"linux","os_version":"4.4","revision":"7a80bc95a6","full_revision_hash":"7a80bc95a6e56d527a426aa4440bc2bec2cf8169","results_url":"https://storage.googleapis.com/wptd/7a80bc95a6/chrome-experimental-linux-summary.json.gz","created_at":"2018-06-05T16:32:23.310676Z","time_start":"2018-06-05T16:32:23.310676Z","time_end":"0001-01-01T00:00:00Z","raw_results_url":"https://storage.googleapis.com/wptd-results/7a80bc95a6e56d527a426aa4440bc2bec2cf8169/chrome-experimental-68.0.3440.7-linux-4.4/report.json","labels":["experimental","chrome"]}
```

https://wpt.fyi/api/runs/4739633715871744
```
{"id":4739633715871744,"browser_name":"firefox-experimental","browser_version":"62.0a1","os_name":"linux","os_version":"4.4","revision":"7a80bc95a6","full_revision_hash":"7a80bc95a6e56d527a426aa4440bc2bec2cf8169","results_url":"https://storage.googleapis.com/wptd/7a80bc95a6/firefox-experimental-linux-summary.json.gz","created_at":"2018-06-05T14:50:23.650429Z","time_start":"2018-06-05T14:50:23.650429Z","time_end":"0001-01-01T00:00:00Z","raw_results_url":"https://storage.googleapis.com/wptd-results/7a80bc95a6e56d527a426aa4440bc2bec2cf8169/firefox-experimental-62.0a1-linux-4.4/report.json","labels":["experimental","firefox"]}
```

**Comment by stephenmcgruer** [comment]
Neither of those have the `stable` label, so unclear why `browser_name.go` missed them. Will start by exploring that.

**Comment by stephenmcgruer** [comment]
Oh, `browser_name.go` didn't actually rename them, it just added the `experimental` label to them.

**Comment by stephenmcgruer** [comment]
Random aside whilst poking around; found some Edge runs that don't have an 'edge' label on staging:

Processed TestRun /TestRun,5150881536278528 (edge 44.17763.1.0)
Processed TestRun /TestRun,5413113704742912 (edge 44.17763.1.0)
Processed TestRun /TestRun,5218364062433280 (edge 44.17763.1.0)
Processed TestRun /TestRun,4720568024694784 (edge 44.17763.1.0)
Processed TestRun /TestRun,4801737189752832 (edge 44.17763.1.0)
Processed TestRun /TestRun,5352350130634752 (edge 44.17763.1.0)
Processed TestRun /TestRun,5694182416973824 (edge 44.17763.1.0)

Instead they have 'edge_webdriver':

```{"id":5150881536278528,"browser_name":"edge","browser_version":"44.17763.1.0","os_name":"win","os_version":"10.0","revision":"4bc37b9ed1","full_revision_hash":"4bc37b9ed1a901ad1fe872f2eacef3c5a8a2f0c3","results_url":"https://storage.googleapis.com/wptd-staging/4bc37b9ed1a901ad1fe872f2eacef3c5a8a2f0c3/edge_webdriver-44.17763.1.0-win-10.0-12cb7400a1-summary.json.gz","created_at":"2019-02-24T00:20:15.572098Z","time_start":"2019-02-23T21:27:13.743Z","time_end":"2019-02-24T00:10:33.128Z","raw_results_url":"https://storage.googleapis.com/wptd-results-staging/4bc37b9ed1a901ad1fe872f2eacef3c5a8a2f0c3/edge_webdriver-44.17763.1.0-win-10.0-12cb7400a1/report.json","labels":["azure","edge_webdriver","master","stable","webdriver"]}```

There are some equivalent runs on prod, but they have both 'edge' and 'edge_webdriver' labels.

**Comment by Hexcles** [comment]
^ That was intentional. Historically, Edge was tested via Selenium (which would then use WebDriver underneath), and `edge_webdriver` was a separate product that directly used WebDriver. https://github.com/web-platform-tests/wpt/issues/15174#issuecomment-459311676

**Comment by stephenmcgruer** [comment]
Fixup complete. 402 prod runs renamed to not have '-experimental' in the "browser_name", 330 staging runs.

Example runs: 5759902660165632, 5637760434044928, 4739633715871744 (I have the full log files, they're just not on the machine I'm writing this comment from :D)

**Comment by stephenmcgruer** [comment]
[prod-rename-log.txt](https://github.com/web-platform-tests/wpt.fyi/files/3899004/prod-rename-log.txt)
[staging-rename-log.txt](https://github.com/web-platform-tests/wpt.fyi/files/3899005/staging-rename-log.txt)
