### ISSUE TITLE
Harness status "OK" should not be green

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1553]
It now looks like this, more obvious after https://github.com/web-platform-tests/wpt.fyi/pull/1527:
![image](https://user-images.githubusercontent.com/498917/67105354-e9d03380-f1c8-11e9-8fce-eb5e76353049.png)

This is a regression from https://github.com/web-platform-tests/wpt.fyi/issues/449 where this was first fixed.

**Comment by stephenmcgruer** [comment]
Where was this fixed? #499 was closed by a PR that only adds a border (https://github.com/web-platform-tests/wpt.fyi/pull/595/files), I don't see it changing the color away from green?

**Comment by foolip** [comment]
Yes, it was definitely gray for a long time after this was fixed the first time.

**Comment by stephenmcgruer** [comment]
Ok, was just not sure as #449 didnt seem to contain the change. Shouldnt be too hard to track down (he says).
