### ISSUE TITLE
Don't include "status check" in the name of the check suite

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1557]
### Check
https://github.com/web-platform-tests/wpt/pull/10571/checks?check_run_id=268068852 or any other check

### Description
The check suite is named "wpt.fyi status check" (or "staging.wpt.fyi status check") and especially the word "check" isn't useful to have there.

My suggestions would be just "wpt.fyi" or perhaps "wpt.fyi results".

**Comment by foolip** [comment]
This fix for this would be in https://github.com/organizations/web-platform-tests/settings/apps:
![image](https://user-images.githubusercontent.com/498917/68599400-ca16ed00-04a0-11ea-97e8-fbe3e3eff6bb.png)

@Hexcles @stephenmcgruer what name would you like?

**Comment by stephenmcgruer** [comment]
So the responsibilities for the task: add results to the datastore backing wpt.fyi, and report regressions?

Hard to summarize, I'd be happy with just 'wpt.fyi' to match 'Azure Pipelines'. But really I don't care that much :p

**Comment by foolip** [comment]
It actually isn't responsible for getting any results into wpt.fyi, the check just compares the results. On PRs it compares the results with and without the changes and also links to diffs to master, and on commits to master the check compares to the previous master run.

Just "wpt.fyi" would be fine I think. @Hexcles?

**Comment by stephenmcgruer** [comment]
![image](https://user-images.githubusercontent.com/153264/68602315-1d267b00-0474-11ea-91d8-e306fe22de95.png)

?

**Comment by foolip** [comment]
Yeah it says that but it’s not really the responsibility of the check, it would happen anyway and did work the same before the check existed.

It would be fine to make the check represent the results processor as well if there’s some utility to it. @Hexcles WDYT?

**Comment by Hexcles** [comment]
The name is in fact configured on GitHub settings. I've changed the names to remove "status check" for both installations.

I'll look into other feature requests separately. Some of them seem to be related to lifecycle.
