### ISSUE TITLE
/api/search should allow filtering by directory

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt.fyi#1592]
/api/search has the 'q' parameter, but that's a substring match. We (WebKit) often care about directories, so it would be nice to have a parameter that filters by directory prefix. I can do "/css/" but that still might find unwanted results.

**Comment by Hexcles** [comment]
We do support filtering by paths. In the front-end, this is quite easy: https://wpt.fyi/results/?label=master&label=experimental&aligned&q=path%3A%2Fcss%2F (note the structured query)

However, the query parsing happens on the front-end (JavaScript), so the API only takes a JSON request in the body. Here's the [full doc](https://github.com/web-platform-tests/wpt.fyi/blob/master/api/query/README.md). You could either read the JSON part of the doc and construct the JSON yourself, or read the query language part, type that in the frontend and capture the request payload using devtools.

By the way, what is the use case if you don't mind sharing? Are you trying to build another dashboard? Is there anything we could help to make wpt.fyi more useful for you?

**Comment by smfr** [comment]
Good to know, thanks. I'm just trying to pull down some data for Safari that I can use to track improvement over time, in a format that I can copy-paste into a spreadsheet (tab-delimited).

**Comment by foolip** [comment]
It looks like the "path" atom isn't documented in https://github.com/web-platform-tests/wpt.fyi/blob/main/api/query/README.md, I was going to file an issue when I came across this.

@KyleJu @tabatkins FYI that there is already this way to filter results by path, since there was talk about adding a way to do that.
