### ISSUE TITLE
Figure out (automatic) staging & prod deployment

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#161]
Currently, we deploy the `webapp` project automatically, using `util/deploy.sh`. This issue requires:

 - Generalizing (parameterizing) the deployment script, to apply to other projects (i.e. `results-processor`)
 - Updating the Travis CI client-secret.json.enc to have the needed permissions.

**Comment by lukebjerring** [comment]
I'm going to get started on the deploy script.

@mdittmer - you recently wrestled with permissions for a Flex environment. Can you update the secret?

**Comment by mdittmer** [comment]
I double checked the roles for the account that appears to be associated with Travis deployment. It should now have all the permissions it needs.

**Comment by lukebjerring** [comment]
After a large number of PRs (#183, #181, #179, #178, #171, #162, #159, #143, #122, #111, #83, ...), this behaviour is looking stable.

**Comment by Hexcles** [comment]
Apart from a rare race condition (#191 ), this issue seems to be fixed. Closing.
