### ISSUE TITLE
Install browser/webdriver deps and re-enable webdriver tests in Travis CI

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt.fyi#163]
#158 disables webdriver tests Travis CI. We need to figure out a straightforward way to ensure that all dependencies for browsers and webdriver are installed at a system level so that when npm installs them for testing they work as intended.

**Comment by mdittmer** [comment]
This line added to the make target `webdriver_deps` works, but I don't particularly like it:

```make
webdriver_deps:
	sudo apt-get install --assume-yes --no-install-suggests default-jdk wget xvfb $$(apt-cache depends firefox-esr chromedriver |  grep Depends | sed "s/.*ends:\ //" | tr '\n' ' ')
```

`default-jdk wget xvfb` are unstated dependencies for Selenium, npm's install scripts, and webdriver implementations (respectively). The subshell gets all the direct dependencies of `firefox-esr` and `chromedriver` so that they get installed before manual browser+driver installations are performed by the npm install scripts used in the same make target.

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/wpt.fyi/commit/6ee2352869c8df5c6ad620b9f25221c55526e7c5
