### ISSUE TITLE
WebDriver tests are slooooooooow

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt.fyi#165]
Would it make sense to run WebDriver tests on a nightly cron rather than on each PR?

Still-not-done Travis build summary (emphasis mine):

Build Jobs
 384.1
 Python
 WCT=1
 **18 min 6 sec**

 384.2
 Go
 MAKE_DEPS_TARGET=go_deps MAKE_TEST_TARGET=go_lint
 7 min 50 sec

 384.3
 Go
 MAKE_DEPS_TARGET=go_deps MAKE_TEST_TARGET=go_test
 7 min 42 sec

 384.4
 Go
 MAKE_DEPS_TARGET=go_deps MAKE_TEST_TARGET=go_webdriver_test
 9 min 57 sec

 384.5
 Go
 GITHUB_TOKEN=[secure] MAKE_DEPLOY_TARGET=webapp_deploy_staging
 6 min 36 sec

**Comment by lukebjerring** [comment]
Moving inside docker seems to drastically reduce the running time (not really sure why - could be that all that deps splitting we slaved over had a speed-up effect?? https://github.com/web-platform-tests/wpt.fyi/pull/167) 
e.g. https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/383291809 was 6m13s
