### ISSUE TITLE
Missing stable runs on wpt.fyi/runs

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt.fyi#1668]
https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

No stable runs have happened over the last 3 days - the latest ones are from Nov. 22

**Comment by stephenmcgruer** [comment]
The missing Chrome and Firefox runs could be https://github.com/web-platform-tests/wpt.fyi/issues/1660#issuecomment-557934912, I think, which kept going over the weekend until I fixed it Sunday night.

But why Safari is missing I'm not sure.

**Comment by stephenmcgruer** [comment]
... epochs is failing - https://github.com/web-platform-tests/wpt/commit/2a745bdf45e90e0edc04f71e096be69d724870d9/checks?check_suite_id=328010105

**Comment by stephenmcgruer** [comment]
```
### ERRORED 18:12:35Z

- Your workflow file was invalid: The pipeline is not valid. .github/workflows/epochs.yml (Line: 10, Col: 9): Unexpected symbol: '"web-platform-tests/wpt"'. Located at position 22 within expression: github.repository == "web-platform-tests/wpt"
```

**Comment by stephenmcgruer** [comment]
Strong suspect https://github.com/web-platform-tests/wpt/pull/20412 (@Hexcles )

**Comment by Hexcles** [comment]
> But why Safari is missing I'm not sure.

Safari runs on Azure, which is a GitHub Check. And the broken webhook is responsible for collecting the results.

**Comment by stephenmcgruer** [comment]
I note that https://github.com/web-platform-tests/wpt.fyi/commit/ec4eacb3de5768c72f47faac8aeda1097ea94b3e uses single quotes.

However lets start with putting out the fire; I'm going to revert web-platform-tests/wpt#20412

**Comment by stephenmcgruer** [comment]
Change of plan; we have a docker-related action with near-identical code but single quotes which works, so I'm going to push a change to use single quotes instead.

**Comment by stephenmcgruer** [comment]
Keeping open until we confirm we're good. I've kicked off another run of `epochs`, but I was a bit keen and may have raced my CL actually landing :D

**Comment by stephenmcgruer** [comment]
Most recent epochs action ran successfully - https://github.com/web-platform-tests/wpt/commit/29cfeaf1ea98a1d05378bfb735575e3e9dbbc72b/checks?check_suite_id=328293071

Continuing to hold open until we see stable runs coming back. I'm not 100% sure how to track the progress from the epochs branches to wpt.fyi (e.g. where the triggers are that lead from epoch branch --> run happening)

**Comment by stephenmcgruer** [comment]
We have stable runs.
