### ISSUE TITLE
Interop view summary numbers disagree with results view for same runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#168]
https://master-dot-wptdashboard.appspot.com/interop/shadow-dom/Document-prototype-currentScript.html:
![screenshot from 2018-05-22 13-44-51](https://user-images.githubusercontent.com/498917/40360488-a75e9d12-5dc6-11e8-88c3-084401cba5cd.png)

https://master-dot-wptdashboard.appspot.com/results/shadow-dom/Document-prototype-currentScript.html:
![screenshot from 2018-05-22 13-47-07](https://user-images.githubusercontent.com/498917/40360490-a963c808-5dc6-11e8-9250-daebae2b39f2.png)

These are the same versions. The numbers don't add up, only the harness status is a consistent failure.

@mdittmer

**Comment by lukebjerring** [comment]
Looks like @mdittmer will have a prerequisite on the overall test passing for a subtest pass to count?

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/results-analysis/blob/master/metrics/compute/compute.go#L24

**Comment by foolip** [comment]
Alright, so for harness errors we do something a bit different. I've added this issue to "Harness status untangling" to set it straight somehow. @mdittmer can you explain a bit how the harness status is taken into account here, and what you think we should do?

**Comment by lukebjerring** [comment]
Closing this issue and rolling it into #931 which will accomodate changes to interop scoring.
