### ISSUE TITLE
Support diffing of local results

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#169]
It would be handy to be able to see the differences between two wptreport JSON files which haven't been submitted to wpt.fyi yet. @kereliuk might be able to use this...

**Comment by Hexcles** [comment]
@lukebjerring asked me about this today.

So now that we have a staging project and the results receiver is ready, we can do ad-hoc diffing on the staging deployment. Though not entirely locally, it does the job.

Instructions:

1. Go to https://wptdashboard-staging.appspot.com/admin/results/upload
2. Choose an arbitrary "uploader" (e.g. your username).
3. Choose the **gzipped** wptreport you want to compare.
4. Fill in other necessary information if they are not present in the report. If not sure, just put in a dummy value. Take a note of the revision (SHA).
5. Wait for about half an hour until https://wptdashboard-staging.appspot.com/results/?sha=[10-digit-sha] becomes available.
6. You can now use the diff endpoint to compare the results you just uploaded to any existing results. (@lukebjerring could you briefly describe how to use the diff endpoint?)

**Comment by lukebjerring** [comment]
Example URL:
staging.wpt.fyi/results?before=chrome@latest&after=chrome@[10-digit-sha]

**Comment by foolip** [comment]
Very nice, thanks @Hexcles and @lukebjerring! @kereliuk, can you try it out?

**Comment by kereliuk** [comment]
Will give this a go later this morning!
