### ISSUE TITLE
Collect/Publish results from Servo

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt.fyi#1706]
Servo now has daily runs e.g. https://community-tc.services.mozilla.com/tasks/groups/ZeyukzlSSd6ATXzhw-Pmqw we should add servo to the frontend and populate it with that data.

**Comment by Hexcles** [comment]
Pretty sure this has been fixed: https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=servo&product=firefox&aligned

And yeah I like that logo ;)
