### ISSUE TITLE
Interop view tables don't have wide enough columns for numbers

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#173]
see e.g. https://wpt.fyi/interop/css/css-flexbox

Given we're using `table-layout: auto` (which we might not want to for perf reasons, given this is the O(n^2) table layout algorithm), adding `white-space: nowrap` to the headers is probably what we want. This would in this case make the table overflow the body even more than it currently does, though.

**Comment by zcorpan** [comment]
The whole page layout width could also be wider I think.

**Comment by lukebjerring** [comment]
Alleviated by #1139
