### ISSUE TITLE
Edge runs missing from wpt.fyi/runs, but not the API?

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt.fyi#1735]
https://wpt.fyi/runs?label=master&from=2020-01-03T00%3A00 shows no Edge runs since Jan 7th, but https://wpt.fyi/api/runs?product=edge&max-count=50 shows a bunch of Edge runs from the 8th - 10th.

This also seems to be affecting https://wpt.fyi/results/, which is showing Jan 7th for Chrome/Firefox/Safari, but Jan 10th for Edge (?!).

**Comment by stephenmcgruer** [comment]
Ah, this may not be a wpt.fyi bug... the epochs/3_hourly are all still running: https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&view=runs&branchFilter=9077

**Comment by stephenmcgruer** [comment]
I'm not sure I'm reading this right, but this build from 2.5 days ago seems to still be running, and seems to be making progress... so it's almost like the pipeline is just *really* backed up?

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39761&view=results

**Comment by stephenmcgruer** [comment]
cc @mustjab

**Comment by Hexcles** [comment]
Something seems wrong on Azure Pipelines? https://dev.azure.com/web-platform-tests/wpt/_build?view=runs is loading forever for me.

> but https://wpt.fyi/api/runs?product=edge&max-count=50 shows a bunch of Edge runs from the 8th - 10th.

Those runs are old SHAs (from a few days ago) that have only just completed.

**Comment by stephenmcgruer** [comment]
So if I add a branch filter, I can get https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&view=runs&branchFilter=9077 to load reasonably quickly. But yeah, without the filter it seems to be taking forever (3+ minutes)

**Comment by mustjab** [comment]
Looks like your scheduled job for re-creating Windows VMs failed to properly delete resource group with "ProvisioningState/failed/InternalExecutionError" error and left machines in bad state.

I've re-created the VMs and updated pipeline notifications to ensure that i get emails on failures so we can react quickly to future issues.

**Comment by Hexcles** [comment]
> Looks like your scheduled job for re-creating Windows VMs failed to properly delete resource group with "ProvisioningState/failed/InternalExecutionError" error and left machines in bad state.

I guess this was done by @foolip ? How do we fix this VM re-creation job?

**Comment by mustjab** [comment]
The runs are scheduled by me as we're the ones that provide these Windows VMs for the Edge runs. We have a scheduled job that re-creates VMs once a week and occasionally we run into infra issues with this job.

**Comment by mustjab** [comment]
Yes, i believe that machines are catching up now, which is why it's taking so long. 25 VMs is the default for the number of VMs that we've been using.

**Comment by stephenmcgruer** [comment]
https://wpt.fyi/runs now looks pretty good for Edge (except for d357cf2d59, which went mysteriously missing).

Tentatively closing since I don't think there is any other follow-up here; thanks for the fix mustjab@!
