### ISSUE TITLE
Turn down revision announcer

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1738]
Based on Cloud Monitoring, there is 0 request to this service in the past 6 months. Users have switched to the epoch branches of the wpt repo (maintained with [GitHub Actions](https://github.com/web-platform-tests/wpt/blob/master/.github/workflows/epochs.yml)). I think the time has come for us to turn this service down. Here is the plan

1. [x] Disable traffic serving of announcer
2. [x] Delete the announcer service from AppEngine, including its routing settings
3. [ ] Delete related code in this repo

I propose a somewhat arbitrary 1 week buffer time between each step.

cc @stephenmcgruer @foolip

**Comment by foolip** [comment]
Plan SGTM. I'm somewhat surprised there's no stray request though, can you confirm that if you make a request yourself it shows up in the logs?

**Comment by Hexcles** [comment]
Yes I did confirm that.

So if anyone looks at the logs for the past 6 months now, you'd see ~5 requests, all of which were made by me.
