### ISSUE TITLE
Migrate Go AppEngine to use cloud SDK and eventually to golang 1.12

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1747]
## Goal

Upgrade standard AppEngine Go runtime to 1.12+ early to avoid last-minute rush before deprecation as it's a relatively big refactoring.

It also has additional benefits:
* Greatly simplify our code base (unifying flex and standard runtimes)
* Open up access to more Cloud SDK (no longer need special AppEngine versions)
* Modernize our toolchain to benefit from new Go features and bring the prod environment closer to our default dev setup on workstations (which has the latest Go)

## Overview

The biggest blocker for upgrading to 1.12+ for us is:
> The Go 1.12+ runtimes do not provide access to proprietary App Engine APIs. You can use the Google Cloud client library or third party libraries to access Google Cloud services. You can find suggested alternatives to App Engine APIs in the Migrating from the App Engine Go SDK section.

as we've done the [rest](https://cloud.google.com/appengine/docs/standard/go/go-differences#changes_in_the_app_engine_go_112_runtime) when upgrading to Go 1.11.

Here's the full list of APIs for reference:
https://cloud.google.com/appengine/docs/standard/go/go-differences#migrating-appengine-sdk

Note that we will be able to migrate gradually, **in place** -- we can keep using the Go 1.11 runtime while switching individual APIs to the new Cloud SDK, since most of them are available in Go 1.11 as well:
https://cloud.google.com/appengine/docs/standard/go111/go-differences#migrating-appengine-sdk

## Breakdown

* [x] Clean up remaining urlfetch (tiny) 
* [x] AppEngine Modules API -> google-api-go-client (small)
* [x] TaskQueue -> Cloud Tasks (small)
* [x] AppEngine logging -> Cloud Logging (small) @KyleJu 
* [x] AppEngine Datastore -> Cloud Datastore (big, need to figure out standalone Datastore emulator) (refactoring by @KyleJu, switchover by @Hexcles )
* [x] AppEngine Context -> request.Context (small) @KyleJu 
* [x] AppEngine memcache -> Memorystore (medium)
* [x] AppEngine Users API -> GitHub OAuth login (big)
* [x] Remove AppEngine search (never turned on by default) (small)
* [ ] Local testing: `dev_appserver` -> `go run` (small)

**Comment by Hexcles** [comment]
Note that memcache is going away and we need to move to Memorystore.

**Comment by Hexcles** [comment]
Also an updated link for 1.12 specfically: https://cloud.google.com/appengine/docs/standard/go/go-differences#migrating-appengine-sdk

**Comment by KyleJu** [comment]
@Hexcles I will take the `AppEngine Context -> request.Context (small)` as well
