### ISSUE TITLE
Add the ability to filter out all metadata (or all of one type of metadata)

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt.fyi#1760]
Right now one can specify specific `link:` atoms to try and filter out tests that have been triaged (except note https://github.com/web-platform-tests/wpt.fyi/issues/1757). But there is no way to say 'only show me tests that do not have any metadata associated with them' (aka 'have not been triaged'); one needs to know the complete set of `links` used in all of `wpt-metadata` and list them all.

It would be very useful for triaging to have a simple way to exclude all tests that have already been triaged (aka have any sort of metadata on a _given browser). The browser part is needed in case there is already irrelevant metadata for another browser.

Maybe: `!triaged(chrome)` ?

**Comment by Hexcles** [comment]
A thought: if we generalize the use of wildcards (`*`), we could say `none(link:*)`.

**Comment by stephenmcgruer** [comment]
Not clear how that matches against the product? Is the idea that you would have to filter the view to see Chrome only, and then search like:

`none(link:*) and chrome:!pass and chrome:!missing and safari:pass and firefox:pass`

? Seems fragile, if adding products in will add matching tests.

**Comment by Hexcles** [comment]
I guess I did not fully understand the use case.

Are you trying to find all the untriaged failures for a browser? If so, you could set to only one product and use `none(link:*) status:fail`.

**Comment by stephenmcgruer** [comment]
Untriaged browser-specific failures. As per https://github.com/web-platform-tests/wpt.fyi/issues/1760#issuecomment-580386581, it would work to set to only one product and run `none(link:*) and chrome:!pass and chrome:!missing and safari:pass and firefox:pass` (I think), but it just seems awkward having to remember to restrict the view manually in the UI for the search to do what one expects :/

**Comment by KyleJu** [comment]
none(link:bugs.chromium.org) and chrome:!pass and chrome:!missing and safari:pass and firefox:pass is the closest query that achieves the objective, although it will miss all the chrome bugs that are filed to elsewhere (e.g. GitHub issues)
