### ISSUE TITLE
Update the manifest parsing code to accommodate the new trie format

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1777]
Following https://github.com/web-platform-tests/wpt/pull/16537 , we need to adjust our manifest-related code to accommodate the new, fundamentally different format.

Fortunately, all features that rely on `/api/manifest` are off by default. And even for the users who opted in, the failure mode is expected to be graceful.

**Comment by stephenmcgruer** [comment]
Can we prioritize fixing this? It's failing every PR sent to wpt-metadata (due to https://github.com/web-platform-tests/wpt-metadata/issues/80), which means we can't be confident that the metadata folks (well, mostly me) are adding is correct.
