### ISSUE TITLE
Duration row is missing when search query is not empty

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1786]
https://wpt.fyi/results/fetch/content-type/script.window.html?q=chrome%3Apass%20edge%3Apass%20firefox%3Apass%20safari%3Amissing&run_id=399630006&run_id=433960002&run_id=419090001&run_id=413260002 looks like this:

![image](https://user-images.githubusercontent.com/498917/73960054-851d1e00-490a-11ea-9c81-f403a97a08d8.png)

"Loading JSON…" is a subtest and shouldn't be grouped together with the harness status.

**Comment by Hexcles** [comment]
That should be the duration row.

**Comment by foolip** [comment]
Thanks @Hexcles!
