### ISSUE TITLE
Webhooks fail to send results to the receiver

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1830]
**Current status:** this is currently broken on master and staging, but hadn't been discovered. Prod was broken for a short while following today's deployment #1825 , but was shortly reverted -- in other words, prod is currently not affected.

**Discovery:** staging hasn't been receiving any new runs since around Feb 24th, but we don't monitor staging. The bug surfaced when today, a week since Feb 24th, [a WebDriver test](https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/293165433#L2879) that checks https://staging.wpt.fyi/runs started to fail on CI. Because of the lack of new runs, the recent runs page has become empty (by default we show recent runs in the past week). This bug would have been discovered in another way tomorrow by our rotation as the prod no longer stops receiving new runs for a day.

With bisecting, I was able to confirm the culprit change was https://github.com/web-platform-tests/wpt.fyi/commit/9831b916d1edbf5baab7e021398867a554b93ac4 . After this change, the results receiver started to receive empty payload from webhooks, confirmed by checking server logs from the `/api/results/upload` endpoint.

**Comment by LukeZielinski** [comment]
Sounds like unit tests were inadequate for this, right. Is there something we could have monitored to catch it more pro-actively?

**Comment by stephenmcgruer** [comment]
I mean, I'm looking forward to the postmortem ;). (Postmortems don't have to be long or for dramatic outages, they're useful ways to learn even from small problems!)
