### ISSUE TITLE
Chromium browsers should be executed with the touch-events=enabled flag

### ISSUE THREAD

**Issue by dtapuska** [web-platform-tests/wpt.fyi#1858]
To simulate the same way the content_shell executes the tests (which chromium uses for its waterfall) we should force touch events to be enabled by default.

To do this append "--touch-events=enabled" to the command line.

Doing so should fix the following tests:
https://wpt.fyi/results/touch-events/touch-globaleventhandler-interface.html?label=experimental&label=master&aligned

See:
https://source.chromium.org/chromium/chromium/src/+/master:content/shell/app/shell_main_delegate.cc;l=222;drc=f58a7942aec3f8ba5ad6e29f609ce109534d0b2e;bpv=1;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F

@NavidZ @Hexcles

**Comment by Hexcles** [comment]
Could you provide perhaps a bit more context?

Looking at the definition, does it override touch screen detection and enable touch events even on a Linux desktop without touch? If so, are there potential side effects?

**Comment by NavidZ** [comment]
@Hexcles The touch handlers should be enabled regardless of whether the device supports touch or not. All the codes out there that rely on that are not doing the right thing. To detect whether device supports touch or not js should rely on navigator.maxTouchPoint. Having said that obviously we don't want to break the web overnight.

@dtapuska but just enabling the flag for the test purposes seems like hiding the underlying problem that the event handlers should be enabled all the time regardless of the platform.

**Comment by dtapuska** [comment]
@mustaqahmed Mustaq handled this before. I forget the behavior here. But I thought for web compat the event handlers were only defined when it was a touch device.

**Comment by mustaqahmed** [comment]
There is no clean answer unfortunately.  Currently touch-screen availability matters only with "--touch-events=auto".  Without any command line override, we have global event handlers on [Android only](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/renderer_host/render_view_host_impl.cc;drc=22cc3d7f37662b424335f189d8cd9b2df786fdc9;l=652).

From spec perspective, this is broken so I would also prefer having failing tests (since the test here reflect the spec).

**Comment by Hexcles** [comment]
> From spec perspective, this is broken so I would also prefer having failing tests (since the test here reflect the spec).

Based on my understanding so far, I agree.

In general, we would like the test results to reflect the reality, especially on the stable channel. For the dev/nightly/canary channel, we turn on some experimental features to reflect the likely future. (A category of exception is flags that enable special permissions or mock devices to allow test execution.) I'm going to close this issue as wontfix for now, but please feel free to reopen if you disagree, or in the future if we start to experiment enabling touch events unconditionally on desktop.
