### ISSUE TITLE
[Triage Metadata] provide a fallback email for people without a public email

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#1863]
Not all GitHub users have a public email address. We need to use a fallback email address in such case, as the author email is a mandatory field.

I think we can just use a fake email address, like `noreply@web-platform-tests.org`. This should be safe as we only allow folks from the WPT org to triage. The only downside is that the commit will not be associated with the user. Maybe we can tag the user's GitHub handle in the commit message.

**Comment by gsnedders** [comment]
We could just use GitHub's fake email addresses? c.f. https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by Hexcles** [comment]
I'm seeing this quite a lot and it's an easy fix so I'll just do it :)

**Comment by KyleJu** [comment]
Thanks for the fix!
