### ISSUE TITLE
Make it easier to see which failures have been triaged

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1899]
Currently, no bug links are shown by default, but enabling "Show metadata Information on the wpt.fyi result page." in /flags shows a list at the end.

In a directory like [css/css-images/](https://wpt.fyi/results/css/css-images?label=master&label=experimental&aligned) it's not very easy to figure out which failures have already been triaged. I ended up triaging one test that I didn't know was already triaged in https://github.com/web-platform-tests/wpt-metadata/pull/160.

The UX of this might be tricky, it will easily become cluttered, but something like a bug icon next to the test name or in the individual cells would make it easier to tell what's wrong. Maybe the space that this occupies could also become the thing you click to link new information.

**Comment by KyleJu** [comment]
This requires changes in the UI side and the server side. 

On the server, every time a user triages a test,  the metadata cache in webapp should be updated to reflect the up-to-date metadata information.

On the UI side, we plan to display triaged metadata next to passing/total numbers inside of cells in a directory, similar to reftest screenshot icons:
<img width="920" alt="Screen Shot 2020-05-01 at 12 30 21 PM" src="https://user-images.githubusercontent.com/8611520/80822033-da826780-8ba7-11ea-9e4f-14d7e3cbdf4e.png">
In the subtest view, the metadata triage information will be shown through a row, like the row `harness status`

**Comment by KyleJu** [comment]
The propose change on the server side has been implemented through a [force cached update](https://github.com/web-platform-tests/wpt.fyi/blob/master/api/metadata_cache.go#L29)
