### ISSUE TITLE
Prepare to switch to results-receiver in prod

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#192]
#146 is only one step away (calling the test run creation API) and will be done soon, so it's time to prepare for production switchover. With @lukebjerring 's recent effort of setting up a completely isolated staging project, the process is actually quite simple:

0. Deploy results-receiver to both the staging and prod projects. In each project, the receiver stores results to the main GCS bucket and Datastore respectively.
1. Generate and distribute tokens (also decide usernames) for runners.
2. Ask runners to send the full reports to the **staging** deployment of the new API **in addition to** the existing procedure.
3. Verify everything works.
4. Runners send results to **prod** API and **in the meantime** stop using the legacy upload process.

**Comment by lukebjerring** [comment]
@mikewest - to clarify, this will mean that we are hoping you can upload the results twice (keeping the current behaviour, but also uploading the full report to staging.wpt.fyi).

We feel (strongly) that this makes more sense than trying to replicate existing client behaviour server-side and switching your client to staging-only uploads.

**Comment by Hexcles** [comment]
Sorry, wrong Mike. It's @jugglinmike .

**Comment by Hexcles** [comment]
All done :)
