### ISSUE TITLE
Anomalies view is an unusable UI

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#195]
See
https://wpt.fyi/interop/anomalies
https://wpt.fyi/interop/anomalies?browser=chrome

Views are producing an enormous, un-grouped and non-collapsed list.

This issue should cover design and implementation of a more usable UX.

**Comment by Hexcles** [comment]
@lukebjerring with the new search API & the insights page, shall we just get rid of the anomalies view?

**Comment by lukebjerring** [comment]
Yep. @mdittmer could you clean up the `FailureRateMetadata` (or whatever it was called) and related code?
