### ISSUE TITLE
"Harness status" is shown for reftests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1958]
This conditional is supposed to show "Test status" for reftests:

https://github.com/web-platform-tests/wpt.fyi/blob/0f000bc65bca1724dc453c63f6b20ff64fd7d5f7/webapp/components/test-file-results.js#L282

I'm sure that once worked, but it has since regressed. https://wpt.fyi/results/css/css-ui/appearance-auto-001.html now looks like this:
![image](https://user-images.githubusercontent.com/498917/81953434-f22a0900-9607-11ea-9869-26b275b67727.png)

Possibly the addition of duration is what broke this, if it's represented as a fake subtest or something.

**Comment by foolip** [comment]
I noticed this again just now, because "Harness status" is incorrectly used as the subtest name when triaging:
https://github.com/web-platform-tests/wpt-metadata/pull/609/files?diff=split&w=1

@Hexcles @KyleJu

**Comment by foolip** [comment]
I manually cleaned that up in https://github.com/web-platform-tests/wpt-metadata/pull/610, and confirmed there aren't any other instances of "Harness status" already in wpt-metadata.

**Comment by DanielRyanSmith** [comment]
Has was fixed a while ago, and is currently not a problem in production 👍
