### ISSUE TITLE
Use HTTP instead of HTTPS to link to non-HTTPS tests

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#2]
_From @gsnedders on April 4, 2018 18:15_

Only tests which are .https. (and have whatever set in the MANIFEST) should end up with the links to them being to https://w3c-test.org/ instead of http://w3c-test.org/

_Copied from original issue: w3c/wptdashboard#532_

**Comment by jugglinmike** [comment]
This was resolved by @zcorpan via https://github.com/web-platform-tests/wpt.fyi/pull/67
