### ISSUE TITLE
Chrome flakiness in the insight tab crashing in prod

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2006]
Reproduce [here](https://wpt.fyi/results/css?label=master&label=experimental&max-count=10&product=chrome&q=seq%28%28status%3APASS%7Cstatus%3AOK%29%20%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29%29%20seq%28%28status%3A%21PASS%26status%3A%21OK%26status%3A%21unknown%29%20%28status%3APASS%7Cstatus%3AOK%29%29)

Error message:
Uncaught TypeError: Cannot read property 'browser_name' of undefined
    at HTMLElement.getMetadataUrl (wpt-results.js:1051)

**Comment by KyleJu** [comment]
Failing on index-out-of-bound. In `this.products[index].browser_name`, it expects this.products is an array of size 10 because the search atoms compare the recent 10 chrome runs

**Comment by KyleJu** [comment]
@Hexcles perhaps we can turn off the `Show metadata Information on the wpt.fyi result page.` flag by default for now until a fix comes in

**Comment by stephenmcgruer** [comment]
I have turned this off in the admin flags for wpt.fyi (it was already off for staging.wpt.fyi). Checking in an incognito window implies that it has worked.

**Comment by KyleJu** [comment]
Same issue as https://github.com/web-platform-tests/wpt.fyi/issues/1896

**Comment by KyleJu** [comment]
This issue should be fixed in the next wpt.fyi release.

**Comment by KyleJu** [comment]
#2031. In prod
