### ISSUE TITLE
Differing dates of runs become confusing when showing complete runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#204]
After https://github.com/web-platform-tests/wpt.fyi/pull/72, https://staging.wpt.fyi/results/ shows the same commit for each run, but different dates.

Using the commit date of the commit shown would probably be most useful at this point. Being able to hover it and see the exact time would also be neat.

**Comment by lukebjerring** [comment]
TBH I disagree about it being confusing. When the SHA landed isn't as useful as when the run occurred.

**Comment by foolip** [comment]
Alright, I would not be offended if the issue is closed as "won't fix in the way you want" :)

**Comment by lukebjerring** [comment]
Closing as won't fix / WAI.
