### ISSUE TITLE
[UI] Metadata bug icon sometimes has broken link

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt.fyi#2058]
Reproduction: Take a look at the bug link for font-language-override-02.html on https://staging.wpt.fyi/results/css/css-fonts?label=master&label=experimental&product=chrome%5Btaskcluster%5D&product=firefox%5Btaskcluster%5D&product=safari%5Bazure%5D&aligned&q=triaged%3Achrome%20count%3A2%28status%3Apass%29%20none%28status%3Amissing%7Cstatus%3Anotrun%29%20firefox%3Apass%20safari%3Apass

It goes to https://staging.wpt.fyi/results/css/crbug.com/481430 , because the underlying metadata is probably `crbug.com/418430` (no http or https). 

Possibly we should only linkify the icons if they go to things that look like URLs?

**Comment by Hexcles** [comment]
The field is called "url", right? If so then they should all be URLs and maybe we should prepend `http://`.

**Comment by KyleJu** [comment]
> `http://`.

I don't see a Metadata URL starting with `http://`. I would prefer prepending `https://` just because users will feel safer clicking on it?
