### ISSUE TITLE
GitHub checks outdated - not running on the latest commit

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2067]
GitHub checks are outdated. Continuous Integration / web_components_test (pull_request) failed in https://github.com/web-platform-tests/wpt.fyi/pull/2066 due to `PathInfo.getDirname`, which is fixed in the latest commit.

**Comment by Hexcles** [comment]
I've seen that once or twice. Usually closing and reopening the PR fixes the problem. This is most likely a transient issue in GitHub.
