### ISSUE TITLE
Guide users through the triage flow using toasts

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#2085]
@wanderview

> it might also be nice to have some text under the table that says "select cells to add bugs" or in the future "select cells to add or file bugs for failure"

**Comment by stephenmcgruer** [comment]
Tooltips may not be the way to go, if the goal is discoverability of the feature. If the user never knows to put their mouse over a cell, they won't get any tooltip either. Perhaps just making the bottom-left pop-up permanent (when in triage mode) with some text like "Select some cells to [Triage]", and then the triage button is greyed out until some cell is selected?

**Comment by Hexcles** [comment]
Oh sorry I meant toasts; pop-ups are also a good idea.
