### ISSUE TITLE
Surface test type in the UI

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#211]
Related to #56

After surfacing all tests in the manifest, the UI is left with some 'holes' for `manual` tests. This issue covers revision of the UI to better reflect what was and was not run, as well as what the test types are (e.g. `reftest`, `manual`, etc)

**Comment by lukebjerring** [comment]
@foolip said:

> Mockup for directory with no tests run, accname here:
> ![screenshot from 2018-05-31 15-24-09](https://user-images.githubusercontent.com/498917/40784736-c89c6e9c-64e6-11e8-9808-3a42eb3739fa.png)

> For the denominator, the choice will be to either include unrun tests or not. Thinking about it, I think we probably should. So accname should ideally say "0 / 80" or something.

**Comment by lukebjerring** [comment]
@foolip - I'm thinking some tiny unicode or icons for the test types. Any knowledge of existing icons?

**Comment by foolip** [comment]
If you just want an icon for manual tests and nothing to distinguish the other 3 types, then something with a hand might work. But I can't find a suitable unicode hand.

**Comment by lukebjerring** [comment]
https://material.io/tools/icons/?icon=touch_app&style=baseline ?

**Comment by foolip** [comment]
Yes, that's great! https://material.io/tools/icons/?icon=rowing&style=baseline would be very funny, but I don't get why that icon even exists :)

**Comment by lukebjerring** [comment]
This is done, and can optionally be enabled in `/flags`.
