### ISSUE TITLE
Any GitHub user (without being in the org) can triage metadata

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#2157]
https://github.com/web-platform-tests/wpt.fyi/blob/35b4e74dc5625de763ffb25a27468fff649d92bd/shared/github_oauth.go#L157-L164

Here we are passing an empty string for `user` to `GetOrgMembership`, which means we are checking the org membership of the authenticated user (of `gaci`), which is our bot.

**Comment by KyleJu** [comment]
Fixed in #2160
