### ISSUE TITLE
Bug links not shown for WebKitGTK

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2216]
We have a fair bit of WebKitGTK failures triaged, for example [for Flexbox](https://github.com/web-platform-tests/wpt-metadata/blob/88bf5e27790a03429424de2f6cd7fee98173d3bc/css/css-flexbox/META.yml).

However, these aren't shown linked on wpt.fyi:
https://wpt.fyi/results/css/css-flexbox?label=master&label=experimental&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk&aligned&q=triaged%3Awebkitgtk

Screenshot:
![image](https://user-images.githubusercontent.com/498917/96965459-7c0dc480-150c-11eb-8441-a4bb41c78e0e.png)

As you can see, the Safari column has a lot of bug icons, but not WebKitGTK. As a concrete example, anonymous-flex-item-005.html definitely has the data:
https://github.com/web-platform-tests/wpt-metadata/blob/88bf5e27790a03429424de2f6cd7fee98173d3bc/css/css-flexbox/META.yml#L191-L197

**Comment by KyleJu** [comment]
The issue lies at [this line](https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/components/wpt-metadata.js#L204). WebKitGTK and Safari share the same bug URL and is being skipped when checking duplicated links there.

**Comment by KyleJu** [comment]
Note that multiple metadata entries can share the same link, not limited to Safari and WebKitGTK; see https://github.com/web-platform-tests/wpt-metadata/pull/594/files
