### ISSUE TITLE
Occasional "transport is closing" error when scheduling Cloud Tasks

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#2224]
`Failed to schedule task: rpc error: code = Unavailable desc = transport is closing`

I created a new alert for 5xx errors from `/api/results/upload`, which brought my attention to this error. It happens occasionally (a couple of times per week). It's not clear whether it was caused by #2153 (we might have missed it before due to the lack of the alert), but we should have some retry mechanism for this critical API nonetheless.

Tentatively low-prio due to the low frequency

**Comment by stephenmcgruer** [comment]
What is this impact of this bug - do we drop test results?

**Comment by Hexcles** [comment]
Yes, and that's bad, but with a low chance of happening, and the vast majority of API calls being PR results, the expectation for losing a full run is low.

* At least that's what I was going to say... Looking at the logs more closely, I realized I got the filtering wrong and it actually happens ~once per day, which is a lot more concerning. Continue looking...
