### ISSUE TITLE
/api/results is undocumented

### ISSUE THREAD

**Issue by tabatkins** [web-platform-tests/wpt.fyi#224]
The `/api/README` explains which endpoints are available, but it (a) has incorrect parameters in several places (it claims `browser` in several places, but actually wants `product`), and (b) gives zero explanation as to what the returned JSON's structure will be.

For example, `/api/results?product=chrome` returns an object with entries like `"/css/css-text/i18n/css3-text-line-break-opclns-213.html": [1, 1]`. I have no idea what that array means!

I also don't see a way to get a list of products, so I don't know how to query the results per product. Is that information contained in one of the other endpoints' data?

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt.fyi/blob/master/api/README.md is quite extensive now, but /api/results is till undocumented. Leaving issue open for that.

**Comment by lukebjerring** [comment]
There is (now) a basic description, so closing this.
