### ISSUE TITLE
[Memcache] Error from memcache.Set in a cache miss: memcache: server error

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2240]
Since 2020-11-02 12:27:33.437 EST, GCP Logging has started showing `Error from memcache.Set in a cache miss: memcache: server error` for almost all `/api/metadata?products=chrome%2Cedge%2Cfirefox%2Csafari` requests in prod.

See [logging](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22gae_app%22%20resource.labels.module_id%3D%22default%22%20resource.labels.version_id%3D%22rev-8da41d2%22%0AprotoPayload.resource%3D%22%2Fapi%2Fmetadata%3Fproducts%3Dchrome%252Cedge%252Cfirefox%252Csafari%22;timeRange=P7D?serviceId=default&project=wptdashboard) for more information

**Comment by KyleJu** [comment]
This issue doesn't seem to be caused by our side since no changes to memcache were introduced around that time. I will circle back tomorrow to see if it persists

**Comment by Hexcles** [comment]
Yeah this error existed before but we didn't log it. The (gzipped) metadata has exceeded the maximum memcache item size (1MB): https://cloud.google.com/appengine/docs/standard/python/memcache#limits

There's no such limit in the new Redis-based Memorystore. In other words, this issue will be fixed automatically when we switch over to Memorystore.
