### ISSUE TITLE
Show something when searching doesn't match anything

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#225]
I opened https://wpt.fyi/results/ and started typing "ishistory" in the search box before it was loaded. I was left with a just the header, not sure if it was because the results didn't load correctly, or if it was because the search didn't match anything. "No results" or something similar when the search doesn't have any matches would be great.

**Comment by lukebjerring** [comment]
So, we actually do show something now.. but it's 

> Failed to fetch test runs.

If the request succeeds, and `testRuns` are found, it would be good to show a `No results found` message instead.
