### ISSUE TITLE
[Go 1.12] Local build broken due to #2252

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2259]
Running `./util/docker-dev/dev_data.sh` returns:

2020/11/18 22:40:47 populate_dev_data.go:54: Adding dev data to local emulator...
2020/11/18 22:40:47 populate_dev_data.go:145: Adding local (empty) secrets...
2020/11/18 22:40:47 appengine.go:102: Closing clients
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x98552c]

goroutine 1 [running]:
cloud.google.com/go/datastore.(*Client).PutMulti(0x0, 0xd53dc0, 0xc0000bc010, 0xc000295120, 0x1, 0x1, 0xaeab20, 0xc0003f6520, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/cloud.google.com/go/datastore@v1.3.0/datastore.go:516 +0x17c
cloud.google.com/go/datastore.(*Client).Put(0x0, 0xd53dc0, 0xc0000bc010, 0xc0003b7fc0, 0xace420, 0xc0003bd5a0, 0x0, 0x0, 0x42d271)
	/home/user/go/pkg/mod/cloud.google.com/go/datastore@v1.3.0/datastore.go:490 +0xe8
github.com/web-platform-tests/wpt.fyi/shared.cloudDatastore.Put(0xd53dc0, 0xc0000bc010, 0x0, 0xd4f6c0, 0xc0003b7fc0, 0xace420, 0xc0003bd5a0, 0xc000295208, 0xa69b1c, 0xbdfdc0, ...)
	/home/user/wpt.fyi/shared/datastore_cloud.go:152 +0x14e
main.addSecretToken(0xd5f1e0, 0xc0003f6500, 0xc52a67, 0xc, 0xace420, 0xc0003bd5a0)
	/home/user/wpt.fyi/util/populate_dev_data.go:324 +0xc0
main.main()
	/home/user/wpt.fyi/util/populate_dev_data.go:147 +0x1109
exit status 2
make: *** [dev_data] Error 1
Makefile:236: recipe for target 'dev_data' failed

This is caused by `datastore: missing project/dataset id` in [appengine.go](https://github.com/web-platform-tests/wpt.fyi/blob/master/shared/appengine.go#L49).

**Comment by KyleJu** [comment]
I think `datastoreHost` and `project` in  need to be set in `populate_dev_data.go`

**Comment by KyleJu** [comment]
In addition, when running `./util/docker-dev/web_server.sh`, I am seeing error messages:

goroutine 1 [running]:
main.main()
	/home/user/wpt.fyi/webapp/web/main.go:33 +0xe2
ERROR    2020-11-18 22:20:54,201 instance.py:284] Cannot connect to the instance on localhost:19939
ERROR    2020-11-18 22:20:54,525 instance.py:284] Cannot connect to the instance on localhost:20760
ERROR    2020-11-18 22:20:54,846 instance.py:284] Cannot connect to the instance on localhost:20721
2020/11/18 22:20:56 Closing clients
panic: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

goroutine 1 [running]:
main.main()
	/home/user/wpt.fyi/webapp/web/main.go:33 +0xe2
2020/11/18 22:20:57 Closing clients
panic: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by KyleJu** [comment]
> In addition, when running `./util/docker-dev/web_server.sh`, I am seeing error messages:
> 
> goroutine 1 [running]:
> main.main()
> /home/user/wpt.fyi/webapp/web/main.go:33 +0xe2
> ERROR 2020-11-18 22:20:54,201 instance.py:284] Cannot connect to the instance on localhost:19939
> ERROR 2020-11-18 22:20:54,525 instance.py:284] Cannot connect to the instance on localhost:20760
> ERROR 2020-11-18 22:20:54,846 instance.py:284] Cannot connect to the instance on localhost:20721
> 2020/11/18 22:20:56 Closing clients
> panic: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
> 
> goroutine 1 [running]:
> main.main()
> /home/user/wpt.fyi/webapp/web/main.go:33 +0xe2
> 2020/11/18 22:20:57 Closing clients
> panic: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

I am suspecting that this is somewhat related to the use of random datastore emulator ports in  #2252

**Comment by Hexcles** [comment]
Sorry about that; sent you a quick fix.
