### ISSUE TITLE
Change the default branch to "main"

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#2280]
https://tools.ietf.org/id/draft-knodel-terminology-02.html

I'm going to do this now that we have relatively few PRs open.

Note: this issue is about the repo of wpt.fyi itself.

**Comment by Hexcles** [comment]
Locally, I've done
```bash
git branch -c master main
git checkout main
git push -u origin main
```
which gives us https://github.com/web-platform-tests/wpt.fyi/tree/main

**Comment by Hexcles** [comment]
Fixed up everything I can find in the code: https://github.com/web-platform-tests/wpt.fyi/commit/f8d9beebe98a4d254d1ae0d0283c4fe7cef3196e

**Comment by Hexcles** [comment]
Looks like both GitHub Actions and Travis went well: https://github.com/web-platform-tests/wpt.fyi/runs/1460905946

I've changed the default branch to "main" but will keep the "master" around for a short while. The previous branch rule for master has been modified to apply to main. I also added a new branch rule to master to prevent push except from admins.

@web-platform-tests/wpt-fyi please run the following command locally. Thanks!
```bash
git branch -m master main
git checkout main
git fetch origin
git branch -u origin/main
```

**Comment by Hexcles** [comment]
Updated the base branch of all open PRs.

I'm closing this issue now. Feel free to reopen if you encounter any issue.

**Comment by Hexcles** [comment]
Update: the `master` branch has been deleted. All existing URLs (or git refs) to the `master` branch should be automatically redirected to the new `main` branch by GitHub.

**Comment by foolip** [comment]
I can confirm the redirects work in the most common case:
https://github.com/web-platform-tests/wpt.fyi/blob/master/CODE_OF_CONDUCT.md

It doesn't work in all cases though:
https://github.com/web-platform-tests/wpt.fyi/commits/master

**Comment by Hexcles** [comment]
> https://github.com/web-platform-tests/wpt.fyi/commits/master

Do we have this link somewhere?

**Comment by foolip** [comment]
Not that I know of, I just tested two kinds of URLs I often end up at. I suspect some specs link to URLs like this for "recent changes" but that's not relevant for wpt.fyi.
