### ISSUE TITLE
Build & dependency management for protos

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#23]
_From @mdittmer on October 23, 2017 14:59_

Consistency between Python, Go, Big Query, [[insert next technology we use]] will be eased by using protos to define data format. It will also make our data formats more explicit. @jeffcarp mentioned to me that he intended to do this anyway, but hasn't gotten around to it yet.

I have done some initial investigations into this, and managed to get Python code generation and Big Query schema generation working. At the moment, managing the tools and libraries is being done manually on my machine. So far, I need:

- The [protocol buffer compiler](https://github.com/google/protobuf/releases) (protoc) version V = 3.x
- The [protocol buffer big query schema generator](https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema) (a protoc plugin)
- The [protocol buffer libraries](https://github.com/google/protobuf) Checked out to branch corresponding to V

To build the code I have so far, I have to invoke `protoc` twice (passing it arguments that fer to the other two dependencies).

@foolip @jeffcarp any thoughts on how these dependencies should be managed? Ideally we would choose something that is (1) simple & small, and (2) not tied to a specific language or platform.

Under my current branch, we would also need to choose a means of ensuring that "the build" runs before `run.py` (and probably other scripts) run, to ensure that generated code is up-to-date. Perhaps we can have a single script/file for each language (shell, Python, etc.) that should be invoked before doing other work. Thoughts?

_Copied from original issue: w3c/wptdashboard#171_

**Comment by lukebjerring** [comment]
_From @jgraham on October 23, 2017 15:10_

What's the actual proposed change here? Is it about defining a schema for the existing json (wouldn't using json-schema have fewer additional dependencies) or about changing some data formats (which seems possibly problematic given other consumers).

**Comment by lukebjerring** [comment]
_From @mdittmer on October 23, 2017 15:33_

AFAICT, the tacit proposal is to leverage protocol buffers as a language-independent mechanism for implementing an explicit schema. At the moment, what is eventually written out in JSON is encoded by functions that implicitly produce the these structures (e.g., [report_to_summary](https://github.com/w3c/wptdashboard/blob/master/run/run.py#L305)).

The purpose of this bug is to discuss managing protocol buffer-related dependencies *under the assumption that protocol buffers are a good choice* for implementing an explicit schema.

If there is debate about how these schema should be modeled, we can discuss that here, or create another issue that *blocks* this one until it is resolved.

**Comment by lukebjerring** [comment]
_From @mdittmer on October 23, 2017 15:35_

@jgraham do we have other consumers of our Cloud Storage files that we need to be sensitive to? AFAICT we don't have an explicit schema that those consumers can use to know what to expect. Regardless of what technology we use for it, I think exposing the schema would be a good thing.

**Comment by lukebjerring** [comment]
_From @jgraham on October 23, 2017 15:50_

If the intent is just to document the schema (in code), that seems less worrying than e.g. changing wptrunner to output protobuf (which in itself also isn't necessarily a problem as long as it's done in an additive way).

I'm not sure if anyone consumes the cloud storage files directly at the moment, but the intent is certainly there e.g. it sounds like @lukebjerring is going to use them to set expected results in travis runs.

There are other consumers of e.g. the wptreport format that we use for logging.

I don't have any experience with protobuf to know exactly what it's brining to the table, so it would be interesting to know what the design rationale here is (vs e.g. using json schema to encode the current schema, or any of the N other possibilities).

**Comment by lukebjerring** [comment]
_From @mdittmer on October 23, 2017 15:51_

JSON Schema would be an interesting choice. I'm not sure that it would require fewer dependencies, though. Presumably we would depend on validators for each language. I don't see anything [here](http://json-schema.org/implementations.html) that would provide code generation in Python or Go, or generate Big Query schema.

I suppose one downside to protocol buffers is that, though [JSON is supported](https://developers.google.com/protocol-buffers/docs/proto3#json), developers more familiar with JSON than protocol buffers need to jump through some hoops to consume the JSON without a protocol buffer library.

**Comment by lukebjerring** [comment]
_From @mdittmer on October 23, 2017 15:55_

Perhaps using [something like this](https://github.com/devongovett/protobuf-jsonschema) would allow us to leverage the protocol buffer toolchain for generated code and Big Query schema, while also publishing the more familiar (to web developers) JSON Schema of the data we export.

**Comment by lukebjerring** [comment]
_From @jgraham on October 23, 2017 16:0_

FWIW the only time I personally used JSON Schema was in wptdash, where python is the only target and the goal was not code generation but avoiding ad-hoc validation. Presumably the situation for go is different since code generation is more valuable there.

[1] https://github.com/w3c/wpt-pullresults/blob/007e212574535643e1cb407dc14a34d004f2a5fc/wptdash/blueprints/routes.py#L107

**Comment by lukebjerring** [comment]
_From @jgraham on October 23, 2017 16:3_

I'm not entirely sure there's value to producing JSON schema if the underlying format is protobuf, since I'm guessing it will be ugly.

I guess my position here is that if we are going to change the format we try and do it before there are many consumers that need to be rewritten. Beyond that I don't have a strong technical preference.

**Comment by lukebjerring** [comment]
_From @mdittmer on October 23, 2017 20:2_

@foolip @jeffcarp @jgraham assuming we use protos, do you have any recommendations or preferences for managing source+binary third party dependencies? Same question: ... for managing build scripts?

**Comment by lukebjerring** [comment]
_From @mdittmer on October 27, 2017 14:10_

I've got a proposed solution to dependency management and protocol buffer integration at #183.

**Comment by Hexcles** [comment]
We no longer use protobuf (directly).
