### ISSUE TITLE
[Docker] Docker is not watching file changes in the local build

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2310]
After Go 1.12 migration, docker is not watching file changes in the local development. Before Go 1.12, after starting `./util/docker-dev/web_server.sh`, any changes will reflect in the wpt.fyi local build right away.

I am suspecting https://github.com/web-platform-tests/wpt.fyi/pull/2267, where `docker build -t wptd-dev .` is changed to `docker pull webplatformtests/wpt.fyi:latest`

**Comment by Hexcles** [comment]
Oh the hot reload was a feature of `dev_appserver.py` and we've lost it since migrating to Go 1.12...

This is definitely a bad developer experience. Let me see if there are alternatives here.

**Comment by Hexcles** [comment]
(The image is irrelevant here as it doesn't contain the content of the repo; the repo is always mapped, not copied, into the container.)
