### ISSUE TITLE
[Triage Metadata] Triaged subtests are not shown

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2333]
In https://github.com/web-platform-tests/wpt-metadata/pull/735, the newly-triaged subtest `'[foo=''bar'' s] <div foo="bar"> with querySelector in standards mode'` already exists but [wpt.fyi](https://wpt.fyi/results/css/selectors/attribute-selectors/attribute-case/semantics.html?label=experimental&label=master&aligned) failed to show any icons. In fact, none of subtests are shown in [css/selectors/attribute-selectors/attribute-case/META.yml](https://github.com/web-platform-tests/wpt-metadata/blob/master/css/selectors/attribute-selectors/attribute-case/META.yml)

**Comment by stephenmcgruer** [comment]
Thanks for filing this Kyle! I was coincidentally planning to file this same bug today as @andruud reported it to me (on behalf of Rune). I look forward to finding out what the problem is - I suspect the subtest names are to blame (they're awfully interesting looking ... :D)

**Comment by lilles** [comment]
Found this when I was about to report it. I originally triaged by selecting multiple tests, fwiw. Triaging the single subtest that triggered this issue was to check if it was an issue with marking multiple tests with one crbug.

Given the first comment in this issue, I gather the data is there and I don't have to mark hundreds of tests again. *phew*

**Comment by stephenmcgruer** [comment]
> Given the first comment in this issue, I gather the data is there and I don't have to mark hundreds of tests again. phew

Correct! Sorry about the bug, there is a fix in progress and then all the icons should show up :)

**Comment by KyleJu** [comment]
@lilles A fix is submitted and available in [staging](https://staging.wpt.fyi/results/?label=experimental&label=master&aligned)! I will push it to prod tomorrow. 

Just a side note, if you intend to triage all the subtests in a test file, you can also triage that test and the inline icons will be populated for all the failed subtests :)
