### ISSUE TITLE
[pyup] Update pyup bot's GitHub token

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2339]
Robert has left the team and the GitHub token needs to be updated. https://github.com/web-platform-tests/wpt.fyi/pull/2330

**Comment by stephenmcgruer** [comment]
This bug report doesn't really explain what needs to happen...

1. Is something actually broken due to this? pyup bot appears to be successfully making PRs: https://github.com/web-platform-tests/wpt.fyi/pull/2337
2. How do we configure pyup-bot to use a different GitHub token? Where is pyup configured for wpt.fyi?

**Comment by KyleJu** [comment]
Oops sorry about that 

> This bug report is a bit light on details...
> 
> 1. Is something actually broken due to this? pyup bot appears to be successfully making PRs: #2337

Nothing is broken due to this. However if you look at the bottom of https://github.com/web-platform-tests/wpt.fyi/pull/2330, the user who deleted that PR was Robert. `@Hexcles Hexcles deleted the py-scheduled-update-2021-01-04`

> 2. How do we configure pyup-bot to use a different GitHub token? Where is pyup configured for wpt.fyi?

The configuration file for pyup-bot is [here](https://github.com/web-platform-tests/wpt.fyi/blob/main/.pyup.yml). IIUC, Robert needs to remove himself from the pyup.io account and we have to create a new pyup.io account; see [documentation](https://pyup.io/docs/usage-examples/)

**Comment by KyleJu** [comment]
Actually I am able to log into our repo here https://pyup.io/auth/login/?next=/account/scopes-setup/. Let me see how I can update the GitHub token

**Comment by KyleJu** [comment]
Cannot find anywhere to update GitHub token but it does say I cannot remove the wpt.fyi repo from pyup because Robert created it

**Comment by Hexcles** [comment]
Hmm interesting. I actually didn't know it was using my personal access token. It can -- it asked for `public_repo` scope:
![image](https://user-images.githubusercontent.com/1436812/107390527-c91aa400-6ac5-11eb-97a8-02ac17f1ffb0.png)

However, it should really use its own bot account (it clearly has the permission to create branches, so it should be able to delete branches as well). You can see similar cases in the WPT repo: https://github.com/web-platform-tests/wpt/pull/23513#event-3325911693

Now I'm a bit hesitant to click the revoke button as I don't really understand what the warning means:
![image](https://user-images.githubusercontent.com/1436812/107390790-0d0da900-6ac6-11eb-87cb-1b7532c7c46f.png)
Note that there is only a single button to revoke *all* public repos including WPT. I don't know what'd happen to WPT (I'd expect it not to be affected, as it seems to be using gsnedders' token).

We could do an experiment in a coordinated way, or perhaps someone could reach out to pyup support and ask for clarification (I can't find docs).

**Comment by stephenmcgruer** [comment]
Thanks Robert, appreciate you checking so thoroughly.

> perhaps someone could reach out to pyup support and ask for clarification (I can't find docs).

@KyleJu - can you open an issue against pyup and ask why branch deletions appear as the user who originally setup pyup, rather than using its own bot account (which appears to be the thing used to create branches and pull requests)?

**Comment by KyleJu** [comment]
> Thanks Robert, appreciate you checking so thoroughly.
> 
> > perhaps someone could reach out to pyup support and ask for clarification (I can't find docs).
> 
> @KyleJu - can you open an issue against pyup and ask why branch deletions appear as the user who originally setup pyup, rather than using its own bot account (which appears to be the thing used to create branches and pull requests)?

Yea I will file an issue

**Comment by KyleJu** [comment]
Obsolete
