### ISSUE TITLE
Web components test starts failing for wpt-app.html

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2340]
Web components test starts failing for [wpt-app.html](https://github.com/web-platform-tests/wpt.fyi/blob/f8d9beebe98a4d254d1ae0d0283c4fe7cef3196e/webapp/components/test/wpt-app.html#L23) today, e.g. [master](https://github.com/web-platform-tests/wpt.fyi/runs/1685961315), https://github.com/web-platform-tests/wpt.fyi/pull/2338. 

Tests failed: Error thrown outside of test function: uncaptured fetch: http://localhost:8081/api/versions?product=chrome
window.fetch at wpt-app.html:21
HTMLElement.versionsURLUpdated at /components/wptdashboard/components/product-builder.js:235
Object.runObserverEffect [as fn] at /components/@polymer/polymer/lib/mixins/property-effects.js:245
runEffects at /components/@polymer/polymer/lib/mixins/property-effects.js:146
HTMLElement._propertiesChanged at /components/@polymer/polymer/lib/mixins/property-effects.js:2160
HTMLElement._flushProperties at /components/@polymer/polymer/lib/mixins/properties-changed.js:424
HTMLElement.ready at /components/@polymer/polymer/lib/mixins/property-effects.js:2106
HTMLElement.ready at /components/@polymer/polymer/lib/mixins/element-mixin.js:753
HTMLElement._enableProperties at /components/@polymer/polymer/lib/mixins/properties-changed.js:399
TemplateInstance.__enableOrFlushClients at /components/@polymer/polymer/lib/mixins/property-effects.js:2038

**Comment by KyleJu** [comment]
@stephenmcgruer I cannot reproduce it locally because somehow I am getting `"org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start`. Would you mind trying it on your machine?On a linux machine,  run `make web_components_test`

**Comment by stephenmcgruer** [comment]
I can reproduce via:

```
cd webapp/
npm install
npm run wct -l chrome ./components/test/wpt-app.html
```

Note that originally I had chrome 86 installed as my stable chrome, and it did not reproduce. I then upgraded to chrome 87 and was able to reproduce, so maybe something has changed in the browser.

**Comment by stephenmcgruer** [comment]
Hrm, it may also just be flaky; subsequent runs (3 of them, so far) have succeeded even on chrome 87.

**Comment by stephenmcgruer** [comment]
So the only call to `/api/versions` I can find is `computeVersionsURL` in `webapp/components/product-builder.js`,  (which then triggers `versionsURLUpdated`, which does a `fetch()`).

Now what is weird is that the `<wpt-app>` suite in `./components/test/wpt-app.html` is meant to sandbox out fetches to `/api/(shas|versions|interop)`. I wonder if the call is somehow coming after suite `teardown` ... or actually, if the `suiteSetup` is outliving the testing in general?

**Comment by stephenmcgruer** [comment]
It could also be coming in-between tests, I think. If understand correctly, `setup/teardown` are called for each test in turn, whereas `suiteSetup` is called once before the entire suite.

**Comment by stephenmcgruer** [comment]
I've been unable to reproduce this further, and I don't know of any recent cases. This may be inactionable :/

**Comment by KyleJu** [comment]
Thanks Stephen! Closing this
