### ISSUE TITLE
Triaging together, even when careful, results in blocked wpt-metadata PRs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2362]
Today, @kinu, @makotoshimazu, @mattto, @yutakahirano and I were triaging [untriaged Chrome failures](https://wpt.fyi/results/service-workers/service-worker?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=%28chrome%3A%21missing%26chrome%3A%21ok%26chrome%3A%21pass%29%20and%20none%28triaged%3Achrome%29) together, taking care to not look at the same bug, as per the new [triage instructions](https://github.com/web-platform-tests/wpt.fyi/blob/main/docs/triaging.md).

Unfortunately, 3 PRs still got stuck with merge conflicts at the end of the session: https://github.com/web-platform-tests/wpt-metadata/pull/770 + https://github.com/web-platform-tests/wpt-metadata/pull/771 + https://github.com/web-platform-tests/wpt-metadata/pull/773.

It looks like the problem is mostly that new bugs are being appended to the end of the `META.yml` file.

@stephenmcgruer I believe there's a design floating around for a more in-memory approach to metadata, but I couldn't find an existing bug. That should resolve this problem, right?

**Comment by foolip** [comment]
cc @KyleJu

**Comment by stephenmcgruer** [comment]
This is approximately the same as https://github.com/web-platform-tests/wpt.fyi/issues/2202, but it's not identical. Both would be solved by a completely in-memory model, but https://github.com/web-platform-tests/wpt.fyi/issues/2202 can be solved by some simpler approaches (e.g. caching new triages in memory *without* combining them - whereas combining them would be needed for this I think).

**Comment by foolip** [comment]
Thanks for getting this fixed, @KyleJu!

**Comment by foolip** [comment]
@lucacasonato ran into this again with https://github.com/web-platform-tests/wpt-metadata/pull/1532.

@KyleJu are there still cases where this can happen, or is the cause different and it should be a new issue?

**Comment by KyleJu** [comment]
@foolip why is this an issue? It should affect what users see on the UI because of the caching. And the PRs with merge conflict will be resolved once a day? I

**Comment by KyleJu** [comment]
Okie the cron job didn't run yesterday because the triage happened on staging, instead of prof

**Comment by foolip** [comment]
Perhaps we shouldn't link to the created PRs in a toast if there's no need to do anything with them. That would resolve this I think.

**Comment by KyleJu** [comment]
> Perhaps we shouldn't link to the created PRs in a toast if there's no need to do anything with them. That would resolve this I think.

File a separate issue for it #2601
