### ISSUE TITLE
Triaging a test to an existing bug results in failing tests, blocking PRs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2363]
https://github.com/web-platform-tests/wpt-metadata/pull/771 by @makotoshimazu has ended up blocked because the generated patch adds a new section for a bug already linked. The tests then fail like this:
```
    --- FAIL: TestParseMetadata/service-workers/service-worker/META.yml (0.00s)
        parse_test.go:67: 
            	Error Trace:	parse_test.go:67
            	            				parse_test.go:50
            	Error:      	Should not be: "chrome"
            	Test:       	TestParseMetadata/service-workers/service-worker/META.yml
            	Messages:   	duplicated entries between two links
```

This should be a pretty common scenario, since the same root cause often explains multiple failures.

cc @KyleJu @stephenmcgruer

**Comment by foolip** [comment]
I've edited https://github.com/web-platform-tests/wpt-metadata/pull/771 manually to fix the problem.

**Comment by stephenmcgruer** [comment]
>  a new section for a bug already linked

I think this is roughly the same case as all of our other 'race condition' bugs - here two PRs were assumedly created close together, both of which added an entry linking to issue 906991, and therefore once the first one landed the second wouldn't pass the tests. It's no different than the second one getting a merge conflict, it just shows that we need a consistent story on the wpt.fyi side for handling concurrent or close-together triage.

**Comment by foolip** [comment]
This wasn't a merge conflict so I assumed it was different. But perhaps it was a problem of not having an up-to-date copy of the repo, and thus failing to produce the right diff, even though it didn't conflict.

**Comment by KyleJu** [comment]
This should be fixed by https://github.com/web-platform-tests/wpt-metadata/pull/1139

**Comment by foolip** [comment]
Thanks @KyleJu! Now that this has been running for a while, how is it working in practice? Has any pending metadata been resolved via a PR yet?

**Comment by KyleJu** [comment]
No problems. It works fairly well - I used to resolve merge conflicts whenever PRs come, but now I pretty much submit the PR generated by web-platform-tests/wpt-metadata#1139 once a day. The next improvement could be to automatically close the PRs who were stuck
