### ISSUE TITLE
Navigating between interop and results view has gotten harder

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#2396]
Since #2325 landed, there's no easy way to get from (e.g.) https://wpt.fyi/interop/apng?label=experimental&label=master&aligned to https://wpt.fyi/results/apng?label=experimental&label=master&aligned

Perhaps the "Interoperability" in the header should turn to "Results" when in interop view?

**Comment by foolip** [comment]
@gsnedders are you making use of the interop view? I've found that I'm never using it now that the search syntax is fairly capable. We're considering removing the view, would that affect you?

**Comment by KyleJu** [comment]
Interop view has been removed. Closing this bug
