### ISSUE TITLE
change warning to say doesnt test current versions of browsers

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#24]
_From @dstorey on October 22, 2017 6:48_

Currently says doesn't test pre-release versions of Edge and Safari

Actually doesn't even test current versions of Edge and Safari.

_Copied from original issue: w3c/wptdashboard#170_

**Comment by lukebjerring** [comment]
_From @jeffcarp on October 22, 2017 15:49_

We should be testing at least the current public versions of browsers, otherwise that's a bug.

**Comment by lukebjerring** [comment]
_From @jgraham on October 22, 2017 18:27_

I think we aren't necessarily because Sauce is a little behind. There is talk about moving to BrowserStack which allegedly might be more  up to date, at least with Edge.

We would of course do much better here if MS and Apple weren't tying browser version to OS versions, and then placing restrictive license requirements on those OSes that makes it impractical to provide them through a service like TravisCI.

**Comment by lukebjerring** [comment]
_From @jgraham on October 22, 2017 18:27_

(and I think there has been discussion about getting Microsoft and Apple to provide their own results, but so far I haven't seen anything come of that).

**Comment by foolip** [comment]
Current warning is "Each browser listed here is currently tested at its latest stable release." That's correct for the default view, but I'll still send a PR to remove it.
