### ISSUE TITLE
go-github v33 introduces breaking changes

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2403]
wpt.fyi currently uses `github.com/google/go-github/v32`. In [v33](https://github.com/google/go-github/releases/tag/v33.0.0), changes in [UpdateCheckRunOptions](https://github.com/google/go-github/pull/1658#) will cause breaking changes. See the use of [UpdateCheckRunOptions in wpt.fyi](https://github.com/web-platform-tests/wpt.fyi/search?q=UpdateCheckRunOptions)

**Comment by stephenmcgruer** [comment]
If I understand correctly, the parameter is already ignored by GitHub so we aren't updating it anyway by specifying it? In which case we should (a) just remove it, but also (b) maybe try to figure out if and why we wanted it originally.

**Comment by KyleJu** [comment]
Yup correctly. It looks like the only purpose of it is to call [`GetHeadSHA`](https://github.com/google/go-github/pull/1658/files#diff-8fa7fc67c938c0b64412244e6c7b6e49439b0aaef26a3cd9d6f174260310b45cL14072). We are not updating it/using it in the code.
