### ISSUE TITLE
Cannot load wpt.fyi status 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2411]
In both prod and stating, https://wpt.fyi/status doesn't really load and show this error:

`Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".`

**Comment by KyleJu** [comment]
The status page is working in the previous [release](https://rev-3fa4ae5f-dot-wptdashboard.uc.r.appspot.com/status)

**Comment by KyleJu** [comment]
its likely caused by https://github.com/web-platform-tests/wpt.fyi/pull/2381 and https://github.com/web-platform-tests/wpt.fyi/pull/2380

**Comment by KyleJu** [comment]
Fixed in [staging](https://staging.wpt.fyi/status). Will be fixed in the next prod push

**Comment by stephenmcgruer** [comment]
A few questions:

Do we know the root-cause of the issue? 

Is our intention here to just never update `vaadin` again?

Could we write some sort of test that would have caught this before deploying?

**Comment by lucacasonato** [comment]
@KyleJu It broke in staging again.

**Comment by KyleJu** [comment]
Thanks for the headsup! As a next step, I will stop Renovate from upgrading this dependency until we figure out why
