### ISSUE TITLE
Make results receiver idempotent

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#247]
Requirement: if a test runner uploads the same result or TaskQueue dispatches the same task multiple times, we shouldn't create any duplicated data in GCS or Datastore.

The GCS part is already satisfied. The paths for both the full report and the sharded JSONs are deterministic and unique (keyed by \<revision, product, SHA of the report\> since #233 ). And the transformation (splitting) process is also deterministic. Hence, even if the processor processes the same result multiple times, the final data in GCS will still be the same.

Datastore part isn't satisfied yet, because processor always invoke the `/api/run` API to create test runs and neither the processor or the test run API has any duplication detection. We can similarly leverage #233 and use \<revision, product, SHA of the report\> as a unique key in Datastore. The test run API should not create another run if the key already exists.

Lastly, an optional optimization is to skip a task altogether if the API says the key already exists.

**Comment by Hexcles** [comment]
cc @foolip @lukebjerring this is the idempotency issue I was working on, but was kind of put on the back burner because I almost never saw duplicate webhook deliveries in the wild.

During the [GitHub incident](https://blog.github.com/2018-10-21-october21-incident-report/), there was massive duplicatation, when GitHub paused all webhooks and then redelivered them after recovery.

I'll resume this work.

**Comment by foolip** [comment]
Thanks Robert, I agree this is looking more important now than before :)
