### ISSUE TITLE
 GID XX already exists

### ISSUE THREAD

**Issue by chinatyc** [web-platform-tests/wpt.fyi#250]
```
sworddance@MacBook-Pro wpt.fyr.orig$ ./util/docker-dev/run.sh
[  2018-06-08 14:49:22  INFO  ]  Creating docker instance for dev server. Instance name: wptd-dev-instance
[  2018-06-08 14:49:22  WARN  ]  Found existing docker instance wptd-dev-instance. Remove?
Confirm (y/N): y
[  2018-06-08 14:49:29  INFO  ]  Stopping wptd-dev-instance...
wptd-dev-instance
[  2018-06-08 14:49:30  INFO  ]  wptd-dev-instance stopped.
[  2018-06-08 14:49:30  INFO  ]  Removing wptd-dev-instance...
wptd-dev-instance
[  2018-06-08 14:49:31  INFO  ]  wptd-dev-instance removed.
[  2018-06-08 14:49:31  INFO  ]  Starting docker instance wptd-dev-instance...
8f2faf5b1be5dadb289e1b5fc2df3d35b7012bdd3dd1074825d39042f1d737a5
[  2018-06-08 14:49:31  INFO  ]  Setting up local user
groupadd: GID '20' already exists
```
what is GID XX already exists

**Comment by Hexcles** [comment]
(I edited the description to make it more readable.)

This is weird. @chinatyc could you checkout the most recent master and try again? And when running the script, if you are asked "Found existing docker instance wptd-dev-instance. Remove?", please say yes ("y").

**Comment by CYBAI** [comment]
I got into the same issue with latest master (3dea9f3) on `macOS 10.13`

```
→ ./util/docker-dev/run.sh
[  2018-10-14 18:01:28  INFO  ]  Creating docker instance for dev server. Instance name: wptd-dev-instance
Error: No such object: wptd-dev-instance
[  2018-10-14 18:01:29  INFO  ]  Starting docker instance wptd-dev-instance...
4ffd7a4785e9d1c8f8d1917118caaac77e50a6e34e0cbf576a89cf8038ed1e0d
[  2018-10-14 18:01:29  INFO  ]  Setting up local user
groupadd: GID '20' already exists
```

**Comment by Hexcles** [comment]
Oh I just realized what was happening:

We try to create a user and a group inside Docker with the same UID & GID as the current user outside of Docker as a hack to simplify permission setup of Docker volumes. However, the UID & GID are low on Mac (<1000), which collide with some Linux system users/groups.

**Comment by AutomatedTester** [comment]
@Hexcles did you have a plan of how you wanted this fixed (or have you fixed this already)? I remember discussing this with you in Lyon and you had further thoughts about how the docker code should look like
