### ISSUE TITLE
Split experimental label into two or more labels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#252]
The runs in https://wpt.fyi/results/?label=experimental are currently Chrome Dev and Firefox Nightly, but due to https://github.com/web-platform-tests/results-collection/issues/569 at least Chrome isn't experimental in on sense. (Not sure about Firefox Nightly defaults.)

If we later change the Chrome Dev configuration, or just split it into two, the different configurations need to be distinguished somehow. For Chrome, there's the release channel (stable, beta, dev, canary) and the use of --enable-experimental-web-platform-features.

Given the different naming conventions and number of release channels, shared labels for release channels are probably hard.

Proposal:
* Labels matching how each browser names their channels, so "dev" and "beta" shared for Chrome/Firefox, but "canary" and "nightly" not shared. Don't know about "Safari Techology Preview" and "Edge Insider Preview". Maybe "preview" for both?
* A label that means that maximally many features have been enabled, including ones which aren't expected to reach stable any time soon. Unfortunately, "experimental" is a very good name for this label.
* Maybe: a pseudo-label or implied label that would allow https://wpt.fyi/results/?label=foo to eventually match Chrome Dev, Edge Insider Preview, Firefox Nightly and Safari Technology Preview.

**Comment by Hexcles** [comment]
I'm inclined to turn on experimental flags for the dev/nightly version of both Chrome and Firefox, and keep using a single "experimental" flag for now, until there's real need for running the dev/nightly version without experimental features. "experimental" will always mean the bleeding-edge version + experimental features.

And when we do have the need for running more configurations, we can use other labels. The proposals aren't really mutually exclusive. Remember, this is a "label" system, not "category". For example, we can keep the official channel names of each browser (proposal 1), as well as some wpt.fyi-specific, consistent channel names across all browsers (proposal 3). And we can use a label like "experimental-features" for proposal 2 when it's needed (again, I'd like to use the shorter "experimental" for the immediate use case).

I wrote a script to easily [add/modify labels retroactively](https://github.com/web-platform-tests/data-migration/issues/4), so don't worry about historical runs.

**Comment by foolip** [comment]
The existing Chrome Dev / Firefox Nightly runs don't fit the "bleeding-edge version + experimental features" definition, would it be equally fine to just not have any labels for those existing runs and start applying the experimental label at the same time the runner config is changed? (Presumably the runner would suggest the label to the results receiver?)

**Comment by Hexcles** [comment]
@foolip totally, also see my newest comment at https://github.com/web-platform-tests/results-collection/issues/569#issuecomment-397399596

For the existing runs, they don't have any labels at all in prod; besides, my script can batch modify labels for historical runs very easily. So don't worry.

**Comment by foolip** [comment]
OK, I'm not worried :)
