### ISSUE TITLE
When do we use the blue Chromium logo?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2554]
I don't understand what I'm look at here:
https://wpt.fyi/runs?sha=f44fd9953ebdbe8ef90ddf3bae8daaaa0173a92c&max-count=100
https://wpt.fyi/runs?sha=978fb5b951ca43ab646811ad956edaed5640f9bb&max-count=100

For these runs (probably lots more) a blue Chromium logo is used, but the results come from Taskcluster.

I'm concerned that we might be mixing up these runs with the Chrome runs in https://github.com/Ecosystem-Infra/wpt-results-analysis but step 1 is to understand what they are.

**Comment by foolip** [comment]
OK, the logo is explained by this:
https://github.com/web-platform-tests/wpt.fyi/blob/1eff5084b5f85d14cdda1dbe74d7f41eb10a59e3/webapp/components/product-info.js#L158-L160

This was added in https://github.com/web-platform-tests/wpt.fyi/pull/2100.

So we use the Chromium logo when the nightly label is used, because it actually is Chromium.

I think we should:
- [Split chrome product into chromium and chrome](https://github.com/web-platform-tests/wpt/issues/28970) in WPT, so that they cannot be conflated
- Support chromium as its own product on wpt.fyi
- Relabel existing wpt.fyi chrome runs which were in fact Chromium
- Bonus: Show the Chromium revision number instead of the 4-part version string

**Comment by foolip** [comment]
It sure looks like we're running this configuration every day:
https://wpt.fyi/runs?label=nightly&label=master&max-count=100&product=chrome

But I'm struggling to find where it's triggered.

**Comment by past** [comment]
This has been implemented in #3460 and others.
