### ISSUE TITLE
GitHub security warning regarding a node package

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#256]
GitHub sent a security warning regarding one of our Node dependencies last week (somehow I can't find it now).

Basically, the package in question a dependency of `mocha`, which is a dependency of `web-component-tester`. We only use `wct` for testing (and mostly inside Docker), so it's not a big concern.

We just need to wait for `wct` to make a new release, which will depend on an up-to-date `mocha` version. Then we can update our `packages{-lock}.json`.

**Comment by lukebjerring** [comment]
I dismissed it with the "This code isn't actually used" option (as we only use it for testing, in Travis..)
