### ISSUE TITLE
Staging deployment missing

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2560]
For the recent PRs, I don't see any staging deployment. The deployment on staging [wpt.fyi](https://staging.wpt.fyi/about) seems to be behind as well.

e.g. https://github.com/web-platform-tests/wpt.fyi/pull/2557

**Comment by KyleJu** [comment]
@foolip I will look into it but tag you in case you have experience with it before

**Comment by foolip** [comment]
I haven't tinkered with the staging deployment code, but I have set up CI for deploying to AppEngine elsewhere so if you're stumped I could take a look.

First off, did the deploy step run in CI at all? If yes, how did it fail?

**Comment by KyleJu** [comment]
Tested in #2561. Deploy step doesn't run in CI at all

**Comment by KyleJu** [comment]
On the https://travis-ci.com/github/web-platform-tests/wpt.fyi/requests, I see `
Could not authorize build request for web-platform-tests/wpt.fyi.` for most of the missing deployment

**Comment by KyleJu** [comment]
@foolip [“Could not authorize build request”, usually means that the account’s subscription expired or that it ran out of trial builds](https://docs.travis-ci.com/user/common-build-problems/). Not sure how the billing is setup?

**Comment by foolip** [comment]
The linked billing account seems fine. Have you checked logs in GCP to see if they say something interesting.

Another idea is maybe our service account keys need updating, do they really have infinite lifetime?

**Comment by KyleJu** [comment]
Checked GCP but didn't see anything interesting. There is no log for the missing deployment.

How do we update the service account keys? Do I have access to it.

Also I see the pricing change article here - https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. it looks like we have to choose a pricing plan?

**Comment by foolip** [comment]
Oh wait, I misunderstood. It's Travis CI saying that build can't be started, not a step within that has GCP saying the GCP deploy build can't be started.

I think we should migrate from Travis CI to GitHub Actions to sidestep the whole problem.

**Comment by KyleJu** [comment]
[In latest GitHub actions deployment}(https://github.com/web-platform-tests/wpt.fyi/runs/2948394952), Webapp is deployed successfully and it confirmed the fix for https://github.com/web-platform-tests/wpt.fyi/issues/2411. The only issue with webapp is the version name. It should incorporate WPT SHA instead of [refs-heads-main](https://pantheon.corp.google.com/appengine/versions?project=wptdashboard-staging&serviceId=default)

Processor deployment failed.

**Comment by KyleJu** [comment]
`deploy-comment.sh` still needs to be fixed

**Comment by KyleJu** [comment]
Also the deployment fails, it should be cleaned up automatically. #2567 might have missed that

**Comment by KyleJu** [comment]
Latest deployment on main was successful but clean up failed. It tries to delete too many versions, even the one in use and wasnt able to delete outdated PR deployment.

/home/user/wpt.fyi//util/cleanup-versions.sh
[  2021-06-30 07:02:05  INFO  ]  Cleaning stale versions of default...
[  2021-06-30 07:02:06  DEBUG ]  'rev-30b7df1' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:06  DEBUG ]  'rev-4ba5cce' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:06  DEBUG ]  'rev-b92ed99' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:06  DEBUG ]  'rev-e0cd00d' is not a branch in upstream and will be deleted.
f4cf8a605efcc80fe269e947466c9e5acbfd6a04	refs/heads/validate-url
Deleting the following versions:
 - wptdashboard-staging/default/rev-30b7df1
 - wptdashboard-staging/default/rev-4ba5cce
 - wptdashboard-staging/default/rev-b92ed99
 - wptdashboard-staging/default/rev-e0cd00d
[  2021-06-30 07:02:35  INFO  ]  Cleaning stale versions of processor...
[  2021-06-30 07:02:36  DEBUG ]  'rev-30b7df1' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:36  DEBUG ]  'rev-4ba5cce' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:36  DEBUG ]  'rev-b92ed99' is not a branch in upstream and will be deleted.
[  2021-06-30 07:02:36  DEBUG ]  'rev-e0cd00d' is not a branch in upstream and will be deleted.
Deleting the following versions:
 - wptdashboard-staging/processor/rev-30b7df1
 - wptdashboard-staging/processor/rev-4ba5cce
 - wptdashboard-staging/processor/rev-b92ed99
 - wptdashboard-staging/processor/rev-e0cd00d
[  2021-06-30 07:03:03  INFO  ]  Cleaning stale versions of searchcache...
[  2021-06-30 07:03:04  DEBUG ]  'rev-30b7df1' is not a branch in upstream and will be deleted.
[  2021-06-30 07:03:05  DEBUG ]  'rev-4ba5cce' is not a branch in upstream and will be deleted.
[  2021-06-30 07:03:05  DEBUG ]  'rev-b92ed99' is not a branch in upstream and will be deleted.
[  2021-06-30 07:03:05  DEBUG ]  'rev-e0cd00d' is not a branch in upstream and will be deleted.
Deleting the following versions:
 - wptdashboard-staging/searchcache/rev-30b7df1
 - wptdashboard-staging/searchcache/rev-4ba5cce
 - wptdashboard-staging/searchcache/rev-b92ed99
 - wptdashboard-staging/searchcache/rev-e0cd00d
ERROR: (gcloud.app.versions.delete) Issue deleting version: [searchcache/rev-30b7df1]

[searchcache/rev-30b7df1]: ABORTED: Cannot operate on apps/wptdashboard-staging/services/searchcache/versions/rev-30b7df1 because an operation is already in progress for apps/wptdashboard-staging/services/searchcache/versions/rev-30b7df1 by d790376e-3689-400f-a568-873851372888.
make: *** [Makefile:256: cleanup_staging_versions] Error 1
Error: Process completed with exit code 2.

**Comment by KyleJu** [comment]
Looking at the [script](https://github.com/web-platform-tests/wpt.fyi/blob/main/util/cleanup-versions.sh#L23), clean up script deletes every instance thats older than 1 day and without a corresponding branch. It appears to work correctly

**Comment by KyleJu** [comment]
> Also when deployment fails, it should be cleaned up automatically. #2567 might have missed that

This is done by the clean up script.

**Comment by KyleJu** [comment]
Latest deployment [succeeded](https://github.com/web-platform-tests/wpt.fyi/runs/2954929541) but staging.wpt.fyi is still outdated because its status page is broken. The same status page is working on the latest deployment.

**Comment by KyleJu** [comment]
> Latest deployment [succeeded](https://github.com/web-platform-tests/wpt.fyi/runs/2954929541) but staging.wpt.fyi is still outdated because its status page is broken. The same status page is working on the latest deployment.

appear to be a caching issue.

**Comment by KyleJu** [comment]
Filed a separate issue for deploy-comment.sh migration. Closing this issue
