### ISSUE TITLE
Non-semver version strings are unhandled

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#258]
The current handling of `product` param expects all parts of a version string to be an integer.

This is not always the case:
 - Chrome: `69.0.3452.0 dev`
 - Firefox: `62.0a1`

**Comment by lukebjerring** [comment]
@foolip did bring this up during https://github.com/web-platform-tests/wpt.fyi/pull/180 - this issue is intended to follow up on the known limitations.

**Comment by Hexcles** [comment]
In general, shall we make the assumption that browser versions are always semver? Especially in the future we might have random mobile browsers etc.

@lukebjerring could you elaborate again here why we need to parse the version.

**Comment by lukebjerring** [comment]
Note that this also affects some of the URLs, @Hexcles, since there is a space in Chrome's version string.

e.g. 

> https://storage.googleapis.com/wptd-results-staging/9d009fc59a8f99e0117b841b7f49094cc690964c/chrome_69.0.3452.0 dev_linux_16.04_cbc71e6c36/report.json

**Comment by lukebjerring** [comment]
No, we certainly shouldn't be assuming it's semantic. 
The use-case for parsing is with the `product` param, which we want to be able to get more or less specific with, e.g. `chrome-69`, `chrome-69.0.3452`

**Comment by Hexcles** [comment]
> The use-case for parsing is with the product param, which we want to be able to get more or less specific with, e.g. chrome-69, chrome-69.0.3452

This use case can be more or less satisfied by prefix matching (except some edge cases like `chrome-6`, which is probably fine to ignore...), unless we want to support queries like "version > 68" in the future.

**Comment by Hexcles** [comment]
Basically, I'm inclined to treat versions as verbatim strings with as few special cases/patterns as possible.

**Comment by lukebjerring** [comment]
> This use case can be more or less satisfied by prefix matching (except some edge cases like chrome-6, ...

Interesting choice of example... https://github.com/web-platform-tests/wpt.fyi/blob/7ecad52787995c22afa2345d21cf6e974f1bac3d/api/test_run_medium_test.go#L81

**Comment by Hexcles** [comment]
lol yeah I found that test when I touched some related code (and I vaguely remember @foolip mentioned this edge case somewhere?)

But I think ignoring this edge case and treating versions as arbitrary strings would be the right tradeoff.

**Comment by Hexcles** [comment]
I just realized that the current code actually still kinda worked. By "kinda", I mean:

* The code doesn't really make assumptions about the `BrowserVersion` field in Datastore. The following queries can find the `* dev` version of Chrome and the `*a1` version of Firefox as expected:
https://staging.wpt.fyi/api/runs?product=chrome-69
https://staging.wpt.fyi/api/runs?product=firefox-62
* However, the code assumes the `product` **param** in URL must be a semvar, i.e. the following query will cause an error:
https://staging.wpt.fyi/api/runs?product=firefox-62.0a1

I guess the status quo is probably acceptable. It won't block launching the results receiver and isn't urgent to fix.

**Comment by foolip** [comment]
> Basically, I'm inclined to treat versions as verbatim strings with as few special cases/patterns as possible.

This is my thinking as well, do assume that *no* versions follow semver and instead invent our own (really!) way of interpreting version strings.

I *think* that we can, as a start, just say that version strings are arbitrary strings, but that periods have a special meaning, so that "69" matches "69.0.3452" but "6" does not. If, in the future, we were to support > and < comparisons, we could probably invent something that works well enough for that too.

**Comment by lukebjerring** [comment]
Did some work handling special cases in #693 #691
