### ISSUE TITLE
[GitHub actions] Could not read json file /home/user/wpt.fyi/client-secret.json

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2585]
Staging Deployment failed in https://github.com/web-platform-tests/wpt.fyi/pull/2582 due to following errors:

ERROR: (gcloud.auth.activate-service-account) Could not read json file /home/user/wpt.fyi/client-secret.json: Expecting value: line 2 column 1 (char 1)
make: *** [Makefile:238: gcloud_login] Error 1
Error: Process completed with exit code 2.

This is the first occurrence since the migration. This issue should be prioritized if it happens more often

**Comment by lucacasonato** [comment]
@KyleJu I think it happened because the staging run tried to run on my PR, even though I don't have access to the secrets in this repo.

**Comment by KyleJu** [comment]
Aha you are right. fork shouldn't be able to access to the secret. @foolip I guess this is expected?

**Comment by foolip** [comment]
@KyleJu that's expected, yes, but it's related to a comment I made on another PR. We should never go down the deploy code path in this case, some extra condition is needed to avoid that.
