### ISSUE TITLE
Safari runs stuck in processor (retrying)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2620]
https://staging.wpt.fyi/status currently lists runs 5188220648161280 and 5337945892454400 as being in the processor.

At https://pantheon.corp.google.com/cloudtasks/queue/us-east4/results-arrival/tasks?project=wptdashboard-staging one can see that both are stuck retrying:
![image](https://user-images.githubusercontent.com/498917/129754660-fab9d9c9-3608-4321-a7f8-19d1a95651f9.png)

However, following the links to logs, I can't find any logs at all, no matter how far back in time I search.

I've also tried searching for logs for any /api/results/process requests, but I can't find any for these runs.

@KyleJu can you help figure out what's going wrong here? I assume there's something about the input that the processor is failing on, but it's not really possible to find out what without the logs.

**Comment by KyleJu** [comment]
Unrelated question: why is the processor running on the staging instance?

**Comment by KyleJu** [comment]
A little progress - the requests for these two tasks are [getting 500 errors](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22http_load_balancer%22%0Aresource.labels.backend_service_name%3D%22aef-processor-rev--fa3a70b-bs%22;timeRange=2021-08-17T16:04:16.252Z%2F2021-08-17T18:04:44.398167Z;cursorTimestamp=2021-08-17T17:53:11.848763Z?project=wptdashboard-staging)

**Comment by KyleJu** [comment]
Finally found [the logs](https://pantheon.corp.google.com/logs/query;query=%0Aresource.labels.module_id%3D%22processor%22;timeRange=2021-08-17T18:43:19.321Z%2F2021-08-17T18:43:19.321Z--PT1H;summaryFields=:true;cursorTimestamp=2021-08-17T18:43:21Z?customFacets=&scrollTimestamp=2021-08-17T18:24:46.000000000Z&project=wptdashboard-staging) - see timestamps starting at `2021-08-17T18:43:21Z`:

Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vmagent/app/main.py", line 69, in decorated_func
    return func(*args, **kwargs)
  File "/home/vmagent/app/main.py", line 52, in decorated_func
    return func(*args, **kwargs)
  File "/home/vmagent/app/main.py", line 114, in task_handler
    resp = processor.process_report(task_id, flask.request.form)
  File "/home/vmagent/app/processor.py", line 331, in process_report
    p.load_report()
  File "/home/vmagent/app/processor.py", line 194, in load_report
    self.report.load_file(r)
  File "/home/vmagent/app/wptreport.py", line 207, in load_file
    self.load_json(f)
  File "/home/vmagent/app/wptreport.py", line 229, in load_json
    report = json.load(text_file, strict=False)
  File "/opt/python3.7/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/python3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by gsnedders** [comment]
What JSON is that trying to decode?

**Comment by KyleJu** [comment]
> What JSON is that trying to decode?

I believe it is trying to decode the results for gs://wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json

**Comment by gsnedders** [comment]
> I believe it is trying to decode the results for gs://wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json

Can you share that anywhere, rather than me trying to understand how to fetch a file from gs if I even have permission to do so? Presumably it is an issue with the processor though, given the original JSON uploaded decodes fine?

(Also this state should presumably put the build in the INVALID state with an error for it saved?)

**Comment by foolip** [comment]
> Unrelated question: why is the processor running on the staging instance?

@gsnedders is trying to upload Safari results from a new configuration and is trying things out on staging.

**Comment by foolip** [comment]
> > I believe it is trying to decode the results for gs://wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json
> 
> Can you share that anywhere, rather than me trying to understand how to fetch a file from gs if I even have permission to do so? Presumably it is an issue with the processor though, given the original JSON uploaded decodes fine?
> 
> (Also this state should presumably put the build in the INVALID state with an error for it saved?)

The URL is https://storage.cloud.google.com/wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json?_ga=2.65190700.-345301030.1597093354 but requires authentication. I dowloaded it and am pretty sure the problem is that it's gzipped and the code is expecting something uncompressed.

Perhaps the results were gzipped twice, or perhaps the results API expects uncompressed reports?

**Comment by KyleJu** [comment]
> > > I believe it is trying to decode the results for gs://wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json
> > 
> > 
> > Can you share that anywhere, rather than me trying to understand how to fetch a file from gs if I even have permission to do so? Presumably it is an issue with the processor though, given the original JSON uploaded decodes fine?
> > (Also this state should presumably put the build in the INVALID state with an error for it saved?)
> 
> The URL is https://storage.cloud.google.com/wptd-results-buffer/gsnedders/2e96f7e1-e377-4fe6-b41c-b6d40ffccf7c/0.json?_ga=2.65190700.-345301030.1597093354 but requires authentication. I dowloaded it and am pretty sure the problem is that it's gzipped and the code is expecting something uncompressed.

I think that might be the issue too, although it is supposed to correctly detect [gzip as well](https://github.com/web-platform-tests/wpt.fyi/blob/078da6b69090ab77c00ebf557e682d294fe86624/results-processor/wptreport.py#L204) using the file extension. It went down to the wrong path and called `self.load_json(f)`

> 
> Perhaps the results were gzipped twice, or perhaps the results API expects uncompressed reports?

**Comment by gsnedders** [comment]
> Perhaps the results were gzipped twice, or perhaps the results API expects uncompressed reports?

https://github.com/web-platform-tests/wpt.fyi/blob/main/api/README.md#apiresultsupload says "A gzipped JSON file"

> I think that might be the issue too, although it is supposed to correctly detect gzip using the file extension. It went down to the wrong path and called self.load_json(f)

Oh, hmm. If that's the case we should make sure the API documentation say that it needs uploaded with a specific extension, or make sure it is named appropriately? (Note that you can detect if something is gzip'd by inspecting the first two bytes.)

**Comment by foolip** [comment]
Thanks @KyleJu for sending https://github.com/web-platform-tests/wpt.fyi/pull/2630, I've reviewed and merged that now.

@gsnedders can you confirm if that fixes the whole problem? New docs inlined for convenience:

> __`result_file`__: A **gzipped** JSON file, with the filename ending with `.gz` extension, produced by `wpt run --log-wptreport`.
