### ISSUE TITLE
[CI] Staging deployment auth key update

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2644]
The previous staging deployment key has recently expired in https://github.com/web-platform-tests/wpt.fyi/issues/2643. The newly created key has an expiry date of Dec 19, 2021. So this key needs to be updated every quarterly

**Comment by foolip** [comment]
Is 3 months the longest possible duration, or just the default?

Do we have some mechanism to remind ourselves every 2-3 months of the need to do this, and instructions for how to generate a new key?

**Comment by KyleJu** [comment]
It was the default options and cannot modify it. In terms of instructions, we have to go to [service account page](https://pantheon.corp.google.com/iam-admin/serviceaccounts/details/104155495737475210708/keys?project=wptdashboard-staging), remove the old key and create a new key in a JSON file. Copy and paste the content of the JSON file to `GCLOUD_KEY_FILE_JSON` in wpt.fyi Actions secrets

**Comment by KyleJu** [comment]
Note that I am still trying to request an exemption for `Exported Service Account Key review`, so the fate of this key is still unknown

**Comment by KyleJu** [comment]
The newly created key expired on Dec 19 but new keys cannot be created due to org permissin. Looks like I have to escalate this issue

**Comment by KyleJu** [comment]
> The newly created key expired on Dec 19 but new keys cannot be created due to org permissin. Looks like I have to escalate this issue

The key has been updated. The next update cycle is April 7

**Comment by KyleJu** [comment]
This has been added to the interop tooling rotation. Closing this bug
