### ISSUE TITLE
Add a warning about Safari results being out of date

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2663]
Suggested by @yoavweiss in https://twitter.com/yoavweiss/status/1446087339214872588.

Before line 149 here probably makes sense:

https://github.com/web-platform-tests/wpt.fyi/blob/3bd4d70805a5ad532db42f0bfb38c7541c2b7cba/webapp/views/wpt-app.js#L145-L165

It should ideally be conditional on Safari actually being shown, but in practice it would be fine to always show it.

cc @KyleJu @gsnedders

**Comment by voxpelli** [comment]
People keep referencing the wpt.fyi front page to point at how much Safari is falling behind, getting this warning up there would very much help in avoiding people drawing conclusions from a data set that is different to what they expect.

What can be done to help push this one along @foolip?

**Comment by voxpelli** [comment]
This is related to https://github.com/web-platform-tests/wpt/issues/31147

**Comment by foolip** [comment]
@voxpelli I created this issue after discussion with @gsnedders, to point out where it would make sense to add the warning. I'd prefer for it to be worded by someone at Apple, but of course if someone sends a pull request and it looks reasonable, @KyleJu or I can review and merge it.

**Comment by foolip** [comment]
Also note that @stephenmcgruer has done the work to use WebKitGTK numbers instead to get an idea of what current Safari Technology Preview scores would most likely be, see https://staging.wpt.fyi/compat2021?feature=summary&use_webkitgtk for a preview of that.

**Comment by jensimmons** [comment]
What is the current proposed text? I'm not seeing it in your PR.

**Comment by voxpelli** [comment]
Which PR @jensimmons? As far as I know no PR has been created yet?

**Comment by foolip** [comment]
@stephenmcgruer has sent a PR at https://github.com/web-platform-tests/wpt.fyi/pull/2679 now.

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer has sent a PR at #2679 now.

Note that this PR is only for /compat-2021, and I believe this issue was for wpt.fyi in general.

**Comment by foolip** [comment]
Oh, right, this issue will remain open then even if that's merged.

**Comment by foolip** [comment]
There's wording that could be copied from https://github.com/web-platform-tests/wpt.fyi/pull/2679 now.

**Comment by foolip** [comment]
Safari is no longer out of date, closing this issue.
