### ISSUE TITLE
show a row with totals

### ISSUE THREAD

**Issue by dbaron** [web-platform-tests/wpt.fyi#2667]
It would be useful if wpt.fyi directory listings showed a row either at the top or bottom with the totals.

For example, I've been focusing a lot on the [list of css-transforms tests](https://wpt.fyi/results/css/css-transforms?label=master&label=experimental).  But the piece of information that I don't see in that view is the information shown in the "css-transforms" line within the [list of all css tests](https://wpt.fyi/results/css?label=master&label=experimental) that has the totals for the css-transforms directory.  I'd like to see that line shown as a "Total" row at either the top or the bottom of the css-transforms list.

I think it would be useful to show this total line in the css-transforms directory listing rather than having to go up to the css directory listing to see it.

**Comment by DanielRyanSmith** [comment]
Hello @dbaron, I'd like to get your opinion on #2841 to ensure it adds the change you're looking for in this issue. Thanks!

**Comment by DanielRyanSmith** [comment]
This functionality was added some time ago and is available in production.
