### ISSUE TITLE
Rename Compat 2021 to Interop 2021

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2674]
As suggested by @jensimmons in https://github.com/web-platform-tests/interop-2022/issues/3.

This would mainly involve redirecting https://wpt.fyi/compat2021 to https://wpt.fyi/interop-2021 and doing a broad search/replace of the terms.

@stephenmcgruer is there any problem with this that I might be overlooking?

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer is there any problem with this that I might be overlooking?

No, it should be fairly straightforward. To be super thorough the underlying data sources might also want to be renamed.

Should we leave a butter-bar at the top noting it used to be called compat2021, given the previous blog-posts/etc with that name?

**Comment by jensimmons** [comment]
Actually, I don't think the URL needs to be changed. Or old blog posts. I was suggesting that we call it "Interop 2021" from here forward, and say so publicly on day we announce Interop 2022. 

We can't change history, so why try. Let the name change be part of the history. And simply use the new name in new content. At least that's my opinion. 

A small note could be added to older blog posts that says "in fall 2021, we started calling this effort Interop 2020" for clarity. It seems like that kind of update — on that gets a small note from the future.

**Comment by DanielRyanSmith** [comment]
This has been essentially completed - [/compat2021](https://wpt.fyi/compat2021) now redirects to [/interop-2021](https://wpt.fyi/interop-2021), and the dashboard has been renamed accordingly.
