### ISSUE TITLE
[CI] web_components_test selenium installation failures

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2677]
Starting last week, the web_components_test started to fail for [all PRs](https://github.com/web-platform-tests/wpt.fyi/actions/workflows/ci.yml). The check is failing at the start of `Installing and starting Selenium server for local browsers`:

File from https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar has already been downloaded

Error: Could not write to /github/workspace/webapp/node_modules/selenium-standalone/.selenium/geckodriver/0.23.0-x64-geckodriver.gz

npm ERR! Test failed.  See above for more details.
+ stop_xvfb
+ '[' true == true ']'
+ killall Xvfb
make: *** [Makefile:114: web_components_test] Error 1

**Comment by KyleJu** [comment]
cc @past. @foolip do these error messages ring a bell?

**Comment by foolip** [comment]
@KyleJu I haven't seen this error before, but I see "selenium-standalone installation starting" twice in the logs and that seems suspect. The first install succeeds, and then presumably some file is read-only and makes the second install fail.

Can you tell why install is happening twice?

**Comment by KyleJu** [comment]
Yea the issue is indeed with Selenium, chromedriver and geckodriver being installed twice, however I am not able to reproduce it locally...

These lines happened twice
```
selenium install:
from: https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
to: /usr/local/google/home/kyleju/wpt.fyi/webapp/node_modules/selenium-standalone/.selenium/selenium-server/3.141.59-server.jar
---
chrome install:
from: https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
to: /usr/local/google/home/kyleju/wpt.fyi/webapp/node_modules/selenium-standalone/.selenium/chromedriver/2.43-x64-chromedriver
---
firefox install:
from: https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
to: /usr/local/google/home/kyleju/wpt.fyi/webapp/node_modules/selenium-standalone/.selenium/geckodriver/0.23.0-x64-geckodriver

```

**Comment by KyleJu** [comment]
Digging into it more - the difference between CI and running locally is [`sudo -u browser npm test`](https://github.com/web-platform-tests/wpt.fyi/blob/75fd16bdd086ff29459c0fd41fe8e86908af5347/util/wct.sh#L26), which reinstalls `selenium-standalone` again on CI. `npm test` runs just fine locally.

**Comment by KyleJu** [comment]
I am pinning it down to an issue with `wct`. It seems to me that when it does `npm install` on `wct-local`, the script installs selenium automatically. When it tries to run `wct --local chrome && wct --local firefox`, it fails the installation check and tries to download it again on CI.
