### ISSUE TITLE
Uploading wpt report from real runs get empty report

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt.fyi#2724]
When upload wpt report from a real run, e.g. https://staging.wpt.fyi/api/runs?run_id=5567202187018240, the report uploaded is always empty. And when uploading such report, the response from upstream is 200 OK, and it did give the run id.
log as below:
2021-12-21 20:11:30,749 - Successfully uploaded wpt report with response: Task 5347420657418240 added to queue

But if I use a small file, use the same upload_report function, I am able to create a report successfully, e.g. https://staging.wpt.fyi/api/runs?run_id=6306164329414656.

**Comment by KyleJu** [comment]
@foolip any insights here?

**Comment by WeizhongX** [comment]
Kyle, I just checked the result from wpt-uploader. Looks like it
successfully uploaded a report? Can you help check? The log is as below. I
opened the link, and it looks like the report is there. I am not sure why
it is not the same as I tested locally.

2022-01-05 11:57:35,044 - Successfully uploaded wpt report with
response: Task 5432590127333376 added to queue
2022-01-05 11:57:35,044 - Report uploaded to
https://staging.wpt.fyi/api/runs?run_id=5432590127333376

**Comment by KyleJu** [comment]
> https://staging.wpt.fyi/api/runs?run_id=5432590127333376

Yea looks like the run is uploaded https://staging.wpt.fyi/results/?run_id=5432590127333376. How did you test it locally?

**Comment by WeizhongX** [comment]
Just run third_party/blink/tools/wpt_upload.py.

If this works correctly, maybe we can keep monitoring it to see if it will
be successful next time.

**Comment by WeizhongX** [comment]
Looks like there is no issue here, let's close this bug now.
