### ISSUE TITLE
realpath dependency is not documented

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2743]
@argyleink ran into this trying to get a local setup working on macOS. We use `realpath` in some scripts and the failure mode when following the README is pretty confusing if `realpath` isn't present.

We could document this dependency, or remove the need for it with some workaround.

**Comment by KyleJu** [comment]
Notes that the `realpath` issue was resolved by installing `coreutils` through brew but there should be a better fix

**Comment by ranashayan836-lang** [comment]
https://github.com/web-platform-tests/wpt.fyi/pull/2748
