### ISSUE TITLE
wpt.fyi fails to count subtests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#2759]
For example, see [this](https://wpt.fyi/results/webaudio/the-audio-api/the-audiocontext-interface/audiocontext-suspend-resume.html?sha=fdb441a036fae9246b9f7348778a41e2d233f5c5&label=master&label=experimental&product=chrome&product=firefox&product=safari) result view.

The UI says:

> Showing 33 subtests from master test runs from revision fdb441a

It also shows 40 subtests below that.

**Comment by foolip** [comment]
That's fascinating, thanks for reporting! @KyleJu can you tell where we get these numbers from? Maybe it's just the max number of subtest in any run?

**Comment by foolip** [comment]
I'm pretty sure the code that take the union of subtests for display only runs when actually viewing subtest results, and depends on loading the subtest data, which is [this](https://storage.googleapis.com/wptd/78da752cb927e5cae3c7f5d6af75376a66ad4c3a/edgechromium-100.0.1169.0-win-10.0-a256d5d80c/webaudio/the-audio-api/the-audiocontext-interface/audiocontext-suspend-resume.html) and 3 other files in this case.

To get consistency here wpt.fyi and get the subtest counts right even at a directory level, wpt.fyi would have to take the union of all subtests. Going through the search cache that might be possible, but not with the fast path we're still using when there's no query.

This is yet another situation where the backend storage model doesn't really work.

**Comment by DanielRyanSmith** [comment]
I've been taking a look at this issue. It seems that these subtest numbers are referencing the `legacy_status` attribute described here:
https://github.com/web-platform-tests/wpt.fyi/blob/5cf03758fa20741b1de0dba331c5cc332d6993b9/shared/models.go#L492-L497

The value of the subtest numbers are chosen by whichever browser has the highest `legacy_status` value among them here:
https://github.com/web-platform-tests/wpt.fyi/blob/5cf03758fa20741b1de0dba331c5cc332d6993b9/webapp/views/wpt-app.js#L387-L394

In the original example you linked @gsnedders, Chrome has the highest total at 33, which is also what is being displayed as the total for this test when we zoom out to view Chrome's total for this test when viewing [all of the tests for the-audiocontext-interface](https://wpt.fyi/results/webaudio/the-audio-api/the-audiocontext-interface?sha=fdb441a036fae9246b9f7348778a41e2d233f5c5&label=master&label=experimental&product=chrome&product=firefox&product=safari).

I'm not yet certain where this number is derived. Perhaps this number originally reflected something different than it currently does. The description of `legacy_status` gives a possible explanation of why a good number of the subtests views are off by +1, as it says that the total is counted such that the actual test counts as 1 and each subtest also counts as 1. However, this does not answer why the above example is so wrong. This will likely need to be handled via a different approach if we are to accurately show expected numbers here.
