### ISSUE TITLE
Deploy 59b17e7 to production

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2769]
Previous deployment was https://github.com/web-platform-tests/wpt.fyi/issues/2741 (3924238)

Changelist 3924238... 59b17e7

Major changes:
- https://github.com/web-platform-tests/wpt.fyi/pull/2748 (may affect deploy scripts)
- https://github.com/web-platform-tests/wpt.fyi/pull/2754
- https://github.com/web-platform-tests/wpt.fyi/pull/2744
- https://github.com/web-platform-tests/wpt.fyi/pull/2768
- https://github.com/web-platform-tests/wpt.fyi/pull/2772 
- https://github.com/web-platform-tests/wpt.fyi/pull/2773
- https://github.com/web-platform-tests/wpt.fyi/pull/2775
- https://github.com/web-platform-tests/wpt.fyi/pull/2774

https://github.com/web-platform-tests/wpt.fyi/pull/2772)

This push is happening for the Interop 2022 launch.

Pushing all three services - webapp, processor, and searchcache.

**Comment by KyleJu** [comment]
The new release [rev-7ce1e155](https://rev-7ce1e155-dot-wptdashboard.uc.r.appspot.com/) in live. The traffic will be directed on 8PT Feb 22

**Comment by foolip** [comment]
@KyleJu we're postponing the Interop 2022 launch, so let's _not_ redirect any traffic today.

**Comment by foolip** [comment]
We've decided on 9am Feb 24 (tomorrow) as the new launch date.

**Comment by KyleJu** [comment]
The latest release, rev-8c07c7e0 is live on prod.

**Comment by KyleJu** [comment]
https://rev-59b17e75-dot-wptdashboard.uc.r.appspot.com. 59b17e75 has been deployed

**Comment by foolip** [comment]
I have done the traffic split so this is done.
