### ISSUE TITLE
[Interop 2022] hardcode links not working for staging instance

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2770]
[All hardcode links](https://github.com/web-platform-tests/wpt.fyi/blob/7ce1e1551e2377acb8abcbe2819235cdc443c07c/webapp/components/interop-2022.js#L24) will not work for any staging instance because they are refer to the prod. E.g.
![Screen Shot 2022-02-21 at 4 04 23 PM (2)](https://user-images.githubusercontent.com/8611520/155040678-3904c8de-04d2-4ddc-a14f-dc125b0233f8.png)

In the process of testing the release candidate above, the `href` to the test-result view points to the wpt.fyi prod, where interop 2022 isn't live yet.

**Comment by KyleJu** [comment]
#2744

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt.fyi/pull/2772 to fix the links. Let's not include this in the prod push today though.
