### ISSUE TITLE
Improve gridline ticks on Interop 2022

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#2776]
https://staging.wpt.fyi/interop-2022's graphs look not great currently:

![Screenshot of Interop 2022 graph](https://user-images.githubusercontent.com/176218/155563767-3d9a67f6-4b84-45a4-a35f-3a9d5a77b135.png)

Having "Jan-2022 Jan-2022 Jan-2022 Jan-2022 Feb-2022 Feb-2022 Feb-2022" as ticks is very… not helpful. 

https://developers.google.com/chart/interactive/docs/datesandtimes#formatting-axis,-gridline,-and-tick-labels makes it sound like we probably want something like:

```js
          gridlines: {
            count: -1,
            units: {
              months: {format: ['MMM-YYYY']},
              days: {format: ['dd-MMM-YYYY']},
            }
          },
```

**Comment by KyleJu** [comment]
@foolip

**Comment by foolip** [comment]
@gsnedders this is what I see on https://staging.wpt.fyi/interop-2022?feature=interop-2022-color in Safari right now:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/498917/156348231-392892f4-9f36-4e74-8a43-7be78107f406.png">

I would call that "not great" as well, but it doesn't match your screenshot. Can you reproduce this right now, and with what browser? Chrome, Firefox and Safari all look the same to me.

**Comment by foolip** [comment]
@gsnedders I see, you zoomed in on part of the graph. That does result in something pretty silly.

**Comment by foolip** [comment]
@gsnedders did you try your suggestion locally? I tried it and a bunch of variations, but didn't arrive at something I thought really fixes the problem well.

**Comment by DanielRyanSmith** [comment]
This has been addressed with the Interop 2023 UI design. Is it safe to say we can close this issue?

![Screenshot 2023-12-12 at 11 15 58 AM](https://github.com/web-platform-tests/wpt.fyi/assets/56164590/74da08df-95d4-4d73-befd-50a35c554fc6)

**Comment by gsnedders** [comment]
Yeah, even zooming in it seems fine now.
