### ISSUE TITLE
Deploy 237dc468 to production

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2785]
Previous deployment was https://github.com/web-platform-tests/wpt.fyi/issues/2769 (59b17e755cd60601fe05878040cd4e5dc03d2df7)

Changelist 59b17e755cd60601fe05878040cd4e5dc03d2df7...237dc468e0b819242063515f17d7fc2aeafa3844

Major changes:
- https://github.com/web-platform-tests/wpt.fyi/pull/2782
- https://github.com/web-platform-tests/wpt.fyi/pull/2783
- https://github.com/web-platform-tests/wpt.fyi/pull/2784

Pushing all three services - webapp, processor, and searchcache.

**Comment by foolip** [comment]
https://rev-237dc468-dot-wptdashboard.uc.r.appspot.com/interop-2022 is up now.

**Comment by foolip** [comment]
I've tried it a bit and think it's ready for traffic splitting to deploy at 9am PT.

**Comment by KyleJu** [comment]
Push complete. Close this bug.
