### ISSUE TITLE
Nested TestRun metadata no longer present in PassRateMetadata

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#280]
This breaks https://staging.wpt.fyi/interop/

Several things should change:

- The redundant nested TestRuns data should be dropped - same style of TestRun and results should be used
- api/interop should be created
- interop.html should use the metadata it already has

**Comment by mdittmer** [comment]
@lukebjerring is this still an issue? If so, is it a regression? staging's interop view LGTM.

**Comment by lukebjerring** [comment]
All of the itemized changes have been implemented.
