### ISSUE TITLE
Clean up old WPT Interop tab 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2801]
The old interop tab became increasingly obsolete due to low usage and recently removed in https://github.com/web-platform-tests/wpt.fyi/pull/2768. Might be a good time to retire the `interop/` on the frontend and backend. Most importantly, it will improve the homepage load time.

**Comment by KyleJu** [comment]
@foolip

**Comment by foolip** [comment]
I think this is a good idea. Given a URL like https://wpt.fyi/interop/html?label=master&label=experimental&aligned we can replace it with an explanation that the feature is gone, with links to these views to show something similar:
- [`count:0(status:ok|status:pass)`](https://wpt.fyi/results/html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=count%3A0%28status%3Aok%7Cstatus%3Apass%29)
- [`count:1(status:ok|status:pass)`](https://wpt.fyi/results/html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=count%3A1%28status%3Aok%7Cstatus%3Apass%29)
- [`count:2(status:ok|status:pass)`](https://wpt.fyi/results/html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=count%3A2%28status%3Aok%7Cstatus%3Apass%29)
- [`count:3(status:ok|status:pass)`](https://wpt.fyi/results/html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=count%3A3%28status%3Aok%7Cstatus%3Apass%29)

**Comment by KyleJu** [comment]
Ideally we can delete both frontend and backend
