### ISSUE TITLE
Expose per-test execution time

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#282]
As https://github.com/web-platform-tests/wpt/issues/10026 the wptreport JSON has the execution time at a per-test level. Exposing this in the UI would be great, and even greater would be the ability to search for slow tests.

**Comment by foolip** [comment]
@lukebjerring did you close this accidentally? Test-level execution time is not yet exposed in the UI.

**Comment by lukebjerring** [comment]
Yes, I misinterpreted this as overall execution time. My mistake.

**Comment by foolip** [comment]
This would have helped in https://github.com/web-platform-tests/wpt/pull/19527 where I suspect the test is slow, but determining this required downloading the full report and reading the JSON manually.
