### ISSUE TITLE
Consider calling tests just "Test" instead of "Subtest"

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#29]
_From @foolip on September 30, 2017 20:15_

In http://wpt.fyi/speech-api/historical.html the first column says "Subtest". In testharness.js the terminology is that each of these is a test. The whole file is just a file, a way of grouping tests. This is the terminology that @jgraham uses and that I try to emulate :)

_Copied from original issue: w3c/wptdashboard#130_

**Comment by foolip** [comment]
I've come around to @jugglinmike's view on this, that in the face of multi-global tests where test names are not files names, "file is just a file" is wrong, and test+subtest is a better choice than ???+test.
