### ISSUE TITLE
Remove client-secret.json from packaged searchcache bundle

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt.fyi#2906]
During the deployment, the make target `package_service` is run.
For searchcache there's a special exception that copies all of the needed build files into a directory called wpt.fyi.
https://github.com/web-platform-tests/wpt.fyi/blob/506ee62856f373cba16f06ee568f2729807d4511/Makefile#L168-L175

However, in a prior step of the deploy.yml, client-secret.json for gcloud is written to the file system
https://github.com/web-platform-tests/wpt.fyi/blob/506ee62856f373cba16f06ee568f2729807d4511/.github/workflows/deploy.yml#L20-L23

During the copy in `package_service` client-secret.json is also copied. The service does not need it. That secret is only used for deploying the services.

Screenshot of the wpt.fyi folder for searchcache
![image](https://user-images.githubusercontent.com/7788930/179235799-acff31ca-b031-4c1e-b733-b4347f41b2e1.png)

**Comment by KyleJu** [comment]
Nice catch!!
