### ISSUE TITLE
Investigate consolidating renoavte and dependabot

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt.fyi#2948]
## Why
We currently leverage two systems for dependency upgrades: renovate and dependabot. Recently, there have been some problems where dependabot PRs cannot successfully finish their gates. (#2926, #2925, #2924)  This is due to the fact that GitHub has changed the behavior of Dependabot to be more secure. [Dependabot no longer has access to the same secrets as a normal pipeline](https://github.com/community/community/discussions/30588). That begs the question that why doesn't renovate enforce something like this too? Instead of having to wonder about the security of two systems doing the same thing, why not just consolidate to one and keep up to date with that single one.

**Comment by jcscottiii** [comment]
Regarding the outstanding work section, here are some data points

> a. Disable deploying completely for renovate/dependabot PRs

It is common to see this done. Examples:
1. [google-github-actions/deploy-cloud-functions](https://github.com/google-github-actions/deploy-cloud-functions/blob/ed0331bc9154bed7a142d0f1c93d9a672f091907/.github/workflows/integration.yml) - Explicitly skips deploying for dependabot builds
2. [worker-place/worker-place](https://github.com/worker-place/worker-place/blob/593d6c0f70e2887b0c6a62ad1770298f1f35e024/.github/workflows/heart.yml#L157) - explicitly skips deploying for dependabot builds
3. [DFE-Digital/apply-for-qualified-teacher-status](https://github.com/DFE-Digital/apply-for-qualified-teacher-status/blob/955ccc69fc8b79ea052da7ba7dec387ef18e052d/.github/workflows/deploy.yml#L153) - only deploys if a reviewer adds a tag to it.

> b. Investigate if there's a way to leverage [review deployments](https://docs.github.com/en/actions/managing-workflow-runs/reviewing-deployments) specifically for dependabot/renovate builds

A way to accomplish this option:

1. Create a new environment in the settings. (e.g. `dependabot-review`). Add required [reviewers](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#required-reviewers) to the environment
2. Add a section to the deploy.yml that looks specifically for dependabot. Add the environment to that section. 
3. Create credentials for dependabot to deploy with. Ensure that the service account credentials only have the roles needed to deploy. Not project wide admin. (This may already be done). Add the credentials under the dependabot section of the repo's secrets

**Comment by jcscottiii** [comment]
# Conclusion
I think dependencies with major version upgrades should be deployed. Maybe even some minor version upgrades too. Patch version upgrades are okay to be skipped. If we want this selective deployment, using 1) the example that adds a tag added by reviewers could be useful or 2) examining the [metadata (via steps.dependabot-metadata.outputs.update-type)](https://github.com/dependabot/fetch-metadata) of the dependabot PR could help. 

To keep things simple, we could just deploy on all dependency updates.

In whichever case we do decide to do, we should add reviewed deployments. This will prevent a bad dependency from automatically being built and deployed. A human has to OK the dependency version.

**Comment by jcscottiii** [comment]
Last week it was discussed whether we should keep both renovate and dependabot or consolidate to one. I added my notes to this thread here. FYI for @DanielRyanSmith @foolip @KyleJu @past

**Comment by past** [comment]
Thank you for the very thorough analysis and investigation, James! I agree with your conclusion, although it doesn't look like you have a recommendation regarding consolidating on renovate or dependabot? 

I feel slightly more inclined to move towards dependabot as it is a first-party bot, but I want to know what the rest of the team thinks.

**Comment by KyleJu** [comment]
+1 to @past's comment. I have gone through the third-party application approval process for `pyup` (another automatic dep update service), and the official reply is `I'm hesitant to add any third-party applications unless they've been vetted by the OSPO team.` Dependabot is recommended by the GoogleChrome GitHub organization.

Moreover, third-party applications add another layer of complexity to store credentials, since GitHub has to indirectly access to our GCP service account secret from another party. Overall, my gut feeling here is that the simpler, the better.

**Comment by jcscottiii** [comment]
Thanks for the feedback! I created https://github.com/web-platform-tests/wpt.fyi/issues/2959 to track the work.
