### ISSUE TITLE
Safari logos are missing on wpt.fyi staging

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#2955]
`safari-preview_64x64.png` logo is missing on staging but working on prod
![Screen Shot 2022-09-06 at 3 13 54 PM (2)](https://user-images.githubusercontent.com/8611520/188749801-7bc0bc65-d74a-4971-b203-bca1a051a91a.png)

After looking at the static folder, there only exists `safari_64x64.png` and all other Safari logos are missing.

**Comment by KyleJu** [comment]
@DanielRyanSmith

**Comment by DanielRyanSmith** [comment]
This might be related to the `cpy-cli` dependency that was updated last week. https://www.npmjs.com/package/cpy-cli
We use this to pull in the logos in the postinstall script: https://github.com/web-platform-tests/wpt.fyi/blob/f6202858228c99fb9f3227ecab742766beae9f93/webapp/package.json#L41
It looks like none of the logos that are renamed in this command are present in the `static` folder. I'll investigate and post an update.
