### ISSUE TITLE
Deploy 2081133 to production

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt.fyi#2966]
Previous deployment was #2949 (7ffc18a)

Changelist 7ffc18a...2081133
Major changes:
- Update module cloud.google.com/go/storage to v1.26.0 #2952
- Update module github.com/taskcluster/taskcluster/v44 to v44.20.2 #2953
- Update package.json (#2956)
- Use searchcache results if summary file is old format (#2920)
- Update Go dependencies (#2954) 
- Update dependency json-schema to 0.4.0 [SECURITY] (#2958) 
- Update golang.org/x/oauth2 digest to f213421 (#2960)
- Update dependency mocha to v10 (#2961)
- Align the node version between Docker and Makefile (#2962) 
- Remove Universal Analytics tracking (#2921) 

This push is happening as part of the regular weekly push.

Pushing all three services - webapp, processor, and searchcache.

- [x] Deploy the services
- [x] Flush the cache

**Comment by jcscottiii** [comment]
Thanks @KyleJu and @DanielRyanSmith for connecting and helping with me on my first deployment of this!

cc: @past

**Comment by DanielRyanSmith** [comment]
Thanks for handling this and the cache flush @jcscottiii 😊
