### ISSUE TITLE
Update Interop 2022 investigation effort scores

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2971]
In https://github.com/web-platform-tests/interop/issues/131#issuecomment-1248347439 we agreed to bump the score of the viewport investigation effort to 60%. This is the first time we have a (non-zero) score for an investigation effort, so code needs to be written to integrate it into the graphs over time.

**Comment by DanielRyanSmith** [comment]
This bug has been taken care of
