### ISSUE TITLE
Feature Request: Alert when wpt score goes down

### ISSUE THREAD

**Issue by beaufortfrancois** [web-platform-tests/wpt.fyi#2972]
I just received a [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1365302) regarding a regression in web platform tests as part of Interop 2022 and I thought it would have been great if I received some kind of notification as soon as chrome score was regressing so that we could had a chance to look at it earlier than later.

I bet this would help developers and users in this continuous effort that is interoperability.

**Comment by foolip** [comment]
I see there's a previous request for subscription in https://github.com/web-platform-tests/wpt.fyi/issues/1744.

I'll close as dupe and add my own +1 to that issue.
