### ISSUE TITLE
view=subtest is added to URLs where it doesn't do anything

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3011]
https://wpt.fyi/runs redirects to https://wpt.fyi/runs?label=master&from=2022-10-21T00%3A00&view=subtest, but the `view=subtest` bit doesn't do anything. @DanielRyanSmith can you take a look at not adding this, to add it only for `/results`?

**Comment by DanielRyanSmith** [comment]
Yes, I can take a look.

**Comment by Mir-SA** [comment]
Hi, I would like to work on this issue. 
Some doubts -
1. this issue requires removing the `view` param from `runs/` route or from every url it isn't being used?
2. should this param(view) be added to `results/` route as well? because after removing aligned param it seems to fallback to `view=subtest` so, basically make it a default?

**Comment by Mir-SA** [comment]
> As far as I know, this is the only route that the view param is added but is not used, but it should not display in any route except for the results/ route.

Got it.

> Ideally, this param should only display on pages where it is possible to use either the `interop` or `subtest` view param. For reference, the `interop` view is possible when viewing a search result that involves a label with "interop" in its name. For example: https://wpt.fyi/results/css/css-values?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-mathfunctions

It seems I misinterpreted original comment as removing it from `/runs/` and add it to `/results`/ instead. But this example makes it more clear what it's use case is.

I've raised the PR for it. The param was being set with conditionals in `components/test-runs-query.js`.
Do check it and let me know your thoughts.

**Comment by DanielRyanSmith** [comment]
Closing this for now. Thanks for the help @Mir-SA!
