### ISSUE TITLE
Interop 2022 dashboard is broken

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3012]
Reported by @gsnedders on matrix chat, it's blank and there's this console error:

> [Error] Failed to load resource: Origin https://wpt.fyi/ is not allowed by Access-Control-Allow-Origin. Status code: 503 (countUp.js, line 0)

I can repro the blank (nothing but header) page in Safari, and in Chrome if I disable the cache in DevTools.

@DanielRyanSmith can you investigate?

**Comment by KyleJu** [comment]
I cannot reproduce it on Chrome or Safari. Have you tried it @DanielRyanSmith?

**Comment by DanielRyanSmith** [comment]
Hmm, I'm seeing the page (https://wpt.fyi/interop-2022) as intended in Safari and Chrome with cache disabled. Are there any additional steps needed to reproduce?

**Comment by jcscottiii** [comment]
Also another issue to look into: https://github.com/mjackson/unpkg/issues/343
