### ISSUE TITLE
Upgrade python version

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt.fyi#3032]
Currently, we are using python 3.7 in the results processor [Dockerfile](https://github.com/web-platform-tests/wpt.fyi/blob/207813b3ed18bae81068934caa478daffd782d36/results-processor/Dockerfile). Should consider upgrading soon because it will be [EOL](https://endoflife.date/python) in June 2023.

When we do, we also need to update the local Dockerfile python version as well. https://github.com/web-platform-tests/wpt.fyi/blob/a5620f01d5318199093fe5e3f21e317115c88f31/Dockerfile#L18 for local development.

Other places that need updates:
- [README](https://github.com/web-platform-tests/wpt.fyi/blob/7198502326ce826753a3140955b093188ef8c3fa/results-processor/README.md) references
- [Makefile](https://github.com/web-platform-tests/wpt.fyi/blob/68eab45e1ce02f3b9a3a8015efa73af024d23c94/Makefile) target

**Comment by past** [comment]
Shouldn't we upgrade the local Dockerfile as well just for the necessary testing of the changes? If so, we are constrained by the golang:1.19-buster image that we are using, which doesn't carry anything above 3.7.

**Comment by jcscottiii** [comment]
Whoops. Good catch. I referenced the wrong service in my initial description. The results processor [Dockerfile](https://github.com/web-platform-tests/wpt.fyi/blob/main/results-processor/Dockerfile#L21) uses python 3.7. Not searchcache (uses only Go). I have updated the description.

**Comment by jcscottiii** [comment]
Also, I see what you mean about the local Dockerfile. I made one more edit.

**Comment by past** [comment]
Thanks! Also [results-processor/tox.ini](https://github.com/web-platform-tests/wpt.fyi/blob/main/results-processor/tox.ini#L2) should be updated.

**Comment by past** [comment]
After #3180 Python is now at 3.9, which will be [EOL](https://endoflife.date/python) in October 2025. Let's file a followup for further upgrades.
