### ISSUE TITLE
Access wpt raw data?

### ISSUE THREAD

**Issue by amirian28** [web-platform-tests/wpt.fyi#307]
Hi folks,

Is there a way to access the data that wpt.fyi/results provides in a raw format? I.E. json, csv, etc? This is a great data source, and I'm trying to see if there's a way for me to utilize the tests you've already run instead of trying to run it on my local.

Thanks, and thanks for providing this great resource!

Cheers,
Ariana

**Comment by lukebjerring** [comment]
Hi Ariana,

We have a JSON endpoint https://wpt.fyi/api/runs which lists `TestRun` entities. They have a field `raw_results_url` which is the full WPT report output, before it is pre-processed by our pipeline.
(We also have a singular endpoint. See https://github.com/web-platform-tests/wpt.fyi/tree/master/api for some docs)
 
e.g. https://wpt.fyi/api/run?product=chrome

    {
      "browser_name": "chrome",
      "browser_version": "69.0.3464.0 dev",
      "os_name": "linux",
      "os_version": "16.04",
      "revision": "2d497c444f",
      "full_revision_hash": "2d497c444f06c7348b1e6322ec8804df69d54c59",
      "results_url": "https://storage.googleapis.com/wptd/2d497c444f06c7348b1e6322ec8804df69d54c59/chrome-69.0.3464.0_dev-linux-16.04-ea811ea6d7-summary.json.gz",
      "created_at": "2018-06-21T13:46:25.866923Z",
      "raw_results_url": "https://storage.googleapis.com/wptd-results/2d497c444f06c7348b1e6322ec8804df69d54c59/chrome_69.0.3464.0_dev_linux_16.04_ea811ea6d7/report.json"
    }

The data should be a public bucket - let me know if this covers your needs.

**Comment by amirian28** [comment]
Hi Luke,

This is exactly what I was looking for --- thanks for the pointer. I seem to be able to download the examples OK, so if I run into any problems here on out I'll let you folks know. 

Much appreciated,
Ariana
