### ISSUE TITLE
Expose the status of results processing queue as a public API

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#308]
During a chat with @jugglinmike , he asked if there was any way to see the status of the queue. AppEngine has a dashboard, but it's not publicly visible. It'd be kinda cool if we can have a publicly readable API of the queue status (which we can also use for monitoring).

**Comment by Hexcles** [comment]
Sadly this proves more difficult than I thought.

Although the GCP dashboard has a UI to show each individual task in the queue, there's no such API available; the API only allows us to get stats about the whole queue: https://godoc.org/google.golang.org/appengine/taskqueue#QueueStats

Apparently getting info about individual tasks is part of the v2 CloudTasks API: https://godoc.org/cloud.google.com/go/cloudtasks/apiv2beta3

But we'll have to wait until #983 .

**Comment by lukebjerring** [comment]
The /api/status endpoint was added, so I believe this is fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1432
