### ISSUE TITLE
Sort "Recent Runs" by commit date

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt.fyi#310]
Currently, [the "Recent Runs" page](https://wpt.fyi/test-runs) lists results grouped by revision and orders these groups according to the date of the most recent upload. However, for many visitors to wpt.fyi, the moment that a particular result set was uploaded is not as relevant as the date of the revision under test.

Because results may be uploaded out of order\*, this sorting method produces a listing which does not reflect the revision dates. This is why on wpt.fyi today, the results for the Safari and Edge browsers appear to have been collected sporadically:

![screenshot from 2018-06-21 13-47-43](https://user-images.githubusercontent.com/677252/41736205-d7a3379e-7559-11e8-820e-c71df7d6a750.png)

What would it take to update the UI to sort these rows according to revision date?

\* - There are two main causes of this in practice.

The first is due to differences in duration of results collection. Edge and Safari require approximately 13 hours, while Chrome and Firefox require less than 4. When Edge and Safari results are uploaded, the relevant row is moved to the top of the listing, above revisions that have been tested with Firefox and Chrome in the time since.

The second cause is recovery from intermittent failures. When a test collection attempt fails, we diagnose the issue and manually re-trigger the process at a later date. We report the results for these manually-rescued attempts long after subsequent collections have completed successfully. The "sort by upload time" heuristic causes these results sets to be displayed at the top of the listing.

**Comment by Hexcles** [comment]
@lukebjerring and I were actually discussing this very problem just now.

Due to some technical complexities of using commit date (it'd require a checkout; not impossible, but a bit more complicated), we were considering sorting by the test start time (`run_info.test_start` in the report) instead. WDYT?

**Comment by jugglinmike** [comment]
I think that would work! An important factor is the way we consolidate partial result sets: [we use the earliest `test_start` time and the latest `test_end` time](https://github.com/web-platform-tests/results-collection/blob/1e9a26f293b55d8cea2bbe2d311d180b6d7df8ce/src/scripts/upload-wpt-results.py#L124-L130).  That means that even if we "rescue" a failed build many days later, the reported `start_time` will still describe the time testing began (which roughly corresponds to the date of the revision).

This would not work for cases where we needed to re-start a trial "from scratch," but that has been rare enough that this approach should suffice.
