### ISSUE TITLE
Make circle labels more consistent in interop 2023

### ISSUE THREAD

**Issue by boazsender** [web-platform-tests/wpt.fyi#3114]
Thinking it would be helpful to move the labels for the big circle to a consistent relative location to the circle they label, and to change them to use the same style. Here's a quick mockup:
![image](https://user-images.githubusercontent.com/122117/214978171-3cedbd46-bf33-439b-a780-420f1a912da2.png)

**Comment by boazsender** [comment]
Would also be great to add a footnote explaining how the interop score is calculated to the interop score. Could read something like: "The interop score is the percentage of WPT tests that pass in all three engines."

**Comment by jensimmons** [comment]
Hey Boaz, can you remove the screenshot of the whole thing? Just post the circle part — the part needed to talk about this.

**Comment by boazsender** [comment]
Sure thing!: 
![image](https://user-images.githubusercontent.com/122117/214978146-fbb17811-43cd-420e-84ae-c0ed774d5756.png)

**Comment by boazsender** [comment]
Sure thing, just updated it.

**Comment by jensimmons** [comment]
I just tried a couple different options. 

Here's the current design on the left, with the idea of putting the browser circles on top, and project circles on bottom. The labels are the same — on the outside. 

<img width="1105" alt="Screenshot 2023-01-26 at 7 19 08 PM" src="https://user-images.githubusercontent.com/108474/214979334-f3f880bc-93d9-43d7-be59-344084f7a4d2.png">

**Comment by jensimmons** [comment]
Here I tried putting all the labels on the bottom — with the 2 variations of browser circles on top vs project circles on top.

<img width="1206" alt="Screenshot 2023-01-26 at 7 20 41 PM" src="https://user-images.githubusercontent.com/108474/214979509-a2fe258e-a3a3-4c8f-b551-934399fad705.png">

**Comment by jensimmons** [comment]
And lastly, for the sake of being complete, I did the same thing as just above, but with all the labels on above the circles. (I don't like this.)

<img width="1220" alt="Screenshot 2023-01-26 at 7 21 37 PM" src="https://user-images.githubusercontent.com/108474/214979628-d789ef11-3c70-438f-8ff8-31bae75d8825.png">

**Comment by jensimmons** [comment]
I believe we should do one of these three options — A, B, or C. 

Whichever we choose, I just want to make sure it's possible to take a screenshot of one row (cropping out the other), so there needs to be just enough space to do so.

<img width="1603" alt="Screenshot 2023-01-26 at 7 25 12 PM" src="https://user-images.githubusercontent.com/108474/214980013-b6ff6d7b-0838-471b-ab56-ca4f93ef8d82.png">

**Comment by jgraham** [comment]
FWIW I think my order of preference is A B C, but I really prefer the Interop and Investigation scores being top-level and the browser scores on the next line (and I think the inverted pyramid "feels" unstable, which isn't the right vibe at all), so I can live with A or B, but have a strong preference to avoid C.

**Comment by boazsender** [comment]
My strong preference is for B or C due to the consistent placement of the labels, which I believe make the scores more legible. Between B and C, I prefer B.

**Comment by foolip** [comment]
I have to say that visually I prefer what we have, which is closest to option A. Nobody has commented on the inconsistency of the top labels being bold and capitalized, but that consistency might make it clearer that all are labels.

I could live with either A, B or C though.

**Comment by jensimmons** [comment]
I like B best, I do think it adds clarity to what those top numbers represent. My second choice is A. I agree the inverted triangle seems weird. 

But mostly, I just want us to lock it in on Tuesday, so we can all reshoot our screenshots on Wednesday, and stage our blog posts.

**Comment by jensimmons** [comment]
> I have to say that visually I prefer what we have, which is closest to option A.

Option A is _literally_ what we have now. I took a screenshot and left it unchanged. (Oh wait, maybe I added a bit more space between the two rows.) 

Boaz bolded the browser text in the top drawing, but I don't think that's needed. It's a bit ugly, imho. I did not retypes anything in the drawings I created. I just copy & pasted screenshots, cropping them in different ways and moving them around.

**Comment by jgraham** [comment]
So it sounds like everyone's happy with B, and that isn't true of the other options, so let's do B.

cc @DanielRyanSmith

**Comment by foolip** [comment]
> > I have to say that visually I prefer what we have, which is closest to option A.
> 
> 
> 
> Option A is _literally_ what we have now. I took a screenshot and left it unchanged. (Oh wait, maybe I added a bit more space between the two rows.) 

Indeed, the space is what I was thinking of.
