### ISSUE TITLE
Sort functionality for Interop dashboard

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/wpt.fyi#3117]
@foolip had the idea a while ago to add little triangles (or other UI) to allow people to sort by each column of the data tables. So — sort alphabetically by area name (the default, and as it is now). Sort by % number order for each of the three browsers. Or sort by % number order for Interop score.

It'd be especially helpful to be able to quickly sort and see what's in most need of work for a particular browser. Anyone could sort and see the order of most-interoperable to least-interoperable.

I'd love it if this is possible. I do not believe it's a blocker to launching. We could always add the functionality later.

**Comment by foolip** [comment]
Oh right, I forgot about this! I think this would be very useful, whether looking for how best to improve an individual browser's score, or the overall interop score. cc @DanielRyanSmith

**Comment by nt1m** [comment]
With PR #3125 merged, pasting this snippet in the console:

```
[...document.querySelector("interop-dashboard").shadowRoot.querySelectorAll("th")].forEach(n => n.addEventListener("click", (e) => {
  let index = [...e.target.closest("thead > tr").querySelectorAll("th")].findIndex(node => n == node);
  let tbody = e.target.closest("table").querySelector("tbody");
  let bodyItems = [...tbody.querySelectorAll("tr")];
  bodyItems.sort((a, b) => {
    let aContent = a.children[index].textContent;
    let bContent = b.children[index].textContent;
    if (isNaN(parseFloat(aContent)))
      return aContent.localeCompare(bContent);
    return parseFloat(aContent) > parseFloat(bContent);
  });

  tbody.textContent = "";
  tbody.append(...bodyItems);
}));
```

works. 

Perhaps it would be possible to integrate such code into a component.

Worth noting that `:has()` makes it awkward with`aContent.localeCompare(bContent);`, since it will always appear first heh.

**Comment by DanielRyanSmith** [comment]
I currently don't have time to implement this, but if anyone is passionate about adding the functionality and wants to go for it, I am available to review any PRs as needed. 🙂

**Comment by jensimmons** [comment]
I could really use this functionality this week! Still wishing for it.

**Comment by foolip** [comment]
Integrating the sort JS would be easy, but I'm not sure how to trigger it. There's no obvious place to place little arrows.

**Comment by nt1m** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1795135/224392059-19a5a063-a5c6-41e0-846b-b4dc528a2ed1.png">

This is an example from Firefox where the first column is currently sorted in ascending order.

**Comment by racheljay** [comment]
Hello! I'd like to take a look at this. I have some clarifying questions:
1. Just to make sure I'm looking at the right place, I assume all changes will need to be made in the `InteropDashboard` class in `interop.js`. Is that correct?
2. Is there an existing component that can be used for the arrow? Or will a new one need to be made?
3. I assume we want to order data in ascending order, but is there a need to also sort in descending order?

**Comment by nt1m** [comment]
Thanks for your interest!

> Just to make sure I'm looking at the right place, I assume all changes will need to be made in the InteropDashboard class in interop.js. Is that correct?

Yes `InteropDashboard` inside the `interop.js` file is the right place, all the `<table>` markup in there is for the tables that are shown on https://wpt.fyi/interop-2023

> Is there an existing component that can be used for the arrow? Or will a new one need to be made?

There is one that is used on the homepage of wpt.fyi, but it might not fit nicely in the table header given the limited amount of space. I would personally suggest to just set a class name on the `<th>` that is associated with selected column (by default the "Focus area"), and use CSS to add the arrow.

> I assume we want to order data in ascending order, but is there a need to also sort in descending order?

Ideally, clicking on an unsorted column would initiate sorting in ascending order, then clicking on a sorted column would toggle between ascending/descending.

Though as an initial iteration, just ascending sorting is also good enough (like what the JS in the 3rd comment does).

**Comment by DanielRyanSmith** [comment]
Thank you @racheljay to taking care of this! I'm making some small UX changes around the implementation, but this functionality should be in production by next week. 🙂
