### ISSUE TITLE
Move components of interop dashboard to separate files

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt.fyi#3133]
Currently, almost all of the components used to display the interop dashboard are jammed into a single file, `webapp/components/interop.js`. This is making it increasingly harder to review and maintain. The components that exist in this file should be broken down and moved to separate files for organization purposes.

**Comment by himanshu007-creator** [comment]
hey, i would like to work on this issue

**Comment by KyleJu** [comment]
> hey, i would like to work on this issue

Feel free to get started. Let me know if you have any questions about the setup or testing!

**Comment by LeonardYam** [comment]
Hi, I would like to work on this issue. If I understood this correctly, we just need to:
1. Refactor each class into a separate component file
2. Ensure the appropriate components are being defined by `window.customElements.define()`

**Comment by DanielRyanSmith** [comment]
Hello @LeonardYam! Thanks for the inquiry. Yes, that's basically the gist of it. Hopefully it's relatively straightforward!
