### ISSUE TITLE
Interop dashboard's interop-data.json appears to be missing 2023 data, resulting in empty page

### ISSUE THREAD

**Issue by patrickangle** [web-platform-tests/wpt.fyi#3137]
As of this morning and having cleared my browser caches, the interop dashboard doesn't display any data for me. Looking in dev tools, it appears that the 2023 data is missing from `interop-data.json`, and thus can't be found to populate the page.

**Comment by DanielRyanSmith** [comment]
Thank you for reporting this @patrickangle. A fix has been deployed now. Can you check if https://wpt.fyi/interop-2023 for us to make sure this problem is no longer an issue?

**Comment by patrickangle** [comment]
Yep, looks good now! Thank you 😄
