### ISSUE TITLE
Interop investigation projects don't have their links in the dashboard

### ISSUE THREAD

**Issue by stof** [web-platform-tests/wpt.fyi#3140]
Quoted from the description on https://wpt.fyi/interop-2023 (emphasis is mine):

> Investigation Projects are group projects chosen by the Interop team to be taken on this year. They involve doing the work of moving the web standards or web platform tests community forward regarding a particularly tricky issue. The percentage represents the amount of progress made towards project goals. **Project titles link to Git repos where work is happening.** Read the issues for details.

However, those project titles are not links:

![image](https://user-images.githubusercontent.com/439401/216136529-234e2ec0-faab-430c-8878-fb7bf94f01b0.png)

I initially thought that maybe the new investigation projects have not yet created their git repos. But the links are also missing for previous investigation projects, which definitely have them:
![image](https://user-images.githubusercontent.com/439401/216136771-4ef3d182-2f0f-4542-a50c-ec1aa03b4c95.png)

**Comment by foolip** [comment]
The repos we could link to are:

https://github.com/web-platform-tests/interop-2023-accessibility-testing
https://github.com/web-platform-tests/interop-2023-mobile-testing

**Comment by foolip** [comment]
And the 2022 ones:

https://github.com/web-platform-tests/interop-2022-editing
https://github.com/web-platform-tests/interop-2022-pointer
https://github.com/web-platform-tests/interop-2022-viewport
