### ISSUE TITLE
Node.js test runner registration request

### ISSUE THREAD

**Issue by panva** [web-platform-tests/wpt.fyi#3144]
I'd like to request that the Node.js project could start uploading results of the limited WPT subset we execute. IIUC we require a username and a password to use in HTTP Basic Auth to submit to [`/api/results/upload`](https://github.com/web-platform-tests/wpt.fyi/blob/main/api/README.md#apiresultsupload).

I'm [preparing a daily job](https://github.com/nodejs/node/pull/46498) that checks out the `epochs/daily` branch and runs it using 4 versions of Node.js, the latest nightly build (experimental), the "current" release line and two of the latest "LTS" release lines (Active LTS and Maintenance LTS).

**Comment by past** [comment]
Thanks for working on this! I have sent you access credentials offline for the staging server. Let us know when you have a working pipeline.
