### ISSUE TITLE
"Failed to fetch test runs" on prod with many (38) labels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3149]
In https://github.com/web-platform-tests/interop/pull/273 I'm adding this link to all Interop 2023 tests:
[`label:interop-2021-aspect-ratio or label:interop-2021-flexbox or label:interop-2021-grid or label:interop-2021-position-sticky or label:interop-2021-transforms or label:interop-2022-cascade or label:interop-2022-color or label:interop-2022-contain or label:interop-2022-dialog or label:interop-2022-forms or label:interop-2022-scrolling or label:interop-2022-subgrid or label:interop-2022-text or label:interop-2022-viewport or label:interop-2022-webcompat or label:interop-2023-color or label:interop-2023-contain or label:interop-2023-container or label:interop-2023-cssborderimage or label:interop-2023-cssmasking or label:interop-2023-events or label:interop-2023-flexbox or label:interop-2023-fonts or label:interop-2023-forms or label:interop-2023-grid or label:interop-2023-has or label:interop-2023-inert or label:interop-2023-mathfunctions or label:interop-2023-mediaqueries or label:interop-2023-modules or label:interop-2023-motion or label:interop-2023-offscreencanvas or label:interop-2023-property or label:interop-2023-pseudos or label:interop-2023-url or label:interop-2023-webcodecs or label:interop-2023-webcompat or label:interop-2023-webcomponents`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms%20or%20label%3Ainterop-2022-cascade%20or%20label%3Ainterop-2022-color%20or%20label%3Ainterop-2022-contain%20or%20label%3Ainterop-2022-dialog%20or%20label%3Ainterop-2022-forms%20or%20label%3Ainterop-2022-scrolling%20or%20label%3Ainterop-2022-subgrid%20or%20label%3Ainterop-2022-text%20or%20label%3Ainterop-2022-viewport%20or%20label%3Ainterop-2022-webcompat%20or%20label%3Ainterop-2023-color%20or%20label%3Ainterop-2023-contain%20or%20label%3Ainterop-2023-container%20or%20label%3Ainterop-2023-cssborderimage%20or%20label%3Ainterop-2023-cssmasking%20or%20label%3Ainterop-2023-events%20or%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2023-fonts%20or%20label%3Ainterop-2023-forms%20or%20label%3Ainterop-2023-grid%20or%20label%3Ainterop-2023-has%20or%20label%3Ainterop-2023-inert%20or%20label%3Ainterop-2023-mathfunctions%20or%20label%3Ainterop-2023-mediaqueries%20or%20label%3Ainterop-2023-modules%20or%20label%3Ainterop-2023-motion%20or%20label%3Ainterop-2023-offscreencanvas%20or%20label%3Ainterop-2023-property%20or%20label%3Ainterop-2023-pseudos%20or%20label%3Ainterop-2023-url%20or%20label%3Ainterop-2023-webcodecs%20or%20label%3Ainterop-2023-webcompat%20or%20label%3Ainterop-2023-webcomponents)

This is a query for 38 labels, and it consistently fails to load like this:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/498917/217187908-442af401-4c75-4664-827b-685efd7249d8.png">

Being able to run this query would be very useful when combined with `status:error` and similar to look for non-OK harness statuses.

@DanielRyanSmith can we tell from the logs why this is happening? Does it result in 38 unique queries and a huge join, which times out?

**Comment by KyleJu** [comment]
Fixed in prod. Future improvement in #3323
