### ISSUE TITLE
web component test components/test/test-run.html failure in Chrome 110

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#3152]
e.g. https://github.com/web-platform-tests/wpt.fyi/actions/runs/4117766043/jobs/7111874652

components/test/test-run.html » <test-run> » TestRun.prototype.* » timeFormat(iso string)
670
671  expected 'Jan 12 at 12:00 PM' to equal 'Jan 12 at 12:00 PM'

We will pin Chrome to 109 for a temporary workaround

**Comment by jcscottiii** [comment]
Thanks for creating this to track it!

**Comment by KyleJu** [comment]
Possible cause: https://bugs.chromium.org/p/chromium/issues/detail?id=1414553
