### ISSUE TITLE
webapp deployment is failing (but the build is still green)

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#319]
https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/397034462

```
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
2018/06/26 12:19:22 go-app-builder: Failed parsing input: parser: bad import "syscall" in google.golang.org/grpc/credentials/credentials_util_go19.go
```

This is happening on both master and PR jobs. cc @lukebjerring

**Comment by Hexcles** [comment]
Still can't reproduce locally.

The first failure on master was https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/396550762 (eb318d50547f31b8b0d76da0584c67aea7d50b02), but that commit didn't change Go code at all and the PR staging deployment was successful. Perhaps something happened in the dependencies.

**Comment by lukebjerring** [comment]
@mdittmer, is this the issue that you patched as part of the Makefile rule?

**Comment by Hexcles** [comment]
Don't know why but the issue is gone...
