### ISSUE TITLE
Interop: link to investigation area repos

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt.fyi#3198]
https://wpt.fyi/interop-2023 doesn't link anywhere for investigation areas. Since each investigation area has its own repo, it seems useful to link to them in the dashboard.

Active
https://github.com/web-platform-tests/interop-2023-accessibility-testing/
https://github.com/web-platform-tests/interop-2023-mobile-testing/

Previous
https://github.com/web-platform-tests/interop-2022-editing
https://github.com/web-platform-tests/interop-2022-pointer
https://github.com/web-platform-tests/interop-2022-viewport

**Comment by jensimmons** [comment]
Also #3140
