### ISSUE TITLE
Enable color-4 flag to see Gecko experimental Interop results for css-color?

### ISSUE THREAD

**Issue by svgeesus** [web-platform-tests/wpt.fyi#3206]
From [Firefox 111 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/111):

> CSS color functions `color()`, `lab()`, `lch()`, `oklab()`, and `oklch()` are now supported. These features are disabled by default and can be enabled by setting the preference `layout.css.more_color_4.enabled` to true. 

However, WPT experimental shows Firefox [failing a bunch of Interop 2022 and 2023 CSS Color tests](https://wpt.fyi/results/css/css-color?label=experimental&label=master&aligned), because this flag is not enabled when running them.

My informal manual testing (Nightly 113) shows a _lot_ of tests are currently passed when the flag is enabled. (failures are mostly things like not supporting `none` yet).

@jgraham would it be possible, on the [WPT.fyi Experimental](https://wpt.fyi/results/css/css-color?label=experimental&label=master&aligned) runs (**not** on Stable, yet) to enable this flag so we can see the actual test failures instead of a wall of red?

**Comment by svgeesus** [comment]
[Interop 2023 Color results](https://wpt.fyi/results/css?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-color%20or%20label%3Ainterop-2023-color)

**Comment by nt1m** [comment]
Seems like this should be enabled by default in Firefox Nightly in the mozilla-central repo, rather than here.

cc @emilio @tiaanl

**Comment by tiaanl** [comment]
Color features will be enabled by default in fx nightly very soon when this is landed:  https://bugzilla.mozilla.org/show_bug.cgi?id=1813481

**Comment by gsnedders** [comment]
Ever since https://github.com/web-platform-tests/wpt/pull/10443, `wpt` has downloaded channel-specific prefs from Mozilla-central that control what features are/aren't enabled; as such, this being disabled just follows from the fact they're still disabled in Nightly in mozilla-central.

**Comment by svgeesus** [comment]
> enabled by default in fx nightly very soon

Great, feel free to close this, then
