### ISSUE TITLE
Uploading to production server is slower than uploading to staging

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt.fyi#322]
When we first deployed parallel services for uploading results, we noticed a possible difference in upload durations. @Hexcles wrote via IRC:

> wow... that's interesting... the only difference I can think of is that the prod endpoint is loaded
>
> the upload endpoint is in the same service that serves the website
>
> but 30% is still quite a lot... especially given that we're using AppEngine auto scaling

We decided to wait for more data points to see if that was coincidental.

We have since uploaded results successfully 89 times, and a shallow analysis of the data (script included below) verifies that this difference is persistent:

    production { mean: 28.168539325842698, stdDev: 1.210775172406668 }
    staging { mean: 17.39325842696629, stdDev: 1.3707865168539328 }

Not sure what to make of this. Even though it's not an issue in practice (we're uploading once every 6 hours, so 10 seconds is a drop in the bucket), I figured that @Hexcles might be interested.

<details>
  <summary>Script used to collect the data</summary>

```js
'use strict';

const http = require('http');

function getJSON(url) {
  return new Promise((resolve, reject) => {
      http.get(url, resolve).on('error', reject);
    }).then((response) => {
      const { statusCode } = response;

      if (statusCode !== 200) {
        // consume response data to free up memory
        response.resume();
        throw new Error(`Request Failed.\nStatus Code: ${statusCode}`);
      }

      let rawData = '';
      response.setEncoding('utf8');
      response.on('data', (chunk) => { rawData += chunk; });
      return new Promise((resolve) => {
        response.on('end', () => resolve(rawData));
      });
    }).then((rawData) => JSON.parse(rawData));
}

function summarize(series) {
  const mean = series.reduce((all, next) => all + next, 0) / series.length;
  const variance = series.reduce((all, next) => all + (next - mean) ** 2, 0) / series.length;
  const stdDev = variance ** 0.5;

  return { mean, stdDev };
}

(async function() {
  const prod = [];
  const stage = [];

  for (let id = 1746; id < 1835; id += 1) {
    const data = await getJSON(`http://builds.wpt.fyi/api/v2/builders/4/builds/${id}/steps`);

    prod.push(data.steps[0].complete_at - data.steps[0].started_at);
    stage.push(data.steps[1].complete_at - data.steps[1].started_at);
  }

  const prodStats = summarize(prod);
  const stageStats = summarize(stage);

  console.log('production', prodStats);
  console.log('staging', stageStats);
}());
```

</details>

**Comment by Hexcles** [comment]
This is very interesting. Thanks again for the awesome report, Mike!

While 10 seconds in 6 hours are a drop in the bucket, 10 seconds also translate to almost 60% slower than staging. And with 89 times of upload and a standard deviation of <2 seconds, I think the number is statistically significant enough that warrants some attention.

Let me look into this.

**Comment by jugglinmike** [comment]
No problem, Robert. There was an error in my script. The value I originally reported as the standard deviation was actually the variance. So those averages are a little more precise than originally reported. I've corrected the numbers and the script in the description above.

**Comment by Hexcles** [comment]
I noticed that the buffer bucket was in the wrong region. I just changed it to multi-region US. Although I don't believe it would have such a significant impact on performance.

**Comment by foolip** [comment]
Is this still a problem?

**Comment by jugglinmike** [comment]
Here are the stats for the past 4 days (59 upload pairs, build IDs 2558 through 2617):

    production { mean: 29.135593220338983, stdDev: 2.070434549644304 }
    staging { mean: 18.52542372881356, stdDev: 5.289439213502244 }

Means are similar, though the variance has spiked. This isn't quite a problem, though. Just a possible inefficiency.

**Comment by foolip** [comment]
Do you always upload in the same order? @Hexcles, is it possible that GCS already having seen the file once would explain a difference? I know it's a different bucket, but... internal de-duping?

**Comment by jugglinmike** [comment]
Yes, we consistently upload to the production deployment first followed by the staging deployment second.

**Comment by lukebjerring** [comment]
Closing as will not fix.
