### ISSUE TITLE
wpt.fyi has a linkified (underlined) whitespace character after bug icon, for bugs-in-tests-themselves

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt.fyi#3224]
STEPS TO REPRODUCE:
1. Visit https://wpt.fyi/results/css/css-transforms/rotate?q=svg-rotate-angle-45
2. Look at the bug icon next to the test names.
3. (optional) try clicking on that bug icon, to see it with the link in the `:active` state 

ACTUAL RESULTS:
There's an awkward colorful `_` to the right of the bug icon; this is actually some `<a>`-underlined whitespace that trails the bug icon.  This is extra noticeable if you click on the bug icon, to make it `:active` or `:visited`.

EXPECTED RESULTS:
No such underlined whitespace.

Screenshot:
![image](https://user-images.githubusercontent.com/426803/227365211-5e2268e6-0d71-4def-b973-e82e7510b269.png)

**Comment by dholbert** [comment]
Here's a screenshot in Firefox's devtools, showing the whitespace node:
![image](https://user-images.githubusercontent.com/426803/227365697-57d6343c-6f0e-4935-9e89-f158d2d1ced1.png)

It's inside the `<a>` element, just after the `<iron-icon>` element.

For whatever reason, this whitespace node is not present (and hence this issue doesn't reproduce) for the bug icon that's in per-browser columns.  It's only there for the bug icon that's alongside the test name itself.

**Comment by dholbert** [comment]
Also, to be clear, this affects all browsers (I tested Firefox, Chrome, and Epiphany (WebKit-based browser on Linux).

**Comment by KyleJu** [comment]
Thanks for filing the issue! I added it to the backlog and hope to address it in the beginning of Q2
