### ISSUE TITLE
Deploy CI stage is skipped for main commits; staging environment not updating

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt.fyi#3237]
Due to the recent change to [skip the deploy step for PRs from forked repos](https://github.com/web-platform-tests/wpt.fyi/pull/3222), the commits to main from any pull request is also skipping this step, which means that our staging environment is not automatically updating. We'll need to investigate why this happens and find a way to avoid this step for forked repos but still run this step for commits to main.

CC @jcscottiii @KyleJu

**Comment by KyleJu** [comment]
I believe the issue is with specifying [pull_request](https://github.com/web-platform-tests/wpt.fyi/blob/d5a59b835730adef24f3f99077e3454bae338f40/.github/workflows/deploy.yml#L9) as a part of requirement:

`github.event.pull_request.head.repo.full_name == 'web-platform-tests/wpt.fyi`

**Comment by DanielRyanSmith** [comment]
@KyleJu you're right that this is the cause. I'm wondering the best way to word the line in that logic to still skip the step for forked repository PRs but still run the step for main commits. 🤔 I haven't looked deeply into it, but I will update if I find anything.

**Comment by jcscottiii** [comment]
I just put up a PR to hopefully address this
