### ISSUE TITLE
Differentiate "experimental" results

### ISSUE THREAD

**Issue by RByers** [web-platform-tests/wpt.fyi#333]
Test results from a browser with additional flags like Chrome's --enable-experimental-web-platform-features mean something pretty different than results that don't have that flag. I was confused recently to see tests passing on wpt.fyi for a feature I knew hadn't shipped yet (did it mean the tests were bad and always passing?).

Whenever we're testing a mode different from what end users get, I suggest we indicate that somehow in the browser label / icon. Eg. maybe instead of "Chrome 69" and the normal Chrome logo, we should use the yellow Chrome canary logo and say "Chrome 69-exp" with a tooltip/link that lists "--enable-experimental-web-platform-features".

Also ideally the main view would be consistent - probably in NOT showing any experimental results unless you click on an "experimental browser builds" link or something. I'm also OK with that being the default, as long as it's clear.

**Comment by Hexcles** [comment]
#331 should address the logo part. And we can have more UI bits (tooltips, etc.) to highlight the difference.

**Comment by Hexcles** [comment]
With #365 , all four browsers now have different logos for the experimental version.

**Comment by lukebjerring** [comment]
With respect to the flags, this ties in to #538, and otherwise, the UI now reflects the dev channel via icons, and also defaults to `stable` product runs, so I'm closing this.
