### ISSUE TITLE
Labeling directories

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3351]
For https://github.com/web-platform-tests/interop-2023-accessibility-testing/issues/44, it would be useful to be able to label directories, to be able to replace this query of multiple directories and one test: [`path:/accessibility or path:/accname or path:/html-aam or path:/wai-aria or path:/svg-aam or path:/graphics-aria or path:/graphics-aam or path:/dpub-aam or path:/html/dom/aria-element-reflection.html`](https://wpt.fyi/results/?label=experimental&label=master&aligned&q=path%3A%2Faccessibility%20or%20path%3A%2Faccname%20or%20path%3A%2Fhtml-aam%20or%20path%3A%2Fwai-aria%20or%20path%3A%2Fsvg-aam%20or%20path%3A%2Fgraphics-aria%20or%20path%3A%2Fgraphics-aam%20or%20path%3A%2Fdpub-aam%20or%20path%3A%2Fhtml%2Fdom%2Faria-element-reflection.html)

Labeling is currently done in [wpt-metadata](https://github.com/web-platform-tests/wpt-metadata) with support in the wpt.fyi UI to add labels to tests, but not directories.

Option 1: We already support linking a bug to a whole directory in wpt-metadata ([example](https://github.com/web-platform-tests/wpt-metadata/blob/3794a05315b45116293aae9f30800a793ee54ce4/css/css-grid/masonry/META.yml)) and it we could do the same for labels. https://github.com/web-platform-tests/wpt-metadata/pull/4303 is an example of what this would look like in wpt-metadata.

Option 2: We could support labels in WPT itself, via its META.yml files. That would make this similar to https://github.com/web-platform-tests/wpt.fyi/issues/372, which is about spec links extracted from WPT. @KyleJu is working on this now.

In either case, the idea is that `label:accessibility` would work as a search atom, and it would not be necessary to individually label all of the tests in each directory.

**Comment by foolip** [comment]
@cookiecrook did https://github.com/web-platform-tests/wpt-metadata/pull/4297, so no need for my draft https://github.com/web-platform-tests/wpt-metadata/pull/4303.

It looks from https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aa11y like this doesn't work in the search cache. @KyleJu can you help check how labels and bugs are different? Given that we have `triaged:chrome` which is based on bug links I guess the search cache does understand '*' as a wildcard for tests in some contexts, but not for labels?

**Comment by KyleJu** [comment]
> @cookiecrook did [web-platform-tests/wpt-metadata#4297](https://github.com/web-platform-tests/wpt-metadata/pull/4297), so no need for my draft [web-platform-tests/wpt-metadata#4303](https://github.com/web-platform-tests/wpt-metadata/pull/4303).
> 
> It looks from https://wpt.fyi/results/?label=master&label=experimental&aligned&q=label%3Aa11y like this doesn't work in the search cache. @KyleJu can you help check how labels and bugs are different? Given that we have `triaged:chrome` which is based on bug links I guess the search cache does understand '*' as a wildcard for tests in some contexts, but not for labels?

Wildcard has not been implemented in `label` yet, but it shouldn't be huge amount of work. Let me try to get to it at the end of this month. Thanks for bringing it to my attention :)

**Comment by KyleJu** [comment]
Note: we will go with option 1 proposed by the issue author. It includes supporting wildcards on the wpt.fyi UI and searchcache

**Comment by KyleJu** [comment]
Once https://github.com/web-platform-tests/wpt.fyi/pull/3447, this feature will be available in the next release
