### ISSUE TITLE
[WPT Test History] Create an API endpoint and document it

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#3352]
Create an API endpoint that serves WPT Dashboard Test History data and document it in https://github.com/web-platform-tests/wpt.fyi/blob/main/api/README.md.

Currently, the broken “show history” section pulls data from each run separately for each column that is displayed there. The page has to make hundreds of requests, basically one per red/green square. Ideally, we would want one API request per test, that serves the data for all subtests under this test with 

- one year of data (subject to change)
- four major browsers
- aligned & experimental runs

The request should be a GET request, with optional parameters. The server response should be JSON format with all necessary metadata. Both request and response format should be consistent with other APIs in  https://github.com/web-platform-tests/wpt.fyi/blob/main/api/README.md, in terms of naming, etc.

#1495

**Comment by DanielRyanSmith** [comment]
Work completed!
