### ISSUE TITLE
[WPT Test History]  Frontend dashboard design

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#3353]
Taken from https://docs.google.com/document/d/1qqYoqFoz6dGQUGzHNkBfCkw9XSgUdTemZMMacoiDhbY/edit?resourcekey=0-HX97-YSMa9KRscd5WN34sg. Have a basic sketch of what the frontend dashboard should look like, based on the user requirements in https://github.com/web-platform-tests/wpt.fyi/issues/1495. 

We can first focus on improving the existing design. Building on top of the existing "Show History" section - a big grid with a list of runs, but a larger view, more history with the aligned runs that date back to one or two years. 

Potentially, it could collapse long runs of the same result. A grid is easy-ish to understand, but would need to be collapsed when nothing changes for long stretches of time. 

Alternatively, since the history is potentially unbounded, we could explore a vertical layout. It could potentially be one column per browser, or all events interleaved.

**Comment by DanielRyanSmith** [comment]
Work completed!
