### ISSUE TITLE
Link to "these runs" not giving these runs

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#3370]
Looking at: https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-onerror.https.html?label=master&product=chrome%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari-171%20preview%5Bexperimental%5D&product=safari-172%20preview&product=safari%5Bstable%5D

Clicking the "Link" button gives me the normal dialog, but under "These runs" the URL it offers is: https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-onerror.https.html (note the lack of query parameters).

This happens with the above query in both Safari and Chrome.

My first guess would be this is a regression from #3350 (cc @jcscottiii @KyleJu).

**Comment by jcscottiii** [comment]
Taking a look now

**Comment by jcscottiii** [comment]
Can verify that #3350 caused the regression. Should have a fix shortly

**Comment by gsnedders** [comment]
Can we just revert https://github.com/web-platform-tests/wpt.fyi/pull/3350 and redeploy so this is fixed ASAP?

**Comment by KyleJu** [comment]
> https://wpt.fyi/results/webaudio/the-audio-api/the-audioworklet-interface/audioworkletnode-onerror.https.html

I reverted the deployment to a previously working instance. It should be fixed on prod now
