### ISSUE TITLE
Cleanup after new history timeline is complete

### ISSUE THREAD

**Issue by racheljay** [web-platform-tests/wpt.fyi#3451]
After the new test history timeline is complete some cleanup will be need to be done:

- [x] Remove `mock_history_data.json`
- [x] Remove feature flag to hide new history button
- [x] Rename "show new history" button to "show history"
- [x] Remove previous history grid version
- [x] Rename `new-test-results-history-grid.js` to `test-history-timeline.js`

**Comment by DanielRyanSmith** [comment]
All finished! Thanks again @racheljay!
