### ISSUE TITLE
Interop 2024: Switch to Chrome Canary

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3579]
Chrome for Testing has a Canary channel, and @DanielRyanSmith is working on setting this up in Taskcluster.

I'd like to suggest switching from Chrome Dev to Chrome Canary to the Interop 2024 dashboard. Switching at the start of the year means we can change the icons and not have to explain any score changes caused by a switch.

**Comment by foolip** [comment]
This will also affect Chrome for Android, as we should ideally run the same browser channel for desktop and mobile. I filed https://github.com/web-platform-tests/interop-2023-mobile-testing/issues/16 about that, not sure where to ask :)

**Comment by past** [comment]
@DanielRyanSmith is there anything left to do here?

**Comment by DanielRyanSmith** [comment]
This has landed with the release of the 2024 dashboard and can now be closed. 🙂
