### ISSUE TITLE
Unable to see test results of tests with query parameters

### ISSUE THREAD

**Issue by tkent-google** [web-platform-tests/wpt.fyi#362]
1. Open https://wpt.fyi/results/dom
2. Click ```interfaces.html?exclude=Node```

Expected:
Showing test results of ```interfaces.html?exclude=Node```

Actual:
The new page URL is https://wpt.fyi/results/dom/interfaces.html, and the page doesn't contain any test results.

**Comment by Hexcles** [comment]
The previous PR didn't fix the test. GitHub misunderstood my comment :)
