### ISSUE TITLE
Freeze the Interop 2023 dashboard

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3639]
Just like Interop 2022, we want to freeze the Interop 2023 dashboard.

The Interop Team's preference would be to freeze the dashboard at the end of January 2024, and not on Dec 31 as we've done previously.

@DanielRyanSmith I presume that freezing can be done in the same way as last year, but is there any problem with letting the data continue updating until the end of January?

**Comment by DanielRyanSmith** [comment]
> @DanielRyanSmith I presume that freezing can be done in the same way as last year, but is there any problem with letting the data continue updating until the end of January?

Should be no problem, although the grab is hardcoded to only display results until the end of December. Freezing the data at any point should be no issue. 🙂

**Comment by dbaron** [comment]
Has this freezing been done yet?  (I know of at least one set of tests that's been waiting to reland until the freezing happens; cc @josepharhar)

**Comment by KyleJu** [comment]
> Has this freezing been done yet? (I know of at least one set of tests that's been waiting to reland until the freezing happens; cc @josepharhar)

This has been completed by Daniel in https://github.com/web-platform-tests/wpt.fyi/pull/3706
