### ISSUE TITLE
Interpolate between color stops in Interop 2024 dashboard

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3694]
This was discussed within the Interop Team but I can't find an issue filed here.

Currently https://staging.wpt.fyi/interop-2024?stable looks like this:

<img width="526" alt="image" src="https://github.com/web-platform-tests/wpt.fyi/assets/498917/cc46617f-0325-4b31-8164-95b1e09b8ff4">

It's a stark difference in color between 73 and 75. In the past we've just been lucky that we didn't have two scores straddling the boundary point between colors in such an eye-catching way.

The suggestion is to instead interpolate between the colors, so that the difference score N and N+1 can never be very big.

cc @DanielRyanSmith

**Comment by DanielRyanSmith** [comment]
This PR is currently available: https://github.com/web-platform-tests/wpt.fyi/pull/3668

**Comment by foolip** [comment]
Oh right, I saw that but forgot! Now reviewed.

**Comment by DanielRyanSmith** [comment]
Completed with #3668, which will be landed in the next deployment.
