### ISSUE TITLE
Upgrade geckodriver to 0.21.0

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt.fyi#373]
I recently checked the wpt.fyi results for Firefox Nightly and saw those strange results:

https://wpt.fyi/results/webdriver/tests/get_element_property/get.py?labels=experimental

For a couple of element interaction commands we see a failure like "Failure message: assert 400 == 404" for the stale element tests.

We already fixed that with geckodriver 0.20.0:
https://github.com/mozilla/geckodriver/blob/release/CHANGES.md#changed-1

Which means that the version of geckodriver used for wpt.fyi results should be <0.20.0.

Can we please upgrade to 0.21.0?

CC'ing @jugglinmike, @andreastt, @jgraham

**Comment by whimboo** [comment]
Oh, and there is also the change for an empty response which we shipped with 0.21.0. Having the tests correctly run with the newest release of geckodriver should give us mostly green results for Firefox 63 now.

**Comment by whimboo** [comment]
With PR #316 the version constants have been moved out of the Makefile. Now I'm not sure where to actually bump the version of geckodriver. @lukebjerring could you help us please? Thanks.

**Comment by lukebjerring** [comment]
I was under the impression this was automated, but if not, @jugglinmike is your best bet to handle this.

**Comment by whimboo** [comment]
Ok. In case it's automated it looks like that a different executable is called. Maybe 0.21.0 is getting installed into a different path than `$(NODE_SELENIUM_PATH)geckodriver/` as the [Makefile](https://github.com/web-platform-tests/wpt.fyi/blob/master/Makefile#L88) looks into.

**Comment by jugglinmike** [comment]
Hi there!

As of today, most of the data displayed on wpt.fyi is collected from a separate project, [web-platform-tests/results-collection](https://github.com/web-platform-tests/results-collection). Here's a patch to update that project's version of Geckodriver to 0.21.0 https://github.com/web-platform-tests/results-collection/pull/585

**Comment by lukebjerring** [comment]
Note that the makefile's rules are only for the integration tests (of wpt.fyi itself); versions used to produce the results will be specified in https://github.com/web-platform-tests/wpt and https://github.com/web-platform-tests/results-collection

**Comment by whimboo** [comment]
I see. Thank you for that information.

**Comment by jugglinmike** [comment]
As expected, with Geckodriver 0.21.0, [that failure](https://wpt.fyi/results/webdriver/tests/get_element_property/get.py?sha=4273df6e12&labels=experimental) is [now passing](https://wpt.fyi/results/webdriver/tests/get_element_property/get.py?labels=experimental&sha=68318aca8a).
