### ISSUE TITLE
Unable to setup dev environment on Apple Silicon Macs

### ISSUE THREAD

**Issue by meelunae** [web-platform-tests/wpt.fyi#3737]
Hello! I am trying to run this project for local development on an Apple Silicon Mac (Specifically a MacBook Pro with an M3 Pro and 36GB of Unified Memory) but the script `./utils/docker-dev/run.sh` points out the lack of a linux/arm64/v8 image (which isn't that big of an issue since it just falls back to the linux/amd64 image through rosetta), but then fails during the creation of the user group in the Docker image. Logs of my execution are as follows:
```
[  2024-03-01 00:44:23  INFO  ]  Creating docker instance for dev server. Instance name: wptd-dev-instance
[  2024-03-01 00:44:23  WARN  ]  Found existing docker instance wptd-dev-instance. Remove?
Confirm (y/N): y
[  2024-03-01 00:44:23  INFO  ]  Stopping wptd-dev-instance...
wptd-dev-instance
[  2024-03-01 00:44:34  INFO  ]  wptd-dev-instance stopped.
[  2024-03-01 00:44:34  INFO  ]  Removing wptd-dev-instance...
wptd-dev-instance
[  2024-03-01 00:44:34  INFO  ]  wptd-dev-instance removed.
[  2024-03-01 00:44:34  INFO  ]  Starting docker instance wptd-dev-instance...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9b255d6575c1fe3990bdd41f71b2dbf14684021f7e495aafea13864c4bb417e9
[  2024-03-01 00:44:34  INFO  ]  Setting up local user
groupadd: GID '20' already exists
[  2024-03-01 00:44:34  INFO  ]  Ensuring the home directory is owned by the user...
chown: changing ownership of '/home/user/wpt.fyi/.git/objects/pack/pack-1321129db003e3ac855112c5d9d80ce0d0bacb96.rev': Permission denied
chown: changing ownership of '/home/user/wpt.fyi/.git/objects/pack/pack-1321129db003e3ac855112c5d9d80ce0d0bacb96.idx': Permission denied
chown: changing ownership of '/home/user/wpt.fyi/.git/objects/pack/pack-1321129db003e3ac855112c5d9d80ce0d0bacb96.pack': Permission denied
```
It seems that the issue could be removed through migrating to a predefined/hardcoded UID and GID for the Docker container that avoids conflicts rather than relying on the host user's GID. Is there anything I am missing? I have been trying to locate all chown occurrences inside the code, but even tho I managed to get past the issue of creating a GID that already exists, I still get the permission denied error. 
Do you have any pointers on where to look if I wanted to to fix these issues and get a functioning build for a macOS + arm64 environment?

Thank you very much!

**Comment by meelunae** [comment]
@KyleJu Sorry for pinging you on this issue, but do you have any idea on how to approach it so I can work on a PR? :) Thanks!

**Comment by KyleJu** [comment]
@meelunae Unfortunately it is a known issue on our side, https://github.com/web-platform-tests/wpt.fyi/issues/3196. The project needs to support a linux/arm64 docker image, but we haven't gotten to it yet. Do you have other machines to try it?

**Comment by meelunae** [comment]
@KyleJu I have a Windows machine that I am using for development through WSL2 and Docker containers, but it would have been nice to see if it was an easy fix so that the development process would be accessible to more people!
I'll proceed with giving a look at issue #3196! :) Thanks
