### ISSUE TITLE
Distinguish "Test file" result from subtest results

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#38]
_From @mikewest on August 21, 2017 20:2_

https://w3c-test.org/cookies/secure/set-from-ws.https.sub.html contains a single test, but http://wpt.fyi/cookies/secure/set-from-ws.https.sub.html  (and the table at http://wpt.fyi/cookies/secure) counts two.

_Copied from original issue: w3c/wptdashboard#92_

**Comment by lukebjerring** [comment]
_From @jgraham on August 21, 2017 20:17_

This is expected. One result is the overall file result, which is typically `OK` but can be `ERROR`, `TIMEOUT`, `CRASH`, etc. The other is the result of the single subtest.

**Comment by lukebjerring** [comment]
_From @mikewest on August 21, 2017 20:19_

Ok. I guess it seems strange to count that as a test in the list of results (and especially on the wrap-up tables). It surprised me, at least. :)

**Comment by lukebjerring** [comment]
_From @bobholt on August 31, 2017 13:36_

While expected, I agree it's odd. Leaving this open to consider how to more clearly distinguish overall file results from subtest results.

**Comment by lukebjerring** [comment]
_From @gsnedders on August 31, 2017 16:50_

The fact it's under the table as a subtest is confusing IMO. I also think the colouring isn't that useful: "OK" isn't actually that interesting; what we want is "ERROR"/"TIMEOUT"/etc. when the parent fails and make it clear the actual subtest results below are basically irrelevant.

**Comment by foolip** [comment]
The original issue was about both the numbers in https://wpt.fyi/results/cookies/secure and that https://wpt.fyi/results/cookies/secure/set-from-ws.sub.html does "count that as a test in the list of results".

I agree!

There are separate issues for these now:
* [Pass/total numbers inflated by "Test file" for testharness.js tests (harness status)](https://github.com/web-platform-tests/wpt.fyi/issues/62)
* [Distinguish harness status from subtests in test results view](https://github.com/web-platform-tests/wpt.fyi/issues/449)

@mikewest, please follow either or both of those if you're interested in following along, or just be delighted one day when they're fixed :)
