### ISSUE TITLE
Link to web-platform-tests.live instead of w3c-test.org

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#380]
https://web-platform-tests.live/ is now live. @jugglinmike will update this issue when it's a state where we can depend on it.

**Comment by frivoal** [comment]
Also, w3c-test.org seems stale, while https://web-platform-tests.live/ is up to date.

For example, https://w3c-test.org/css/css-values/calc-letter-spacing.html is a 404, but https://web-platform-tests.live//css-values/calc-letter-spacing.html works.

I am not sure how many links lead to it, but at least this one should be fixed:
<img width="574" alt="screenshot 2019-02-04 13 59 02" src="https://user-images.githubusercontent.com/113268/52190917-1c2d4100-2885-11e9-9f43-fed5f890b376.png">

(cc: @TalbotG )

**Comment by frivoal** [comment]
See also https://github.com/web-platform-tests/wpt/issues/13913

**Comment by TalbotG** [comment]
> but https://web-platform-tests.live//css-values/calc-letter-spacing.html works.

https://web-platform-tests.live/css/css-values/calc-letter-spacing.html
