### ISSUE TITLE
Inconsistent results on staging.wpt.fyi

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#381]
After https://github.com/web-platform-tests/wpt.fyi/pull/72 the front page should only show runs for the same sha of wpt. https://staging.wpt.fyi/results/ now shows:
![screenshot from 2018-07-26 10-09-31](https://user-images.githubusercontent.com/498917/43249812-03d89b74-90bc-11e8-9359-7a20ba36c76a.png)

@lukebjerring, this is also mixing stable and experimental runs which you mentioned yesterday, but the mixing of wpt shas seems like it could be a different problem.

**Comment by lukebjerring** [comment]
This is a regression from dropping the complete param, likely caused by my recent changes to push the query param behavior to the client. I've already written the integration test that would have caught this; will have a PR by end of day.

**Comment by Hexcles** [comment]
Fixed.
