### ISSUE TITLE
Ensure consistent shas between results and interop view

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#382]
After https://github.com/web-platform-tests/wpt.fyi/pull/330 it's easy to switch back and forth between results and interop. However, because interop results are computed in batch jobs, there's no guarantee that the same test runs are used for both views.

For example, when visiting https://staging.wpt.fyi/results/?sha=f9cb1ddc13 it would be great if the interop tab linked to https://staging.wpt.fyi/interop/?sha=f9cb1ddc13 and that was guaranteed to work.

I realize there's a bunch of work hidden in this issue and that it has implications for https://github.com/web-platform-tests/results-analysis and possibly will require computing interop numbers on the fly, but filing the issue for future planning.

**Comment by lukebjerring** [comment]
Another form that this bug takes is when the latest test-run and the latest interoperability computation are not the same; the default tabs (`/results` & `/interop`) show different runs.

**Comment by lukebjerring** [comment]
This was fixed by #498, #488, and #385
