### ISSUE TITLE
Links from https://wpt.fyi/results/dom?labels=stable to test are broken

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#388]
https://wpt.fyi/results/dom?labels=stable has a link to "interfaces.html?exclude=Node", but following it leads to https://wpt.fyi/results/dom/interfaces.html?labels=stable, and that's no longer a test.

The `?` in the test name is going to have to be escaped, or something.

**Comment by Hexcles** [comment]
Duplicate of #362 , which has already been fixed.

Production release is scheduled today. Stay tuned.

**Comment by foolip** [comment]
Oh nice, noticed on same test, even :)
