### ISSUE TITLE
Reading long failure messages requires scrolling horizontally

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#393]
https://staging.wpt.fyi/results/fullscreen/api/document-fullscreen-enabled-cross-origin.sub.html

To read the failure messages for Safari, which is rightmost, one has to hover over it, and the scroll to the right while taking care to not not move the mouse cursor. If I didn't have a touchpad where I could scroll without moving the cursor I'm not sure how I'd do it.

cc @mdittmer

**Comment by foolip** [comment]
I hesitate to solve problem by adding more options, but for this, https://github.com/web-platform-tests/wpt.fyi/issues/395 and https://github.com/web-platform-tests/wpt.fyi/issues/396, it might make sense to have a compact/full toggle in the UI, similar to icons/list toggles in file managers, or the "display density" options in Gmail.

**Comment by Hexcles** [comment]
This is also addressed (worked around) by #405.
