### ISSUE TITLE
History interleaves stable and experimental browsers

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#394]
On https://staging.wpt.fyi/results/fullscreen/api/document-fullscreen-enabled-cross-origin.sub.html, showing the history current shows this:
<img width="902" alt="screen shot 2018-07-27 at 9 27 20 pm" src="https://user-images.githubusercontent.com/498917/43342688-e73868ae-91e3-11e8-8e3f-f23f5860ee8e.png">

Note the green/red pattern for Chrome and Firefox. This seems to because the stable and experimental versions are interleaved, Chrome 67/69 and Firefox 61/63.

cc @mdittmer

**Comment by Hexcles** [comment]
FWIW, this is a known issue of the graphs, among some others, so we decided to hide the graphs behind a button and won't block prod releases on this.

**Comment by foolip** [comment]
I can confirm the page I originally reported is OK now. Thanks!
