### ISSUE TITLE
Subtest names with long prefixed are indistinguishable at a glance

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#395]
Subtest names are fairly often generated by scripts with the interesting variation at the end. Two such cases:

https://staging.wpt.fyi/interop/dom/historical.html

Here, "Historical DOM features m..." is all that can be seen without hovering.

https://staging.wpt.fyi/interop/gamepad/idlharness.window.html

Here, a number of tests start with "GamepadButton interface: ..."

cc @mdittmer

**Comment by Hexcles** [comment]
This is addressed by the verbose view introduced in #405.
