### ISSUE TITLE
[results-processor] Refer to download an archive file instead of "azure URL"

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#3958]
Currently we have function signatures like:

```python
def download(self, results, screenshots, azure_url): pass
```

Instead of explicitly calling it an "azure URL" (which isn't justified in the results-processor — there's nothing Azure-specific about it), we should just have some concept of an "archive URL" pointing at an archive.

(For #3906 I'm just going to pass `azure_url` [sic] to the processor, rather than doing this renaming, but we should keep this on the backlog.)

**Comment by past** [comment]
Eventually you did end up renaming it to archive_url right? Is there anything more to do here?

**Comment by gsnedders** [comment]
Nope, nothing to do here.
