### ISSUE TITLE
Abbreviated errors don't include assertion description

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#396]
https://github.com/web-platform-tests/wpt.fyi/pull/347 began abbreviating errors to things like `!TRUE`:
https://staging.wpt.fyi/results/compat/interfaces.any.html?label=stable

Or `!EQ("null", "no Origin header")`
https://staging.wpt.fyi/results/fetch/origin/no-cors.any.html?label=stable

The previous view also included the assertion descriptions:
https://wpt.fyi/results/compat/interfaces.any.html?label=stable
https://wpt.fyi/results/fetch/origin/no-cors.any.html?label=stable

Important extra detail are things like `The prototype object must have a property "orientation"` and `second origin should be opaque and therefore null` which will help pinpoint which specific assertion in the test is failing, and sometimes in itself be enough to understand the problem.

**Comment by Hexcles** [comment]
I think hovering on an individual cell should reveal the full raw message somewhere somehow. cc @mdittmer

**Comment by lukebjerring** [comment]
We should probably couple this with a 'verbose' / 'compact' toggle which resolves #393 too

**Comment by foolip** [comment]
Yeah, a verbose/compact toggle would solve this for me. Hovering to reveal would be enough in some cases, but the view as it currently is makes it pretty easy to tell if many failures are for the same reason at a glance, and https://wpt.fyi/results/css/css-typed-om/factory-absolute-length.html?sha=8b48137d39 is a good example of this. (It's not exactly the same error string, but that's sometimes the case too.)

**Comment by Hexcles** [comment]
This is addressed by the verbose view introduced in #405.
