### ISSUE TITLE
Display open PRs touching the current directory

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#4]
_From @jgraham on March 21, 2018 16:21_

For some specs we have a large number of open PRs. One problem is getting the people who would benefit from the tests landing to be aware of the fact that there are a bunch of outstanding PRs for that spec. If they know this it seems plausible that they will go in and review those tests, at least in some cases. Displaying the existence of unlanded PRs on wpt.fyi could help draw attention to this.

_Copied from original issue: w3c/wptdashboard#523_

**Comment by lukebjerring** [comment]
@mdittmer - You've dealt with `go-git` recently. Is this a simple enough request?

The GitHub API supports getting a list of files per PR, but not a list of PRs per file. At a guess, we'd need a server-side checkout of wpt.

**Comment by mdittmer** [comment]
Files per PR should be fine. We could just iterate over first N PRs if
quota is an issue. A local checkout of WPT is not cheap, and, IMHO, not a
great solution. We would need to juggle multiple remotes when PRs come from
forks. Using GitHub APIs would be much simpler if we can swing it.

There are reasonable go libraries for that I've used before too.

**Comment by lukebjerring** [comment]
Would you mind taking the API endpoint part of this issue then?
I'm thinking a PR that adds

    /api/pull-requests/[test-path]

Which returns a JSON array. Note that pulling down N PRs and filtering _afterward_ might be awfully inefficient with the scale that WPT gets PRs at?

**Comment by jgraham** [comment]
> We would need to juggle multiple remotes when PRs come from forks

FWIW that isn't true; all the PR heads are stored under `refs/pull/*/head` irrespective of original fork (I'm pretty sure that on the backend all forks are actually views into a single git object store).

Also you are going to need a checkout somewhere if the intent is to generate a complete list of tests from the manifest.

**Comment by foolip** [comment]
Came across this now when searching for something else. The GitHub APIs exist to fairly easily fetch PRs per top-level or css/* directory (labels) and show that. @jgraham, if part of the goal is to draw attention to open PRs, I guess it's a feature that they show up more broadly than for the specific test you're looking at?

**Comment by jgraham** [comment]
Yeah, a list per directory would be fine.
