### ISSUE TITLE
Chrome iOS runs missing since September 11th

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt.fyi#4004]
We've not had any Chrome iOS runs come in since September 11th of this year.

https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome_android&product=firefox_android&product=chrome_ios

CC @WeizhongX who is addressing the issue internally.

**Comment by WeizhongX** [comment]
The chromium bug: https://buganizer.corp.google.com/issues/367805189

**Comment by DanielRyanSmith** [comment]
This issue is now fixed. See [the Chromium bug](https://buganizer.corp.google.com/issues/367805189) for more details.
