### ISSUE TITLE
REGRESSION(2b78c274): web_components_test

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#4046]
See https://github.com/web-platform-tests/wpt.fyi/actions/runs/11265668333/job/31328132500?pr=4025

This regressed after 2b78c2741ad4eaab73fa33e32f564fbf0f28ae02 by @past, #4028.

This is making all PRs fail their checks.

**Comment by past** [comment]
Thanks, I have already seen and investigated this. There are a few options for fixing it, but due to BlinkOn and a team work week I will likely get to it on Monday.
