### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#409]
A favicon to distinguish wpt.fyi tabs would be great.

If I could wish for anything I like, it'd be like https://github.com/web-platform-tests/wpt/blob/master/images/wpt-logo/wpt-logo-orange-bg.svg (thanks @isaacdurazo and @zcorpan!) but with the letters "fyi". My beautiful mockup:
![fyi](https://user-images.githubusercontent.com/498917/43826176-f6387cce-9af6-11e8-9f9a-ff020a489b45.png)

**Comment by Hexcles** [comment]
What about just using the WPT logo as the favicon for wpt.fyi?

**Comment by foolip** [comment]
That would work, too. My mockup is in part motivated by the fantasy that we might have wpt.fyi-backed GitHub checks eventually to communicate regressions or other things that are derived from a combination of runs. And then the "fyi" as an icon would be cute, and different from the repo the check is in.
