### ISSUE TITLE
Some Focus Area percentages on dashboard don't match the results percentage

### ISSUE THREAD

**Issue by cookiecrook** [web-platform-tests/wpt.fyi#4107]
Some Focus Area percentages on dashboard don't match the results percentage

For example, the [dashboard](https://wpt.fyi/interop-2024) lists the Accessibility Focus Area at 97.8% and 99.7% respectively for Firefox and Safari…

<img width="693" alt="screen shot of dashboard listing scores described in the issue prose: 97.8% and 99.7%" src="https://github.com/user-attachments/assets/17a0903d-5169-4f73-a87c-e4d6839dc8da">

But if you click through to the [Focus Area results](https://wpt.fyi/results/?label=experimental&label=master&aligned&view=interop&q=label%3Ainterop-2024-accessibility), the scores are 98% and 99.9%.  (Bottom row right.)

<img width="589" alt="screen shot of results listing scores described in the issue prose: 98 and 99.9%." src="https://github.com/user-attachments/assets/3e42953e-0772-4059-b17b-e6ec6ce04846">

I haven't dug into which is correct, but it seems clear one of them is wrong, and the dashboard percentages should be consistent throughout.

**Comment by KyleJu** [comment]
Assign @DanielRyanSmith just so this issue has an owner. Feel free to discuss this in our meeting!

**Comment by cookiecrook** [comment]
Any movement on this @DanielRyanSmith? Thanks.

**Comment by DanielRyanSmith** [comment]
Sorry, I missed this until now - I'm not quite sure immediately what is happening here yet, since safari does not have any flaky tests that might cause this (that was my initial guess).

I see Safari with a 99.7% on the dashboard and a 99.9% on the results page.

![Screenshot 2024-12-02 7 18 37 PM](https://github.com/user-attachments/assets/14700a5a-7940-4d0e-b378-b5deacea2231)
---
![Screenshot 2024-12-02 7 18 53 PM](https://github.com/user-attachments/assets/5a4e1748-8a56-405b-9b0d-76eef820f519)

If I had to guess again, it might be the fact that some tests/subtests under the label "interop-2024-accessibility" were added/removed at some point through the year, and the interop score aggregation script is using an incorrect number of tests to calculate the passing percentage.

**Comment by cookiecrook** [comment]
Thanks for digging in... The total number has fluctuated a bit as invalid or disputed tests were removed or modified.

**Comment by DanielRyanSmith** [comment]
So I took a deeper look into this and it turns out that the interop dashboard score is definitely the more correct score, and the discrepancy here is due to how the rounding was handled on the test results page. I've made an extremely simple fix at #4142, which has an explanation of the problem.

**Comment by cookiecrook** [comment]
@DanielRyanSmith Original cases linked above still show a discrepancy. Albeit a smaller one. 99.7 to 99.8 instead of the original 99.7 to 99.9.

**Comment by cookiecrook** [comment]
I don’t have a way to reopen the issue. Would you prefer a new one?

**Comment by DanielRyanSmith** [comment]
Hmm, this is still the same issue, but my quick change did not match the approach for the [interop score aggregation script](https://github.com/web-platform-tests/results-analysis/blob/d64417c4761ead5058c6470be99d5b8ea68aa0e5/interop-scoring/main.js#L245-L247), which does no rounding and is the intended result. The test results page is still rounding up, just a little less. I'll readjust things. Sorry about that!

The dashboard score is still correct here.

**Comment by DanielRyanSmith** [comment]
As a follow-up, this is now in production and the Accessibility scores on the results page look as expected. 🙂 

Note that there is a possibility that score discrepancies might pop up at some point, and the likely causes have been documented in these issues:
- #4160
- #4159

However, the cause for the original situation described in this issue has been fixed. Thanks for the patience as I investigated here 😊
