### ISSUE TITLE
Finding regressions in diff view is too hard

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#411]
https://staging.wpt.fyi/results/?product=chrome%5Bexperimental%5D&product=chrome%5Bstable%5D&diff shows this:
![image](https://user-images.githubusercontent.com/498917/43826603-fd69d76c-9af7-11e8-8cd1-e2d85eb708f4.png)

The numbers in the 3rd column are the differences between the pass / total numbers in columns 1 and 2.

Because the number of *failures* isn't counted, when both the total number of tests and total number of passes has changed, it's difficult to see if the number of failures has changed. The appropriate comparison would be in the number of failures, which is `(totalA - passA) - (totalB - passB)`. That's `(totalA - totalB) - (passA - passB)`, so as it turns out one can compare the numerator and denominator in column 3 to check if there are more failures, but that is not possible to do at a glance.

(https://github.com/web-platform-tests/wpt.fyi/issues/408 is a separate issue about the order, which also makes it tricky to skim the view for interesting things.)

**Comment by foolip** [comment]
Actually, that formula doesn't quite cut it either. There is a regression in https://staging.wpt.fyi/results/css/css-values?product=chrome[experimental]&product=chrome[stable]&diff=true (viewport-units-css2-001.html) but it wasn't possible to see that from the high-level numbers, I just happened to drill down there because the numbers for css were large and I wanted to see why.

**Comment by jgraham** [comment]
A comparison based on totals rather than actual differences seems rather problematic; finding that e.g. nightly is +8 passes vs stable doesn't mean there aren't regressions if it's actually +10 -2 i.e. 10 tests started passing, but two regressed.

Separate to that the view would be much clearer if it filtered the columns to only show directories/tests with changes.

**Comment by foolip** [comment]
Yep, these are both changes @lukebjerring and I have discussed. This view is based on comparing summary numbers. It would be improved by comparing the pass/total numbers on the test level and aggregating the differences from tests that could be regressions.

To make it entirely reliable the comparison has to be done using the full results including subtests, but one can probably emulate that quite well using just the summary numbers in different way.

**Comment by foolip** [comment]
The problem with comparing totals became apparent here:
https://staging.wpt.fyi/results/?product=firefox[experimental,buildbot]@8657903435&product=firefox[experimental,taskcluster]@8657903435&diff=true

For css/, the total change is +12 passing tests, but drilling down there are actually a bunch of regressions in css/selectors/ that were obscured by even more changes in the positive direction.

**Comment by foolip** [comment]
Discussed with @lukebjerring today. A simple improvement here would probably be to use three numbers in the diff column: total number of regressions, total number of "progressions" and diff of number of subtests.

That would mean that there's one of those numbers that you can always look at to look for regressions, even if the regressions and "progressions" cancel out.

**Comment by foolip** [comment]
@lukebjerring, the filtering has made it way way better. I'll open a new issue if I still struggle next time.
