### ISSUE TITLE
"File status" still shown for testharness.js tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#419]
A follow-up to https://github.com/web-platform-tests/wpt.fyi/issues/371.

"File status" is still shown for these test:
https://staging.wpt.fyi/results/compat/webkit-text-fill-color-currentColor.html
https://staging.wpt.fyi/results/css/css-flexbox/flexbox_first-letter.html
https://staging.wpt.fyi/results/dom/historical.html

Probably all tests are affected.

**Comment by Hexcles** [comment]
Looks like my fix #375 was regressed.

**Comment by foolip** [comment]
After https://github.com/web-platform-tests/wpt.fyi/pull/443 the URLs I listed now show "Harness status".

Reftests show "Test status":
https://staging.wpt.fyi/results/css/css-flexbox/flex-basis-001.html

"Harness status" also shown for wdspec test:
https://staging.wpt.fyi/results/webdriver/tests/find_elements_from_element/find.py

So, all working as it should, thanks @Hexcles!

Here's a testharness.js test with timeout everywhere:
https://staging.wpt.fyi/results/async-local-storage/api-surface.tentative.https.html?sha=6aef6676d2

This says "Test status" and would change to "Harness status" when any browser reports any subtest. That's OK :)
