### ISSUE TITLE
Update "GitHub Source" and any others links to point to this repo

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#42]
w3c/wptdashboard links now lead to https://github.com/web-platform-tests/results-collection because of the recent renaming.

**Comment by lukebjerring** [comment]
Search for `w3c/wptdashboard` in this repo only points to Golang files.

Might be that I fixed this in https://github.com/web-platform-tests/wpt.fyi/pull/40/files#diff-ec79331c94a845dcb922311420bc5d47

**Comment by foolip** [comment]
I guess that's not deployed? https://wpt.fyi/about is unchanged.

But it does seem to have been fixed, webapp/templates/_header.html in the initial commit already had the updated URL.
