### ISSUE TITLE
Use the same color scheme in results and interop view 

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#423]
https://staging.wpt.fyi/results/css/css-animations looks like this:
![image](https://user-images.githubusercontent.com/498917/43948339-dcc0d9a4-9c8a-11e8-96ba-eb254622b3e7.png)

https://staging.wpt.fyi/interop/css/css-animations looks like this:
![image](https://user-images.githubusercontent.com/498917/43948361-eb506a34-9c8a-11e8-9328-04ab97da5ad5.png)

The interop view uses a red->orange->yellow->green color scheme, where the colors are faded to white based on the proportion of the total number of tests that fall into the column.

The results view uses a red->pink->green color scheme, where total failure is red, 99% passing is pink, and 100% is green.

I'd like to suggest a more consistent color scheme for both:
* Only 100% passing is represented as green, as before. Making 99% clearly distinct from 100% makes it easier to spot where failures are hidden.
* The red->orange->yellow transition for 0%->99% from the interop view is used also in the results view.
* In the interop view, we can keep fading the somewhat based on the proportion of tests falling into the bucket.

**Comment by lukebjerring** [comment]
Currently, we use paper colors in interop, with the alpha channel changing:
https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/components/interop.html#L209

But we use something different in wpt-results:
https://github.com/web-platform-tests/wpt.fyi/blob/master/webapp/components/wpt-results.html#L79

And, something different again in the individual files...

**Comment by foolip** [comment]
Another consideration is picking colors that work with black text. The darkest red we now use might be a tad too dark really.

**Comment by lukebjerring** [comment]
Note that once #674 lands, badge colors will need to be consistent with these choices too.

**Comment by foolip** [comment]
In light of https://github.com/web-platform-tests/wpt.fyi/pull/674, having a discontinuity between yellow and green between 99% and 100% doesn't seem so great. In the form of a badge, it might create the incentive to defend a 100% status in a way that isn't helpful for interoperability. (This of course might happen on wpt.fyi itself as well, but seems less likely.)

https://software.hixie.ch/utilities/js/live-dom-viewer/saved/6331 is a computed red-to-green scale, which I don't find that good, in particular the yellow range is too narrow:
<img width="92" alt="screen shot 2018-10-28 at 8 14 37 pm" src="https://user-images.githubusercontent.com/498917/47620751-1e496c00-daee-11e8-8929-8c3b658c271c.png">

https://software.hixie.ch/utilities/js/live-dom-viewer/saved/6332 uses a fixed palette (from paper-styles) and reserves the reddest and greenest ends for 0 / N and N / N. With that tweak and few enough colors, it's still easy to distinguish 99% from 100%:
<img width="92" alt="screen shot 2018-10-28 at 8 15 50 pm" src="https://user-images.githubusercontent.com/498917/47620765-4a64ed00-daee-11e8-8c58-496572bc7077.png">

https://software.hixie.ch/utilities/js/live-dom-viewer/saved/6333 cuts out the shades between yellow and green to match my original proposal, but I don't think it's really an improvement:
<img width="93" alt="screen shot 2018-10-28 at 8 13 50 pm" src="https://user-images.githubusercontent.com/498917/47620750-0a056f00-daee-11e8-9ff5-8ed0d40f91cf.png">

So, 6332 would be my updated proposal.
