### ISSUE TITLE
sha links under browser names don't preserve labels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#427]
Start at https://staging.wpt.fyi/results/ambient-light?label=experimental

Under "Chrome 70" there is a "@eea0b54014" link to https://staging.wpt.fyi/results/ambient-light?sha=eea0b54014.

That link should preserve other query params, i.e. it should be to https://staging.wpt.fyi/results/ambient-light?label=experimental&sha=eea0b54014

**Comment by lukebjerring** [comment]
Related to #515

**Comment by lukebjerring** [comment]
This is now redundant since those links now send the user to GitHub for the commit, not an in-page query change (which is done with the query builder).
