### ISSUE TITLE
Document how to integrate with the revision announcer

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#429]
https://wpt.fyi/api/revisions/list has been deployed and running for a while. @AutomatedTester and @jgraham was asking about it, and although I seem to remember reading docs, I can't find them now, apart from https://github.com/web-platform-tests/wpt.fyi/blob/abbeb9b8ff56f63c7fc449a552aa2b5406eca315/revisions/README.md.

**Comment by foolip** [comment]
I guess it should go in https://github.com/web-platform-tests/wpt.fyi/blob/master/api/README.md?

**Comment by Hexcles** [comment]
Fixed by #434
