### ISSUE TITLE
Integration tests are broken but the Travis jobs are still green

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#435]
I just discovered today, astonishingly, that our integration tests had been broken for a while but the Travis jobs were all green.

Example job: https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/415642946

The log is too long and truncated. You'd have to check out the raw log to see the errors, but the raw log contains a lot of terminal markups (colour, etc.) that makes it very hard to read.

It seems at least the web component tests are broken.

```
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m wptdashboard@ wct: `wct`

[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Exit status 1

[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 

[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Failed at the wptdashboard@ wct script.

[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m This is probably not a problem with npm. There is likely additional logging output above.

Done. Your build exited with 0.
```

**Comment by mdittmer** [comment]
What's happening to the status code when these tests break? Even if logs can truncate, nonzero should still trigger Travis failure, no?
