### ISSUE TITLE
Discussion: put breaking UI changes and new UI features behind flags by default

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#440]
Today during my discussion with @foolip , I pointed out that the recent deployment (#389) was delayed by more than two weeks partly because of some usability issues in the new UI features or some other breaking UI changes.

The release was much needed to fix some important bugs reported by users, show the new logo for Edge Insider, and make some new parameters that had been advertised in various discussions & presentations finally available to users. And when we realized the code wasn't ready for release, we kinda had to put off landing new features and focus on fixing / working around bugs to make the release possible.

It's important to be able to release quickly when needed (avoiding the feature-fix-release cycle), while it's equally important to maintain developer velocity. Given the size of our team, we probably don't want to maintain different branches for bug fixes and new features (or release channels). The other option that I can think of is to put all breaking UI changes and new UI features behind flags *by default*. And by flags, I mean anything including URL params (or hash) and buttons/toggles. These ad-hoc "flags" should be good for now, and the actual implementation will be case-by-case, decided by authors and reviewers. We might consider some more elaborate flag system in the future.

@mdittmer @lukebjerring please feel free to give your opinions.

**Comment by foolip** [comment]
A cookie and `/flags` SGTM!

**Comment by lukebjerring** [comment]
`/flags` and `admin/flags` are now tightly integrated into the common workflow.
