### ISSUE TITLE
Use full SHAs as the identifier

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#49]
I'm quite nervous about the current practice of using only 10 characters of the full SHAs as identifiers.

To be future-proof, I propose to gradually switch to full SHAs, at least internally (GCS paths, Datastore entities, etc.), and make all SHA lookup code capable of handling both shortened and full SHAs (and perhaps giving a warning when multiple results are found in a lookup).

**Comment by lukebjerring** [comment]
Sure. Note that https://github.com/web-platform-tests/wpt.fyi/pull/46 was simply to prevent a broken UI for the current behaviour - not advocating for short-SHA-only.

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/wpt.fyi/pull/164 added `FullRevisionHash`

**Comment by lukebjerring** [comment]
This is fixed - `?sha is a prefix of the FullRevisionHash`.
