### ISSUE TITLE
Deploy 9923185 to prod (2018-08-29)

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#492]
Changelist: https://github.com/web-platform-tests/wpt.fyi/compare/d698063...9923185

Most notably two efforts:
1. My fixes for various integration tests, which shouldn't have any observable effects to users.
2. @mdittmer 's new search&autocomplete APIs.

**Comment by Hexcles** [comment]
New version up: https://9fc0a08-dot-wptdashboard.appspot.com/results/

**Comment by Hexcles** [comment]
Checklist by @mdittmer 

* [ ] /results (A)
    * [ ] Full results list
    * [ ] Search works
    * [ ] Correct default set of browsers
        * [ ] Currently: Latest not-hash-aligned stable runs
    * [ ] "Show history"
        * [ ] Line chart shows up
    * [ ] Back button goes to previous directory/file state
    * [ ] Tab switch to interop preserves runs under consideration
* [ ] /results?complete=true
    * [ ] All runs have same hash
    * [ ] Subtests of (A)
* [ ] /results?product=chrome&product=edge
    * [ ] Subtests of (A)
    * [ ] Latest chrome and edge runs shown
* [ ] /results?product=chrome&product=edge&diff=true
    * [ ] Subtests of (A)
    * [ ] Correctly formatted diff column added for whole table
* [ ] /results?label=experimental
    * [ ] Subtests of (A)
    * [ ] Latest experimental runs shown
* [ ] /results?complete=true
    * [ ] Subtests of (A)
    * [ ] Hashes for runs are identical
* [ ] /results?label=experimental&complete=true
    * [ ] Subtests of (A)
    * [ ] Hashes for runs are identical
    * [ ] Experimental runs shown
* [ ] /results?label=stable&complete=true
    * [ ] Subtests of (A)
    * [ ] Hashes for runs are identical
    * [ ] Stable runs shown
* [ ] /interop
    * [ ] Search works
    * [ ] Tab switch to results preserves runs under consideration
* [ ] /results/path/to/specific/test
    * [ ] Expand/collapse works
    * [ ] "Show history"
        * [ ] Line chart shows up
        * [ ] "Tiny boxes" chart shows up

**Comment by Hexcles** [comment]
@mdittmer new version is up: https://cccaa7a-dot-wptdashboard.appspot.com/results/

And I've cleared the checklist.

**Comment by mdittmer** [comment]
Merge of #501 currently blocked on Travis port selection issue: https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/423007605#L2936

**Comment by mdittmer** [comment]
New version is up: https://587b8de-dot-wptdashboard.appspot.com/results/

**Comment by mdittmer** [comment]
New version is up: https://9923185-dot-wptdashboard.appspot.com/results/

**Comment by mdittmer** [comment]
Note on behaviour change:

- This release does not include fix #491
- `?label=[stable|experimental]&complete=true` used to effectively ignore `complete=true`
  - In this release, it attempts to honour it (by only showing hash-aligned runs), but does not always render 4 label-matching runs; see #491 for details

**Comment by mdittmer** [comment]
Note on behaviour change:

- Some interop views that didn't work at all before now work somewhat, but do not respect all query params
  - E.g., https://wpt.fyi/interop/?label=stable&complete=true shows nothing whereas https://9923185-dot-wptdashboard.appspot.com/interop/?label=stable&complete=true shows results, but not all runs are `label=stable`

**Comment by mdittmer** [comment]
Checklist complete. Starting traffic migration at 20%.

**Comment by mdittmer** [comment]
Traffic now at 50%.

**Comment by mdittmer** [comment]
... 80%

**Comment by mdittmer** [comment]
100%!
