### ISSUE TITLE
/test-runs does not reflect product (or multiple runs)

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#495]
Issues like https://github.com/web-platform-tests/results-collection/issues/597 would be made more obvious if there was a visual indicator of the number of runs for a SHA, or the product (in particular, whether it's experimental).

cc @jugglinmike who raised the issue

**Comment by Hexcles** [comment]
I'd like to see eight columns (four browsers X (experimental, stable)).

**Comment by jugglinmike** [comment]
We could also display an integer within each cell an expose complete test run information via a tool tip.
