### ISSUE TITLE
Summary numbers incorrect when navigating into subdirectories

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#510]
Repro steps:

Start at https://wpt.fyi/results/webaudio/the-audio-api?complete=true. You should see this:
<img width="801" alt="screen shot 2018-08-31 at 10 25 22 pm" src="https://user-images.githubusercontent.com/498917/44934352-d071eb00-ad6c-11e8-84e0-603b85b5b247.png">

Then, click "the-analysernode-interface/" to reach https://wpt.fyi/results/webaudio/the-audio-api/the-analysernode-interface?complete=true. You should see this:
<img width="803" alt="screen shot 2018-08-31 at 10 26 22 pm" src="https://user-images.githubusercontent.com/498917/44934390-ea133280-ad6c-11e8-9b7e-f9943310b7e1.png">

Note how the summary numbers are the same for the first row! Reload the second page to instead see this:
<img width="799" alt="screen shot 2018-08-31 at 10 27 10 pm" src="https://user-images.githubusercontent.com/498917/44934422-07480100-ad6d-11e8-835c-7d4ff4fe48b3.png">

**Comment by foolip** [comment]
Probably a bug from the refactoring of the components.

**Comment by whimboo** [comment]
When will be the next deploy to production so that this annoying bug is fixed? Thanks.

**Comment by lukebjerring** [comment]
Looking to deploy this week, with a fix for the interop view too.

**Comment by whimboo** [comment]
Thanks!
