### ISSUE TITLE
Discuss and define the terminologies for release channels of major browsers

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#538]
@lukebjerring raised this question earlier. We should investigate what the various release channels of (four) major browsers really mean, and try our best to align them under a set of well-defined terminologies in wpt.fyi. An example would be four channels: stable, beta, dev, experimental (though we need to flesh out the definitions). Based on that, we can create labels for these channels and make sure we are comparing apples to apples on wpt.fyi.

Currently on wpt.fyi we only have two labels, `stable` and `experimental`. With beta results coming from Taskcluster, we'll soon have `beta`, too.

**Comment by lukebjerring** [comment]
We originally jotted a proposal here:
https://docs.google.com/presentation/d/1f5MsezY4TRz4W-JTnqPuW99WFtMp24WNYaPZ6OSdmTM/edit#slide=id.g3ca2f40f94_0_24 

Summary:
- **stable**: The current public release of a browser.
- **beta**: A pre-stable release branch of a browser.
- **dev**: Tip-of-tree branch of a browser, generally updated very regularly.
- **experimental**: `dev`, _including_ experimental features (via enabling flags).

Notes:
- `dev` should be as close to tip of tree as possible.
Picking on Chromium as an example, we actually have more than one channel that fall under wpt.fyi's `dev` definition - `Dev` and `Canary`. For our purposes, we'd just take the most regularly updating of the options.
- `beta` should just be the _next_ branch that will be released as `stable`

**Comment by foolip** [comment]
In https://github.com/web-platform-tests/wpt.fyi/pull/590#issuecomment-426418724 and https://github.com/web-platform-tests/wpt.fyi/issues/611, I think the root problem is that we want mutually exclusive labels for channels, but "experimental" isn't a channel, but a channel + flags. This means we can't accurately label the the channel for these runs.

I think it would probably be beneficial to have one set of labels for channel *only*, which is mutually exclusive, and where we match the nomenclature of each browser. It would mean that we use chrome[dev] and firefox[nightly], but it's possible that we'd add chrome[canary] and firefox[dev] as well, which aren't the same.

One problem is that we already have lots of links to `?label=experimental`, so we probably can't make "experimental" mean exactly "including experimental features (via enabling flags)", but rather just "the most bleeding edge configuration we have for this product".

**Comment by lukebjerring** [comment]
Can we convert that vague proposal into a literal proposal here, @foolip ?

**Comment by foolip** [comment]
Alright :)

Use the official channel names per https://github.com/web-platform-tests/wpt.fyi/issues/538#issuecomment-426625742, as mutually exclusive labels. Then preserve existing URLs using `?label=experimental` by either treating as a product-dependent alias for other labels, or by redirecting to `products=chrome[dev],edge[preview],firefox[nightly],safari[preview]`. A type of alias might be better, to support a "latest everything" URLs that keep updating over time.

Possible follow-up: make channel a first-class concept like versions, so that something like `product=chrome-dev-72` works, or `products=chrome-dev,edge-preview,firefox-nightly,safari-preview`.

**Comment by lukebjerring** [comment]
The current state of affairs:
- We run the `stable` releases as much as 6-hourly
- We run the `beta` releases weekly (ff and chrome)
- We run the `experimental` cut (with experimental features) on all master commits (ff, chrome)
- We run the `experimental` cut on all PR commits (safari, ff, chrome).

Dropping "Dev" for now; it's a concept that we don't use and didn't reach consensus on.

**Comment by foolip** [comment]
`dev` is the Chrome release channel we use, so yeah, we shouldn't use it to mean something else as well.
