### ISSUE TITLE
Results Receiver API for external runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#55]
Design doc: [WPT Results Receiver](https://docs.google.com/document/d/1F3GWJ6lA8C3S5WgyJgXxmTFzu92mqF-1ddGije67ork/edit?usp=sharing)

This is an umbrella issue to track that implementation, and replaces https://github.com/web-platform-tests/results-collection/issues/290.

**Comment by Hexcles** [comment]
Also related: https://github.com/w3c/web-platform-tests/issues/10511 (adding some metadata to wptreport which will be required by the results receiver)

**Comment by Hexcles** [comment]
MVP has shipped. Closing this umbrella bug.
