### ISSUE TITLE
Redirect http://wpt.fyi/ to https://wpt.fyi/ and use HSTS

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#58]
Moved from https://github.com/web-platform-tests/results-collection/issues/128.

This would depend on builds.wpt.fyi using HTTPS, or moving it to another domain.

**Comment by jeffcarp** [comment]
> This would depend on builds.wpt.fyi using HTTPS, or moving it to another domain.

I think it should be possible to land HSTS on wpt.fyi without requiring HTTPS on builds.wpt.fyi by removing the `includeSubDomains` part of the header ([here](https://github.com/web-platform-tests/results-collection/pull/517/files#diff-71e9e9661417b9ac2144488216cff637R52)).

**Comment by jugglinmike** [comment]
@foolip [This was previously blocked on HTTPS support in the results-collection project](https://github.com/web-platform-tests/results-collection/issues/534), but we just today decommissioned that project. That means there's no longer a restriction on enforcing HTTPS on the wpt.fyi domain, so if that's still important to you folks, this issue should be re-opened.

**Comment by Hexcles** [comment]
Thanks, Mike. This has been fixed.
