### ISSUE TITLE
https://wpt.fyi/api/runs?max-count=1000&label=stable returns 500 Server Error

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#587]
It says "API error 1 (datastore_v3: BAD_REQUEST): cannot get more than 1000 keys in a single call".

This URL is used in [ecosystem-infra-stats](https://github.com/foolip/ecosystem-infra-stats/blob/bce9e3cd153eb2a7427abec1e05bc5878f093499/wpt-dashboard-stats.py#L10) with reference to https://github.com/web-platform-tests/wpt.fyi/issues/3.

The cutoff point between working and not working seems to be 302/303:
https://wpt.fyi/api/runs?max-count=302&label=stable (works)
https://wpt.fyi/api/runs?max-count=303&label=stable (500)

That's a surprising cutoff point, not a divisor of 1000, so perhaps it won't be stable over time.

What I really want is an API to enumerate *all runs ever*, or possibly all runs after a specified date.

**Comment by foolip** [comment]
Note that with Taskcluster runs in prod, this problem will get worse. 300 runs will be roughly 3 weeks of activity in wpt, not enough to compute stats for the past quarter as we'll want to do.

**Comment by lukebjerring** [comment]
This is essentially a duplicate of #569

**Comment by foolip** [comment]
I'll open a feature request instead.
