### ISSUE TITLE
Allow /api/runs to enumerate runs for at least past 3 months

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#588]
[ecosystem-infra-stats](https://github.com/foolip/ecosystem-infra-stats/blob/bce9e3cd153eb2a7427abec1e05bc5878f093499/wpt-dashboard-stats.py#L10) uses /api/runs to compute latency stats for run uploads to wpt.fyi.

In https://github.com/web-platform-tests/wpt.fyi/pull/584 the limit is being lowered to 500 (or lower) and with Taskcluster runs soon producing results per push to master, this will not be enough to get all runs in the previous 3 months.

Ideally there should be an API to enumerate *all* runs ever, even if paginated, to make it easier to perform ad-hoc analysis by grabbing a bunch of runs. Failing that, slightly more than 3 months should suffice to compute latency quarterly, if the computation is done soon after the end of each quarter.

**Comment by lukebjerring** [comment]
I believe this is now possible after #673, though it will still be up to a max of 500 of each product I think.

e.g. https://wpt.fyi/api/runs?from=2018-06-01T00%3A00%3A00.000Z
