### ISSUE TITLE
Redirect www.wpt.fyi to wpt.fyi

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#59]
We have www.wpt.fyi, which is probably wise because some things that manage URLs will try to "normalize" by adding it. (Unsure how common, but years ago I had to add www.foolip.org because of it.)

So, redirect it, permanently :)

**Comment by lukebjerring** [comment]
Done.

**Comment by foolip** [comment]
https://www.wpt.fyi/ is just broken for me right now.

**Comment by lukebjerring** [comment]
Https will take up to 24h, apparently.

**Comment by foolip** [comment]
Oh, so for a while we just didn't have www.wpt.fyi, or just no cert for it?

**Comment by lukebjerring** [comment]
Previously.. idk what it did. Same as whatever https://foo.wpt.fyi does, I
guess.
