### ISSUE TITLE
Show upload status

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#605]
At the moment, we have no indication of anything happening between builds completing and them appearing in "recent runs". It would be nice to have… some indication that results for a build are processing, at the very least. Ideally with a progress bar and an ETA.

**Comment by foolip** [comment]
@Hexcles?

**Comment by foolip** [comment]
This might also help understand an issue like https://github.com/web-platform-tests/wpt.fyi/issues/604, where one might be able to tell if wpt.fyi has any knowledge of the run at all.

**Comment by lukebjerring** [comment]
There is now a very basic UI under the `Processor` tab: wpt.fyi/status
