### ISSUE TITLE
Maybe: add dev and nightly labels to Chrome Dev and Firefox Nightly runs respectively

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#611]
Looking at https://wpt.fyi/test-runs I trying to create URL like this one:
https://wpt.fyi/results/?products=chrome[stable],chrome[dev]&aligned=true

That's because I see "dev" right there in the logo. But we only add the experimental label.

It would be great if the dev label was also applied so that this works. Similarly for Firefox.

**Comment by Hexcles** [comment]
First of all, I don't think we support multiple advanced product specs in `products`, i.e. if you have a bunch of `browser[label]`, you'd need to specify them via multiple `product` parameters.

Secondly, there's some confusion about the labels here. We (tentatively) define the "experimental" channel as cutting edge + experimental features, so all the Chrome Dev and Firefox Nightly runs we have right now are experimental, as they all have experimental features enabled.

If we are to add the "dev" label to a run, the run will need to be cutting edge **without** experimental features. See #538 cc @lukebjerring .

**Comment by foolip** [comment]
> First of all, I don't think we support multiple advanced product specs in `products`, i.e. if you have a bunch of `browser[label]`, you'd need to specify them via multiple `product` parameters.

That does seem to work, though. Just by accident?

> See #538

Commented there.

**Comment by lukebjerring** [comment]
The issue was actually with nested commas - a single label was fine. Both now work, though, since #669

**Comment by lukebjerring** [comment]
@Hexcles - the proposal from @foolip is to include extra alias-labels for the `dev` channel which match how the products name their own channel-equivalents.

**Comment by Hexcles** [comment]
Re-opening because we might also want to re-label all the existing runs.

**Comment by foolip** [comment]
I guess this also hasn't been deployed yet?

**Comment by Hexcles** [comment]
No & no.

**Comment by foolip** [comment]
I tried that, but like your link it showed no results.

**Comment by foolip** [comment]
@Hexcles you reopened once before to do that, do you still think we should?

**Comment by Hexcles** [comment]
Sorry for late response. I didn't patch the historic data because the change to add these new labels wasn't pushed to prod yet. And now that we had a prod push, I'll batch label all previous runs.

**Comment by Hexcles** [comment]
Retroactive tagging in progress on staging; will continue to prod after verification.

**Comment by Hexcles** [comment]
This is done.

**Comment by foolip** [comment]
Thanks @Hexcles!
