### ISSUE TITLE
Publish results from WebKitGTK

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt.fyi#612]
My understanding is that we need to

* [x] Make sure it's possible to run the tests with wptrunner + WebKitGTK
* [x] Set up automation to run the tests regularly (See https://github.com/web-platform-tests/wpt.fyi/tree/master/api#announcement-of-revisions-of-interest)
* [x] Upload the results to wpt.fyi (See https://github.com/web-platform-tests/wpt.fyi/tree/master/api#results-creation)

CC @zdobersek @mcatanzaro

**Comment by zdobersek** [comment]
It used to be possible with MiniBrowser. Epiphany would work as well, probably. You just need to settle on one thing.

**Comment by mcatanzaro** [comment]
wpt.fyi shows results for browsers, not engines, so I would use Epiphany....

**Comment by foolip** [comment]
It's fine to provide results from a WebKitGTK test shell if that's the easiest to set up. We've discussed having results from Chromium's content_shell test binary, although we haven't done it.

**Comment by foolip** [comment]
@Ms2ger I've updated your original comment to point to https://github.com/web-platform-tests/wpt.fyi/tree/master/api#announcement-of-revisions-of-interest, which is for ensuring sha alignment between runs on different infrastructure. Unless you want to run for every wpt push to master, then daily is probably the best starting point.

**Comment by mcatanzaro** [comment]
Work is underway in https://github.com/web-platform-tests/wpt/pull/15580

**Comment by jgraham** [comment]
This is done now, right?

**Comment by Hexcles** [comment]
Yeah I think so; at least everything in the checklist is done. Feel free to reopen if I missed anything.

**Comment by stephenmcgruer** [comment]
Note that WebkitGTK still isn't available in /api/runs (https://github.com/web-platform-tests/wpt.fyi/issues/1594), but I think that's best tracked in the wpt.fyi repo
