### ISSUE TITLE
Pass/total numbers inflated by "Test file" for testharness.js tests (harness status)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#62]
Moved from https://github.com/web-platform-tests/results-collection/issues/427. I wrote:

> https://wpt.fyi/gyroscope is a directory where currently all tests except https://wpt.fyi/gyroscope/Gyroscope_insecure_context.html are actually failing, but the overall pass rates listed in https://wpt.fyi/ are 10/50.
>
> This is because "Test file" counts as passing if there aren't any harness errors, for testharness.js tests. For test suites that are split into many files, this makes it harder to spot the "not supported at all" cases, and it would also inflate the 4/4 counts for https://github.com/w3c/wptdashboard/issues/83. Example:
https://metrics5-dot-wptdashboard.appspot.com/metrics/gyroscope/Gyroscope-disabled-by-feature-policy.https.html
>
> @mdittmer @lukebjerring FYI ^
>
> Since "Test file" is the main and only result for reftests the solution would not be to just omit this line. And knowing about harness errors is useful, so omitting it for just testharness.js tests is also not a complete solution.

And:

> I think this might work:
> * Call it "Harness error" instead of "Test file" for testharness.js tests
> * Don't count that in any summary numbers
> * Include harness errors in the upcoming "anomalies" view.

**Comment by foolip** [comment]
Additional thoughts since then. If we make an effort to eliminate harness errors wpt-wide, and make harness errors blocking for PRs (which seems within reach) then we could include harness errors in an "anomalies" view and exclude it from the counts.

**Comment by foolip** [comment]
I just noticed this is a particular problem in the interop view.

In https://wpt.fyi/interop/infrastructure/expected-fail?label=stable&aligned=true, failing-test.html is supposed to fail consistently, and does, but the harness status makes it look like there might be a problem, with "1 / 2" in the 4/4 column.

More generally, the harness status will inflate the "4 / 4" column and make things seem better than they are, numerically at least.

**Comment by foolip** [comment]
@lukebjerring this is easy-ish to fix now with the search cache, right? Or do the summary files ruin it still?

**Comment by lukebjerring** [comment]
It's possible - The issue is diverging from the summary files (used when not executing a search).

**Comment by foolip** [comment]
So I guess the options are making /api/search serve all requests or recomputing all summary files? The former is appealing, but I guess it's not known how much traffic we can handle?

**Comment by fred-wang** [comment]
Hi. I wonder if there is any update on this issue?

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/wpt.fyi/issues/1200 introduced a feature that we could try and use, which only takes effect whenever the /api/search endpoint is used.

@Hexcles - are you able to whip up a PR that changes the summaries to also ignore the OK status when that feature is enabled?

The problem then becomes one of reprocessing the entire corpus (~60K runs) so that we are consistent before and after switching.

**Comment by Hexcles** [comment]
> @Hexcles - are you able to whip up a PR that changes the summaries to also ignore the OK status when that feature is enabled?

That'd be easy to do.

> The problem then becomes one of reprocessing the entire corpus (~60K runs) so that we are consistent before and after switching.

This is the real challenge to get it right (it'll be a long process and we'd need some plans for backup, rollback, recovery from interruptions, etc.). If we can switch to on-the-fly summaries via searchcache altogether, this'll be much easier.

**Comment by foolip** [comment]
This was fixed by the v2 summary format.
