### ISSUE TITLE
Duplicate Chrome Dev runs from Taskcluster

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#624]
https://wpt.fyi/test-runs shows:
![image](https://user-images.githubusercontent.com/498917/46538797-334b2a80-c8b5-11e8-89d8-c5957b90fe72.png)

For b4c8ec5a1c there are 2 Chrome Dev results, and for 23cc12436a there are 3. It's possible there are more duplicates going back in history, but this is the first time I've noticed them.

**Comment by Hexcles** [comment]
Closed by #247
