### ISSUE TITLE
Expose `raw_results_url` for download

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#628]
/api/runs includes a `raw_results_url` field that points to the original JSON report from `./wpt run`. To allow for offline ad-hoc analysis, exposing those URLs for download in the UI would be useful.

Context is this question on webkit-dev:
https://lists.webkit.org/pipermail/webkit-dev/2018-October/030198.html

**Comment by stephenmcgruer** [comment]
This appears to be a dupe of https://github.com/web-platform-tests/wpt.fyi/issues/1480; is there some difference here I'm not aware of?

**Comment by Hexcles** [comment]
Closing as a dupe
