### ISSUE TITLE
Order of products isn't always preserved when using comma-separated ?products=a,b,c

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#639]
https://wpt.fyi/results/css/CSS2/selectors/first-letter-punctuation-280.xht?products=chrome%5Bstable%5D,edge%5Bstable%5D,firefox%5Bstable%5D,firefox%5Bexperimental%5D,safari%5Bstable%5D&sha=b0d2d2da21

In the URL, I've put Firefox stable before experimental, but it shows up  in the other order:
<img width="808" alt="screen shot 2018-10-11 at 10 10 14 pm" src="https://user-images.githubusercontent.com/498917/46831003-74a27500-cda2-11e8-8e17-0acf7b7425c3.png">

Note also that https://staging.wpt.fyi/results/css/CSS2/selectors/first-letter-punctuation-280.xht?products=chrome%5Bstable%5D,edge%5Bstable%5D,firefox%5Bstable%5D,firefox%5Bexperimental%5D,safari%5Bstable%5D&sha=b0d2d2da21 is missing Firefox experimental entirely, so that's a regression.

**Comment by lukebjerring** [comment]
Well, the cause for the latter is actually that we don't support `[label]` syntax for the `products` param (but should). Order is preserved since #408.

**Comment by foolip** [comment]
Oh, I didn't get that, thanks Luke!

**Comment by lukebjerring** [comment]
The provided link no longer exhibits a problem - I believe this is fixed.
