### ISSUE TITLE
Show spec links from tests and allow searching by them

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#65]
Moved from https://github.com/web-platform-tests/results-collection/issues/29.

The title is the use case. An alternative implementation would be to allow searching by *all* test content and have that search be powerful enough to support the use case. This would be quite handy in order to find tests containing certain other strings too.

The "filter by spec link" use case is one which the CSS WG would probably make use of.

**Comment by lukebjerring** [comment]
This feature is a possible atom/extension of the searchcache.

**Comment by foolip** [comment]
https://github.com/w3c/csswg-drafts/pull/4303 is a use case from the wild, to filter by spec level. It assumes some uniformity of the links, but that's pretty easy to bring about within a single directory.

**Comment by lukebjerring** [comment]
Ability to search by spec URL is covered by #1489

**Comment by lukebjerring** [comment]
And the UI-surfacing part is covered by https://github.com/web-platform-tests/wpt.fyi/issues/372
