### ISSUE TITLE
Interop query against a custom set of browsers.

### ISSUE THREAD

**Issue by mikewest** [web-platform-tests/wpt.fyi#655]
https://staging.wpt.fyi/results/content-security-policy?aligned&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D shows experimental versions of Chrome, Firefox, and Safari, and a stable version of Edge. Clicking "Interoperability" gives a "failed to fetch interop data" error (https://staging.wpt.fyi/interop/content-security-policy?aligned&product=chrome%5Bexperimental%5D&product=edge%5Bstable%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D).

**Comment by foolip** [comment]
@lukebjerring @mdittmer we can do this after the Spanner work, right? (Which is the best tracking issue for that?)

**Comment by lukebjerring** [comment]
This is blocked on #931

**Comment by foolip** [comment]
@lukebjerring do you have a URL for what @mikewest was looking to achieve?

**Comment by lukebjerring** [comment]
The link that @mikewest provided (as a failure case) is now functional.

For anyone who stumbles here looking how to check interop for a custom set of browsers:
- Visit the /interop page (a.k.a. the Interoperability tab)
- Hit the 'EDIT' button on the query builder banner
- Select the products you want to include
- Hit submit
