### ISSUE TITLE
/test-runs shows the same run multiple times

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#656]
Currently on https://staging.wpt.fyi/test-runs some recent SHAs have the same runs shown multiple times, e.g. 74d709131e & 937ed3c7b1.

However, both the Datastore and /api/runs are returning correct results (no duplicate runs), so it looks like a frontend issue? But if that's the case, why is it only happening to some recent runs instead of all the runs? cc @lukebjerring

**Comment by lukebjerring** [comment]
So, this is actually kinda complicated as to why this happens.

We have a legacy code path for fetching the test runs via a full, pre-built URL. Other components, however, are using all the params separately (to support a query-builder). When we changed the default behaviour of "no products" to be "the default products", this caused us to run 2 fetches on `/test-runs`, which means we only double-up the runs that are returned by a naked call to `/api/runs`.

I'm glad you spotted this. Fix inbound.
