### ISSUE TITLE
Detect flaky tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#66]
Moved from https://github.com/web-platform-tests/results-collection/issues/22.

Given enough runs, we should be able to build a heuristic to find tests that flip-flop often. A single flip-flop isn't enough, because that could just be a land+revert of a change. Even two flip-flops might be that of course, but with a large enough N we should see only real flakiness.

**Comment by foolip** [comment]
![flip-flops](https://user-images.githubusercontent.com/498917/38864999-cf46f50e-423c-11e8-8255-394cf9835d19.jpg)

**Comment by foolip** [comment]
@mdittmer as @jugglinmike said in the original issue, this would probably have ties into analysis, and not merely be a frontend feature.

**Comment by lukebjerring** [comment]
Oscilloscope, for flip flop measurement.
Nice jandals, though.

**Comment by mdittmer** [comment]
@foolip are you suggesting this should be a https://github.com/web-platform-tests/results-analysis issue?

**Comment by foolip** [comment]
@mdittmer yeah, probably there would be an analysis component to it, but is it too early to create meaningful issues before we know what we want to detect and how it's going to be presented?

**Comment by yoavweiss** [comment]
While investigating https://github.com/web-platform-tests/wpt/pull/10840 I started wondering if it was that CL which introduced the flakiness, or if that flakiness was there all along. Looking at https://wpt.fyi/results/resource-timing/resource_initiator_types.html doesn't tell me much about flakiness of this test in its current state. Would be neat to have some flakiness dashboard/score

**Comment by lukebjerring** [comment]
Closing this as obsolete - it's covered by the "Flakes" query in the "Insights" tab.
