### ISSUE TITLE
Detect renames when diffing across revisions

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#663]
Currently, a simple file rename would be detected as N deleted tests and N added tests, rather than what's effectively a no-op in terms of pass rates.

**Comment by lukebjerring** [comment]
Related to https://github.com/web-platform-tests/wpt.fyi/issues/644

**Comment by lukebjerring** [comment]
Example of a (currently) bad diff:
https://wpt.fyi/results/css/css-shapes/shape-outside/values?product=chrome[experimental]@4b370b4c0b&product=chrome[experimental]@bb9c0ce15e&diff=true&q=shape-outside-inset-0

**Comment by Hexcles** [comment]
We can use GitHub API to get a structured output of `git diff`, which has a list of `files` with status (ACDMR...). e.g.

https://api.github.com/repos/web-platform-tests/wpt/compare/4b370b4c0b...bb9c0ce15e

This saves us the trouble of having to checkout the repository and shelling out to git.

The caveat is:

> The response will include a comparison of up to 250 commits. If you are working with a larger commit range, you can use the Commit List API to enumerate all commits in the range.

**Comment by Hexcles** [comment]
I'd assume that this API has the same internal mechanism as `git`, i.e. heuristic-based rename detection. I don't see any parameter (namely similarity index) in the API. I'd assume it's the git default, 50%.

**Comment by lukebjerring** [comment]
A canonical example of exploded renames:
https://staging.wpt.fyi/results/workers?diff&run_id=5969501392732160&run_id=5487233003945984
