### ISSUE TITLE
Chrome Dev + Firefox Nightly runs from Taskcluster mislabeled as stable

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#667]
Currently on https://wpt.fyi/test-runs:
<img width="813" alt="screen shot 2018-10-17 at 1 43 01 pm" src="https://user-images.githubusercontent.com/498917/47084012-9d978f80-d212-11e8-9a3e-295476d57270.png">

37d83def16 is the last Chrome Dev + Firefox Nightly run from Taskcluster labeled as experimental. After that, what is apparently Chrome Dev and Firefox Nightly by looking at the version is labeled as stable, and presumably then also eligible for showing up on the front page.

**Comment by Hexcles** [comment]
[My fix](https://github.com/web-platform-tests/wpt/pull/13567) has landed in WPT and I have just batch-fixed all the incorrect lables on both prod and staging. This issue has been resolved.
