### ISSUE TITLE
https://wpt.fyi/test-runs?product=chrome-68 is 404

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#671]
https://wpt.fyi/api/runs?product=chrome-68, however, does return something.

**Comment by foolip** [comment]
What I see in the console is that https://wpt.fyi/api/runs?from=2018-09-18T00%3A00%3A00Z&product=chrome-68 failed to load with 404. 

https://wpt.fyi/api/runs?product=chrome-68&max-count=500 shows that the most recent run is from 2018-09-04, so the data parameter is probably the problem.

**Comment by foolip** [comment]
https://staging.wpt.fyi/test-runs?product=chrome-68 still doesn't work for me.

**Comment by lukebjerring** [comment]
https://travis-ci.org/web-platform-tests/wpt.fyi/jobs/443267938 failed to deploy is all :)

**Comment by lukebjerring** [comment]
Oh; just realised this is actually a separate bug. #673 only fixed `/results?product=chrome-68`

**Comment by lukebjerring** [comment]
In the same way that typing products manually on /results becomes non-aligned, /runs falls back to a default of max-count 1 when you use any non default query.

i.e. add max-count=50

**Comment by foolip** [comment]
What's the reason for that fallback, would something weird happen if we use the same max-count unconditionally?

**Comment by lukebjerring** [comment]
No; I'll send another PR.
