### ISSUE TITLE
Harness error message not shown in expanded view

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#681]
https://wpt.fyi/results/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html?sha=cf1873d8e4 screenshot:
<img width="810" alt="screen shot 2018-10-19 at 9 49 20 pm" src="https://user-images.githubusercontent.com/498917/47240531-de490180-d3e8-11e8-8c53-1e41db834600.png">

There's no details on the ERROR, even though it is in the source https://storage.googleapis.com/wptd/cf1873d8e4561c34fed1d3f3836d4c4a3f74aa8c/chrome-71.0.3578.10_dev-linux-16.04-280140cdc2/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html:
```json
{
    "duration": 318,
    "expected": "OK",
    "message": "The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22",
    "status": "ERROR",
    "subtests": [
        {
            "message": null,
            "name": "audio events - pause",
            "status": "PASS"
        },
        {
            "message": null,
            "name": "calling play() then pause() on non-autoplay audio should trigger pause event",
            "status": "PASS"
        },
        {
            "message": null,
            "name": "video events - pause",
            "status": "PASS"
        },
        {
            "message": null,
            "name": "calling play() then pause() on non-autoplay video should trigger pause event",
            "status": "PASS"
        }
    ],
    "test": "/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html"
}
```

This is probably a regression from https://github.com/web-platform-tests/wpt.fyi/pull/486 or something in that area.

**Comment by foolip** [comment]
@mdittmer, can you check if this is related to the compact view changes?

**Comment by lukebjerring** [comment]
Ping @mdittmer

**Comment by foolip** [comment]
Ping @mdittmer, just noticed this again in https://staging.wpt.fyi/results/encoding/unsupported-encodings.any.worker.html?aligned&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D

**Comment by foolip** [comment]
Cool, https://staging.wpt.fyi/results/html/semantics/embedded-content/media-elements/event_pause_noautoplay.html?sha=cf1873d8e4 works now. Thanks @mdittmer!
