### ISSUE TITLE
Ignore non-master runs in default views

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#702]
Once #699 has landed, we need to ignore non-master runs on the homepage.

**Comment by lukebjerring** [comment]
As discussed offline, let's ditch the names for other branches and just treat `master` special.

**Comment by foolip** [comment]
> You can't get your runs into wpt.fyi via a fork unless you have a copy of the webhook secret

On this point in particular, Taskcluster is running for PRs from forks, and I intend to make that work for Azure Pipelines too. The secret lives in the glue code between CI system and results receiver. (This setup can only work for CI systems with integrated and secrets-free artifacts storage.)

**Comment by Hexcles** [comment]
The secret is configured on GitHub in the wpt repository, so runs from a fork will reach the webhook just fine as long as there is a PR created from the fork against the main repo. And if someone creates a PR from the master branch of a fork, then the branch name will be master I believe (unless GitHub automatically prepends "owner/" in this case).

**Comment by foolip** [comment]
> The secret is configured on GitHub in the wpt repository, so runs from a fork will reach the webhook just fine as long as there is a PR created from the fork against the main repo.

Is this an actual secret, or a proposed setup? I thought the only remaining secret available to any CI was the one for tagging master in Travis.

**Comment by Hexcles** [comment]
> Is this an actual secret, or a proposed setup? I thought the only remaining secret available to any CI was the one for tagging master in Travis.

I'm describing the actual, current setup. The "webhook secret" is an optional GitHub setting for each webhook, and it's not available/visible to any CI.

I'm saying this current setup would also work for PRs from forks. As long as Taskcluster is triggered, the status webhook will just work.

**Comment by foolip** [comment]
Oh, the webhook secret. No problem then :)

**Comment by lukebjerring** [comment]
Expanding the scope of this issue. We should be adding the query-builder to the `/runs` view, and have that also ignore PRs by default.

**Comment by whimboo** [comment]
Can we get this fixed? As more tests are run as less frequently the test results from master are shown when opening wpt.fyi. Here an example: https://wpt.fyi/results/webdriver/tests?label=experimental

**Comment by lukebjerring** [comment]
Related to #1025 
You need to add `master` to the set of labels to ensure that PR results aren't included.
The changes to the UI to do this by default when building a query are being launched in #1034

**Comment by whimboo** [comment]
Wonderful news, and good to see that this will happen soon. Thanks for the update!

**Comment by lukebjerring** [comment]
Sorry for the inconvenience - hoping that others being plagued by the same breaking change in behaviour are able to find their way to one of these issues covering the workaround.

**Comment by lukebjerring** [comment]
#1034 is launched and the landing page now shows experimental results for all browsers except edge, by default.

**Comment by whimboo** [comment]
But it still shows non-master runs in default view. I thought that this bug is about this problem?
See: https://wpt.fyi/results/webdriver/tests?label=experimental

**Comment by lukebjerring** [comment]
That's not the default view. That's a manually constructed url. The default view is https://wpt.fyi

The issue you describe is alleviated via the toast that shows in the bottom corner, hinting that PR results are now present on wpt.fyi and offering a button that adds the master label to the current query.

**Comment by whimboo** [comment]
Oh, I see. That works, thanks!
