### ISSUE TITLE
Upload taskcluster 'affected tests' results to wpt.fyi

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#707]
A subset of the diffing solution, we first need the already-available affected tests to be uploaded (or fetched by) wpt.fyi.

This will, as a stop-gap, allow us to diff the most-recent master run of the same product against the PR's results, until we are running with and without the PR's changes.

**Comment by foolip** [comment]
We should do this for Azure Pipelines as well.

**Comment by lukebjerring** [comment]
#719 introduced processing of all branches.

**Comment by lukebjerring** [comment]
Note: Feature is controlled by `Process all taskcluster results (not just master)` in /admin/flags

**Comment by lukebjerring** [comment]
This is now considered fixed, and relates closely to https://github.com/web-platform-tests/wpt.fyi/issues/708
