### ISSUE TITLE
Log or surface invalid params

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt.fyi#71]
*From @lukebjerring on Nov 21, 2017 2:12*

We currently silently fall back to 'latest' - would be good to at least log the issue.

*Copied from original issue: https://github.com/web-platform-tests/results-collection/issues/283*

**Comment by jugglinmike** [comment]
*From @lukebjerring on Nov 21, 2017 2:14*

Not just ?sha, but ?browser too, so made the issue more general.

**Comment by mdittmer** [comment]
FWIW I would prefer an error response on invalid params.

//Mark
