### ISSUE TITLE
Upload 'affected tests' results from Azure Pipelines

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#714]
Azure version of #707

**Comment by foolip** [comment]
The Safari results are being done in https://github.com/web-platform-tests/wpt/pull/14156. The API for getting the results out will be https://dev.azure.com/web-platform-tests/wpt/_apis/build/builds/1040/artifacts?artifactName=drop&api-version=5.0-preview.5&%24format=zip.

@Hexcles @lukebjerring, I think using that PR you should be able to experiment with the results receiver parts to this right now. Note that I'll want to change `artifactName` though, probably to `results`.

**Comment by lukebjerring** [comment]
This is now up and running! https://staging.wpt.fyi/runs?product=safari

**Comment by foolip** [comment]
Sweet, with an azure label too!

**Comment by lukebjerring** [comment]
> Logos are the new labels

https://github.com/web-platform-tests/wpt.fyi/pull/910
