### ISSUE TITLE
/api/runs error "Key path element must not be incomplete" with max-count=500

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#733]
URLs to reproduce:
https://wpt.fyi/api/runs?product=chrome&label=stable&to=2018-06-25T15:50:53.968632Z&max-count=500
https://staging.wpt.fyi/api/runs?product=chrome&label=stable&to=2018-06-25T15:50:53.968632Z&max-count=500

The failure message is:
```
API error 1 (datastore_v3: BAD_REQUEST): Key path element must not be incomplete: [TestRun: ]
```

Using a lower max-count value works, and `max-count=482` is the highest that doesn't give an error.

**Comment by foolip** [comment]
Going back in time, it looks like the `max-count` value that works shrinks. This breaks:
https://wpt.fyi/api/runs?product=chrome&label=stable&to=2017-09-27T14:38:44.79711Z&max-count=100

**Comment by foolip** [comment]
Another failed attempt: https://wpt.fyi/api/runs?to=2017-08-01T06:12:10.595988Z&max-count=100

Perhaps there's an entry some time before that that's actually broken, causing this?

**Comment by s3ththompson** [comment]
Can confirm that I encountered this error and had to write a pagination script that halved the max-count with each failed request until it eventually just requested the last few runs one-by-one (`max-count=1`).

FWIW, this error seemed to crop up regardless of product or label.

**Comment by lukebjerring** [comment]
This surfaced again in the final page while testing #772 . There were a couple of stray entities with a `name` ID key, so we deleted them and the problem should be solved.

**Comment by foolip** [comment]
Was the ID field the string "name" or what had happened? (I thought that was an int64.)

**Comment by Hexcles** [comment]
The `key` can be either numeric (`ID`) or a string (`name`). All of these are special reserved names. We use only numeric IDs as keys. There were a couple experimental runs very early on that used strings as keys.

**Comment by foolip** [comment]
Can we change the scheme to be numeric only now?

**Comment by lukebjerring** [comment]
It is, de facto, but we can't prevent future code from using a named key (that's a datastore feature)

**Comment by Hexcles** [comment]
Besides, Datastore is really schema-less, so there's no schema to begin
with.

**Comment by foolip** [comment]
Ah, I see.
