### ISSUE TITLE
Unclear how to paginate /api/runs?aligned

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#734]
When using the `aligned` parameter, such as with https://wpt.fyi/api/runs?label=stable&products=chrome,edge,firefox,safari&aligned&max-count=50, it's not clear how one would paginate to get the next set of runs at an earlier time.

Using the earliest `time_start` of all the runs returns as the next `to` value probably roughly works, but if the start times of a set of aligned runs happens to straddle that time it seems like it would be skipped. It seems like one would have to add a "buffer" amount of time like 1 week to avoid this, and then remove duplicates. However, one then also assumes that no more than `max-count` runs could happen in that buffer time, and would probably have a serious bug (infinite loop) if it ever did.

**Comment by foolip** [comment]
I think a fix for this would be to use the commit time, since then the time would be the same for all runs for the same commit, and there is no time window issue. @Hexcles?

**Comment by s3ththompson** [comment]
Rather than move pagination to userspace, is it possible that the API could just share some pagination middleware among all Datastore resource endpoints? E.g. each response would have the next URL to request in the response body?

**Comment by lukebjerring** [comment]
That's pretty much exactly my plan.. lol. 

While a little unusual, I'm thinking that having it (it being the next page token) as an HTTP header on the response will help avoid a backward incompatible change to the payload.

**Comment by lukebjerring** [comment]
So, while max-count pagination was introduced in #772, there's still a bug with fetching aligned runs (it caps the number of iterated keys, not the number of results).

**Comment by lukebjerring** [comment]
Apart from a know issue #819 this is now using the standard page-token flow.
