### ISSUE TITLE
Not possible to efficienty keep a mirror of the wptd-results bucket

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#735]
This is related to https://github.com/web-platform-tests/wpt.fyi/issues/636, another attempt to get all the runs.
 
The full wptd-results bucket can be mirrored using `gsutil.py -m rsync -r gs://wptd-results/ wptd-results/`.

However, while the filed are transferred compressed, they end up uncompressed on disk, and would require ~1TB to store. Excerpts from stdout while cloning:
```
gs://wptd-results/74d709131e3c91d09f1708378648a01957c47b38/firefox-62.0.3-linux-16.04-189e95fb5e/report.json has a compressed content-encoding, so it will be decompressed upon download; future executions of gsutil rsync with this source object will always download it. If you wish to synchronize such an object efficiently, compress the source objects in place before synchronizing them, rather than (for example) using gsutil cp -Z to compress them on-the-fly (which results in compressed content-encoding).
Copying gs://wptd-results/74d709131e3c91d09f1708378648a01957c47b38/firefox-62.0.3-linux-16.04-189e95fb5e/report.json...
Downloading to temp gzip filename wptd-results/74d709131e3c91d09f1708378648a01957c47b38/firefox-62.0.3-linux-16.04-189e95fb5e/report.json_.gztmp
```

and

```
gs://wptd-results/79e45ec83e0416793fdb6c59cd95d0acab63e5f4/firefox_60.0.1_linux_4.4/migration.log has a compressed content-encoding, so it will be decompressed upon download; future executions of gsutil rsync with this source object will always download it. If you wish to synchronize such an object efficiently, compress the source objects in place before synchronizing them, rather than (for example) using gsutil cp -Z to compress them on-the-fly (which results in compressed content-encoding).
Copying gs://wptd-results/79e45ec83e0416793fdb6c59cd95d0acab63e5f4/firefox_60.0.1_linux_4.4/migration.log...
Downloading to temp gzip filename wptd-results/79e45ec83e0416793fdb6c59cd95d0acab63e5f4/firefox_60.0.1_linux_4.4/migration.log_.gztmp
```

The "future executions of gsutil rsync with this source object will always download it" part is the problem, and confirmed by aborting the sync at 14%, which caused it to start over. I think that as it started, all of the files on disk were renamed to something with `gztmp` until they were resynced, but I don't want to try again to confirm.

Solution seems to be compressing the files in place.

**Comment by Hexcles** [comment]
This is the [gzip transcoding](https://cloud.google.com/storage/docs/transcoding) of GCS in effect, namely the on-the-fly decompressive transcoding during download.

It's possible to wget/curl the files without decompressing them: simply add `Accept-Encoding: gzip` to headers and GCS will happily serve the compressed form directly. This is essentially what we do in the webapp.

However, I just found out that `gsutil` had very poor support of this. It seems like there's no way to tell gsutil not to decompress.

>  Note that if you download an object with Content-Encoding:gzip gsutil will decompress the content before writing the local file.

(https://cloud.google.com/storage/docs/gsutil/commands/cp#options)

There's in fact even an open feature request against gsutil: https://github.com/GoogleCloudPlatform/gsutil/issues/515

**Comment by Hexcles** [comment]
Alright, here's an idea if we have to do it:

1. Use `gsutil ls -r gs://wptd-results/**` to generate the list of files.
2. Use `xargs -L 1 -P 10 wget --header="Accept-Encoding: gzip"` to download the gzipped files in parallel.

**Comment by foolip** [comment]
If this is a problem with `gsutil` and it is *possible* to write a client (or fix `gsutil`) that doesn't have this problem then I think maybe it's OK to leave it alone.

(Downloading all of the files isn't much of a problem, the problem is later doing an incremental update. I guess I could use some `wget` option for that.)

**Comment by Hexcles** [comment]
Yes it's indeed a client-side problem.

**Comment by foolip** [comment]
Alrighty. I'll close this, with pagination of /api/runs and the assumption that things in GCS never change, it will be possible to keep a mirror, just not using `gsutil`.
