### ISSUE TITLE
wptd-results bucket has a single directory with short hash

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#737]
gs://wptd-results/ffeba23ebd/ exists, and is the only directory in the bucket that isn't exactly 40 characters long.

https://wpt.fyi/results/?sha=ffeba23ebd works, and unlike most oddities, this is a very recent one, from Nov 3.

**Comment by lukebjerring** [comment]
That's the result of a mismatch of the `revision` field while I was playing around / uploading results, not realizing the field in the uploader needs the 40 char version. We can probably delete it.

**Comment by Hexcles** [comment]
Deleted the two runs (both in Datastore and in GCS).

@lukebjerring I'd suggest playing with the staging project instead of the prod in the future.
