### ISSUE TITLE
Remove/hide the range of runs where Edge was broken

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#743]
Between https://github.com/web-platform-tests/wpt/pull/13419 and https://github.com/web-platform-tests/wpt/pull/13938, Edge runs were totally busted, and we're better off not having those runs around.

In https://wpt.fyi/test-runs?product=edge it's the 19 runs from 99e577f57c to 032cd9cc63 (inclusive) that are bad.

**Comment by lukebjerring** [comment]
Done via https://github.com/web-platform-tests/data-migration/pull/11
