### ISSUE TITLE
Comparing stable to beta broken on staging.wpt.fyi

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#750]
Same URL for staging and prod:
https://wpt.fyi/results/?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned
https://staging.wpt.fyi/results/?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned

The staging link says "Failed to fetch test runs", which seems to be because of the difference here:
https://wpt.fyi/api/runs?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned
https://staging.wpt.fyi/api/runs?product=chrome%5Bstable%5D&product=chrome%5Bbeta%5D&aligned

Staging doesn't return any aligned runs.

**Comment by lukebjerring** [comment]
Duplicate of https://github.com/web-platform-tests/wpt.fyi/issues/755
