### ISSUE TITLE
Many more runs available on staging than on prod

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#756]
Compare https://staging.wpt.fyi/test-runs:
![staging wpt fyi_test-runs](https://user-images.githubusercontent.com/498917/48474907-d9b31580-e7fb-11e8-9441-24e3baca06b4.png)

To https://wpt.fyi/test-runs:
![wpt fyi_test-runs](https://user-images.githubusercontent.com/498917/48474956-0109e280-e7fc-11e8-9570-4cef6d84675c.png)

There's a huge difference in the number of runs after 7201104211, possible before as well.

@Hexcles, is the results receiver getting results for both staging and prod?

**Comment by lukebjerring** [comment]
That's likely just all the results for all the PRs (which we download in staging, but not in prod).

**Comment by lukebjerring** [comment]
@foolip - maybe another source icon for `master` would help make this obvious ?

**Comment by Hexcles** [comment]
So the remaining action item for this is to filter by label=master in /test-runs.

**Comment by Hexcles** [comment]
Then let's close this issue.

**Comment by foolip** [comment]
Thanks for the quick action, a great bug filer experience :)
