### ISSUE TITLE
Currently displaying duplicate results (two of each browser)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#76]
https://github.com/web-platform-tests/results-collection/issues/470 has happened again:
![image](https://user-images.githubusercontent.com/498917/39114594-8fcc2898-46df-11e8-8f89-6db102aaa954.png)

Cause unknown, but the previous issue probably has clues.

**Comment by foolip** [comment]
Hmm, it's fixed itself. Did anyone do anything?

**Comment by lukebjerring** [comment]
Race condition was fixed a while back, waiting on a release.
