### ISSUE TITLE
Support listing runs by PR number

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#784]
Because PRs are transient, and GitHub is the source of truth, it would be inherently problematic to store PR metadata ourselves.

However, getting a list of runs associated with a PR would often be quite helpful.

**Comment by Hexcles** [comment]
It'd be great to also have the reverse lookup: finding out which PR a commit belongs to (if it is part of a PR) so that we can provide a back link to GitHub PRs from wpt.fyi when showing the regression view.

**Comment by lukebjerring** [comment]
That latter case is covered by linking to the commit on GitHub, which surfaces a link to any PR on the commit's page.

**Comment by lukebjerring** [comment]
Getting a PR from a commit is covered by #900 (head to the commit on GitHub, which will surface the PR).
