### ISSUE TITLE
Query editor for test level view

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#791]
In a view like https://wpt.fyi/results/webrtc/RTCPeerConnection-connectionState.html?label=stable&aligned, it would be handy if it's possible to change the set of products (browsers) shown just like in https://staging.wpt.fyi/results/webrtc?label=stable&aligned.

This would have been handy for me to show @jonasesolsson the results of Safari and Safari TP side-by-side, instead I edited the URL :)

**Comment by lukebjerring** [comment]
This was fixed by  #789 - the edit button was migrated to the info-bar (which summarizes what the current query is).
