### ISSUE TITLE
Implement & document a monitoring solution that alerts when wpt.fyi is unreachable

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#8]
_From @mariestaver on February 2, 2018 20:36_

_Copied from original issue: w3c/wptdashboard#422_

**Comment by mariestaver** [comment]
Aha, that's very useful; thanks!  It doesn't seem to have alerting options (that I see? maybe admin does), so that's still something we'll want to pursue, but it's nice to have this data as well.

**Comment by lukebjerring** [comment]
Marking this as resolved.
