### ISSUE TITLE
Search doesn't do anything for individual test-result files (subtest pages)

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#81]
Behaviour should probably be filtering on the subtest name, at a minimum. We'll eventually want to filter on particular result types too (TIMEOUT, FAIL, etc). See https://github.com/web-platform-tests/wpt.fyi/issues/73.

**Comment by foolip** [comment]
Being able to search on both file contents and the failure messages would be useful too.

**Comment by foolip** [comment]
(Mostly failure messages, file contents is readily searchable with grep already.)

**Comment by mdittmer** [comment]
Search box no longer shows up in these contexts. Should we close this, or leave it open as a feature request to implement single-top-level-test search?

**Comment by lukebjerring** [comment]
Search now supports filtering by results.
