### ISSUE TITLE
Custom checks showing up on all commits on master, comparing against master

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#866]
In https://github.com/web-platform-tests/wpt/commits/master, every commit gets wpt.fyi "chrome[experimental] and "firefox[experimental]" checks. Example:
https://github.com/web-platform-tests/wpt/runs/38327762
https://github.com/web-platform-tests/wpt/runs/38327768

This could be very useful if the comparison was against the previous commit on master.

**Comment by foolip** [comment]
A comparison against the previous run of the same product would in particular come in handy after landing a change like https://github.com/web-platform-tests/wpt/pull/14309 where some regressions might have slipped through.

**Comment by lukebjerring** [comment]
I think the checks you're pointing at are (incorrectly) comparing the same run against itself, since the "latest master run" is the run itself. I'll use this issue to follow up on ensuring that we find the previous run in those cases.

As for making it show up for everyone, you'll just need to enable `checksAllUsers`. This isn't added in the /admin/flags view just yet - will add it.

**Comment by Hexcles** [comment]
By the way, the user whitelist seems to be not working. All commits from all users on master have the wpt.fyi custom checks.

**Comment by lukebjerring** [comment]
It was that way a couple days ago, so you might just be seeing leftovers from that bug, but if you scroll the list a few don't have the check (e.g. commits from youenff)

**Comment by foolip** [comment]
For commit 226f3b5 3 checks are showing up:
![image](https://user-images.githubusercontent.com/498917/49724887-b6e51700-fc6a-11e8-9819-769348513469.png)

But for the preceding commit no checks. Not sure why :)

**Comment by lukebjerring** [comment]
The pr author is whitelisted, so their merge triggers a check suite

**Comment by gsnedders** [comment]
> The pr author is whitelisted, so their merge triggers a check suite

Why does authorship matter when the commit is on the wpt repo itself? If a commit has been pushed to the WPT repo itself, it's been pushed by someone we should consider trustworthy.

**Comment by foolip** [comment]
The list was just to try it out with a small number of people, not for security reasons.

**Comment by lukebjerring** [comment]
Yah, temporary measure to reduce noise during unstable development.

**Comment by lukebjerring** [comment]
This was fixed by #872
