### ISSUE TITLE
Adjust summary scores to ignore the testharness status

### ISSUE THREAD

**Issue by fergald** [web-platform-tests/wpt.fyi#882]
Steps to repro

1 go to [css-shadow-parts dashboard](https://wpt.fyi/results/css/css-shadow-parts?label=experimental)
2 click on details for [different-host.html](https://wpt.fyi/results/css/css-shadow-parts/different-host.html?label=experimental)

On the dashboard different-host.html is shown as passing 2/2 on FF and Safari but in the details page it's 1 pass and 1 missing, that's not 2/2 and does not seem like it should be green.

**Comment by lukebjerring** [comment]
This is actually ambiguously working as intended. Counts include 1 for the harness (the OK status row at the top).
Each test then happened to execute a different set of 1 subtest, so the counts look like 2/2. I suspect there's a bug in the test itself or a mismatch of which revision of WPT was run. 
I'll investigate further when I'm at a computer later today.

**Comment by gsnedders** [comment]
See also #62.

**Comment by foolip** [comment]
I think it's a dupe :)
