### ISSUE TITLE
Load blocked on unpkg.com

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#883]
Loading wpt.fyi today the loads have been slow, around 10s or so. While blocked, I've seen unpkg.com in the status bar, and in devtools I see that https://unpkg.com/ohm-js@latest/dist/ohm.min.js was loading. Screenshot from the latest load:
![image](https://user-images.githubusercontent.com/498917/49732694-bb67fa80-fc7f-11e8-957c-f3278a90faf5.png)

(URL is https://wpt.fyi/results/?label=taskcluster&product=firefox@226f3b50a6&product=firefox@9f2b7133fa&diff but probably doesn't matter.)

We should use a more reliable CDN, or remove the dependency if it's not intentional.

**Comment by foolip** [comment]
@lukebjerring do we have metrics for end user load time that we're tracking, where this regression shows up?

**Comment by lukebjerring** [comment]
No; we might need to add custom events in analytics; page load and interactive aren't meaningful (the data is inherently slow to load).
ohm should be an async dep either way; will re-jig the loading behaviour.

**Comment by Hexcles** [comment]
Assuming this is fixed.
