### ISSUE TITLE
Automate and de-privilege retrieval of development data

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#9]
_From @jugglinmike on January 31, 2018 22:49_

Currently, [the documentation for running this project locally](https://github.com/w3c/wptdashboard/tree/35563fcc31fd09a360f8e9197e0a060a1e8e5bd4#running-locally) include the following instructions:

> With the webserver running, you'll also need to populate the app datastore
> with some initial data. In another terminal, execute the script which
> leverages `util/populate_dev_data.go` by running:
>
>     ./util/docker-dev/dev_data.sh

This omits a critical requirement: that users have a Google Cloud-enabled account with proper access permissions. Also missing are the steps necessary to create the expected "service account file". For Unix-like systems, that can be done with the following commands:

```
sudo pip install --upgrade google-cloud

curl https://sdk.cloud.google.com | bash
exec -l $SHELL
gcloud init

gcloud auth application-default login
```

I don't think it's worth documenting this because the underlying access restrictions are a more fundamental problem.

We should publish a dataset in a publicly-accessible location and automate its retrieval for folks who are attempting to contribute.

_Copied from original issue: w3c/wptdashboard#418_

**Comment by lukebjerring** [comment]
_From @mattl on January 31, 2018 22:54_

Yeah, this is a good idea. Especially when you consider that https://storage.googleapis.com/wptd/fcf46c6ea5/firefox-57.0-linux-summary.json.gz is a public URL and all of the files mentioned are public too (ie. https://storage.googleapis.com/wptd/fcf46c6ea5/firefox-57.0-linux/css/css-writing-modes/table-progression-vrl-001.html)

**Comment by lukebjerring** [comment]
_From @mattl on January 31, 2018 22:55_

https://github.com/w3c/wptdashboard/issues/136

**Comment by lukebjerring** [comment]
Ultimately, this stems from the fact that we use the `remote_api` to add the data to the datastore, which requires admin access in prod, and (I believe, any) auth locally.

I can still add the data locally by running `./util/docker-dev/dev_auth.sh` before running `./util/docker-dev/dev_data.sh` (and auth-ing with an unauthorized Google account). I'll tweak the documentation.

**Comment by jugglinmike** [comment]
:tada:
