### ISSUE TITLE
Need a way to get from interop view to results view on all levels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#90]
From https://master-dot-wptdashboard.appspot.com/interop/html I would like to be able to get to https://master-dot-wptdashboard.appspot.com/results/html quickly and vice versa.

**Comment by gsnedders** [comment]
Just noticed this looking at the interop view for the first time; would make it much more useful to find out if all the 3/4s are caused by one browser or a mix of all browsers.

**Comment by Hexcles** [comment]
This has been implemented by #330 .
