### ISSUE TITLE
Checks compare stable v. experimental baseline

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#901]
e.g. https://github.com/web-platform-tests/wpt/runs/40189217:

this shows: 

Run | Spec
-- | --
master | chrome-72.0.3626.14 dev-linux-18.04@9bf305b4ed
48d5d50 | chrome-71.0.3578.80-linux-18.04@48d5d5033d

The comparison of Chrome 72 v. Chrome 71 seems bogus.

And the chrome[experimental] run (https://github.com/web-platform-tests/wpt/runs/40181992) shows the equally bogus:

Run | Spec
-- | --
master | chrome-71.0.3578.80-linux-18.04@48d5d5033d
48d5d50 | chrome-72.0.3626.14 dev-linux-18.04@48d5d5033d

**Comment by Hexcles** [comment]
@lukebjerring no, that's a separate issue. IIUC, `GetDiffURL` is only responsible for generating the link, not for finding the runs. I think the problem here is that we need to pass the labels from the receiver to `ScheduleResultsProcessing`.

**Comment by Hexcles** [comment]
Should be fixed now.
