### ISSUE TITLE
Check links to non-existent run when previous commit didn't run

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#902]
https://github.com/web-platform-tests/wpt/runs/40049998

The "Visual comparison of the results" links to a page that gives "'diff' was requested, but is only valid when comparing two runs."

This is presumably because the last master commit didn't get results for that browser.

**Comment by lukebjerring** [comment]
This has been fixed (I re-processed the wpt.fyi check, and the new link uses 2 `run_id` fields).
