### ISSUE TITLE
Interop view of subtests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#91]
In https://master-dot-wptdashboard.appspot.com/interop/dom/historical.html it's not possible to see which 4 / 73 subtests are passing in exactly one browser. This would be very useful.

**Comment by lukebjerring** [comment]
@mdittmer 

I don't recall a test-results split being spec'd in the design/mocks, and I also cannot find said mocks.

I think at the test-file level, we could just also include the same `/results` summary grid, but order it by interoperability browser-pass-count? @foolip WDYT?

**Comment by foolip** [comment]
Yes, I'd also like to see a similar grid as for /results. On the order, I'd say that the closer to the order of /results the better. Order can be implementation-dependent, but going with the order of the first listed browser and then appending missing tests from each following one might be good enough. When order doesn't match, that might actually be worth investigating, so logging such cases would be good.

**Comment by lukebjerring** [comment]
@foolip - I think the solution here is to add an 'explode' parameter (name notwithstanding) which avoids grouping by test, and instead groups by subtest.
Single test-file views would pass that parameter and re-run their query (similar to the current behaviour for fetching with subtest names included).

**Comment by foolip** [comment]
@lukebjerring I'm not sure I fully understand, do you mean that the response from /api/search would include subtests?

I would actually consider this issue fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1103, but perhaps there's more to it?

**Comment by lukebjerring** [comment]
Right now we group the results by the test name (foo.html), and drop the subtests.
#1103 changed to include the subtest _names_, but not the results.
To show interop scores for subtests, we'd need to group/score the results by subtest, not just the test name.

**Comment by foolip** [comment]
Oh, right, that's what I was asking for in this issue: interop numbers for subtests. I had it confused with filtering subtests, sorry.

**Comment by foolip** [comment]
I no longer think we should do this as the search cache has largely replaced the need for the interop view.
