### ISSUE TITLE
Hard to discover what the "expand" button does

### ISSUE THREAD

**Issue by alvestrand** [web-platform-tests/wpt.fyi#930]
In a most wonderful discovery, I came across
https://fyi-dot-wptdashboard-staging.appspot.com/results/webrtc/protocol/missing-fields.html?sha=0acd6696fb&label=experimental
which gives me exactly what I've long wanted - presubmit visibility into how Firefox will do when I submit a new test.

But - there are UI issues.
- I didn't notice the "expand" button, but I did notice that the error messages expanded when I hovered over them. They were too long to fit on the screen, so a scrollbar appeared - but if I tried to reach the scrollbar, I was no longer hovering, so it disappeared again. Suggestion: Replace scrollbar with "click expand to see the whole message", or expand the box vertically when hovered over.

- The expanded message doesn't look like the non-expanded one. In particular, the non-expanded message says PROMISE_REJECT, while the expanded version says "FAIL message: promise_test: Unhandled rejection" - it's not 100% obvious that those two are the same error message. Suggestion: Use the PROMISE_REJECT form in both places; it's clearer and shorter.

**Comment by foolip** [comment]
I like both of these suggestions, a guaranteed-to-be-short summary and a detailed description that is clear how to expose. As it is, it's not surprising that people would first try parsing the error in the long horizontal string.

@mdittmer WDYT?

**Comment by mdittmer** [comment]
The first UI issue is surprisingly hard to implement under the layout
constraints for the table. I also hesitate to implement the second one
because we don't control the "expanded" message. It is the message from the
WPT report. `PROMISE_REJECT` was my attempt to provide a terse summary of
what messages of that general form usually mean.

**Comment by Hexcles** [comment]
Fixed by #1768
