### ISSUE TITLE
Safari check runs not showing up for most PRs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#945]
Recent PRs where Azure Pipelines has finished and there are Chrome+Firefox wpt.fyi check runs, but none for Safari:
- https://github.com/web-platform-tests/wpt/pull/14580
- https://github.com/web-platform-tests/wpt/pull/14581
- https://github.com/web-platform-tests/wpt/pull/14582
- https://github.com/web-platform-tests/wpt/pull/14584
- https://github.com/web-platform-tests/wpt/pull/14588
- https://github.com/web-platform-tests/wpt/pull/14589

On all of these, the Chrome+Firefox checks are also still pending, which suggests that perhaps no runs are quite working?

**Comment by foolip** [comment]
@lukebjerring do you have some scripts to check for pending runs on open PRs? This is likely to confuse people and we should probably try to retrigger stuff so that they finish, or comment saying they can be ignored.

**Comment by foolip** [comment]
I have some scripts I could adapt from https://github.com/web-platform-tests/wpt/issues/13818 and https://github.com/web-platform-tests/wpt/issues/14210, but where should they be run in an ongoing fashion and who will monitor?

**Comment by lukebjerring** [comment]
Without looking yet, those are likely to be no affected tests (empty reports). 
A script sounds like a good idea. Maybe adding to eco rotation?

**Comment by foolip** [comment]
It sounds unlikely that all the recent PRs really have no affected tests. I just looked att PRs in order and all were in the same state.

**Comment by foolip** [comment]
In the first if the listed PRs, there were two affected tests.

**Comment by lukebjerring** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/14649
