### ISSUE TITLE
Empty reports cause permanently pending status checks

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#950]
When there are no affected tests, or only added files (so the pr_base has no tests), we don't produce a TestRun entity, which means that the check is unable to conclude in spite of being pending.

**Comment by lukebjerring** [comment]
Is there any major reason that we don't want to create a run if there's nothing to report?
Can we just have a shared, canonical, empty report URL and create `TestRun` entities either way?

**Comment by foolip** [comment]
Any quickfix for this? I think it's affecting https://github.com/web-platform-tests/wpt/pull/14505, and most likely a lot of other PRs then.

**Comment by Hexcles** [comment]
This should be fixed now.
