### ISSUE TITLE
Check runs created even though there aren't any affected tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#952]
### Check
A link to the GitHub Check run containing my issue:
https://github.com/web-platform-tests/wpt/pull/14033/checks?check_run_id=42851015

### Description
The check run has been created even though there aren't any affected tests, and the jobs to run affected tests will not even run on at least Azure Pipelines.

Perhaps the runs should be created once we know that any test was run with or without the changes? Otherwise, the pre-created checks need to be cancelled once we find out they were not needed.

**Comment by foolip** [comment]
Drive-by comment: the issue template could include the check link directly so one need not copy it. The link is embedded in the very page one should link to, after all.

**Comment by lukebjerring** [comment]
The body-template is static, in a markdown written in wpt.fyi. We'd have to dynamically set the entire template body via query param (making for a very long URI).

**Comment by lukebjerring** [comment]
Caused by https://github.com/web-platform-tests/wpt/issues/14471

**Comment by foolip** [comment]
Oh, the template is in https://github.com/web-platform-tests/wpt.fyi/blob/master/ISSUE_TEMPLATE/checks.md, I assumed it was already sent in the URL.
