### ISSUE TITLE
Don't 400 for run_id missing from search cache

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#953]
With the search cache covering a subset of results, there are several scenarios where a requested id might not be present in the cache.

Often, the id will be part of a group, so serving a 400 and no results prevents the other runs results being viewed or searched. Serving missing results for runs not present in the cache is a better interaction for the client.

**Comment by mdittmer** [comment]
The trouble with this strategy is that it can poison our request-level cache. If the status code somehow marks the results as incomplete we could make sure that the cache decorator refuses to store the "incomplete result" status code.

**Comment by mdittmer** [comment]
There's also an argument to be made that the client should wait until complete results are available via, for example, a polling strategy.

**Comment by lukebjerring** [comment]
How about a 422 - Unprocessable entity?

**Comment by lukebjerring** [comment]
#1031 #1030 #1029 address this issue.
