### ISSUE TITLE
Taskcluster stability failures will prevent results from being collected

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#974]
### Check
A link to the GitHub Check run containing my issue:
https://github.com/web-platform-tests/wpt/runs/43865362

### Description
Because the overall Taskcluster status was failure, the Chrome + Firefox results weren't collected. Additionally, the checks were left hanging instead of failing in some manner.

**Comment by foolip** [comment]
Nope, I spoke too soon. The results came in!

**Comment by lukebjerring** [comment]
FWIW, This actually was the case a while ago:
https://github.com/web-platform-tests/wpt.fyi/issues/835

**Comment by foolip** [comment]
I thought so, and didn't know it had been fixed. Thanks!
