### ISSUE TITLE
TestProductParam_SHA_Latest is flaky on master

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt.fyi#992]
`TestProductParam_SHA_Latest` in `product_test.go` (and perhaps some other tests in the same file) is flaky on master. Example failure: https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/168944971#L3436

**Comment by Hexcles** [comment]
More failures: https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/169008102#L2649

**Comment by lukebjerring** [comment]
Some timing info, running the staging tests from a local machine:

    === RUN   TestFileResults
    --- PASS: TestFileResults (16.04s)
    === RUN   TestLabelParam
    --- PASS: TestLabelParam (9.01s)
    === RUN   TestPath_Results
    --- PASS: TestPath_Results (5.23s)
    === RUN   TestPath_Interop
    --- PASS: TestPath_Interop (5.35s)
    === RUN   TestProductParam_Order
    --- PASS: TestProductParam_Order (6.80s)
    === RUN   TestProductParam_Labels
    --- PASS: TestProductParam_Labels (7.58s)
    === RUN   TestProductParam_SHA_Latest
    --- PASS: TestProductParam_SHA_Latest (5.57s)
    === RUN   TestProductParam_SHA_Specific
    --- PASS: TestProductParam_SHA_Specific (9.50s)
    === RUN   TestSearch_Results
    --- PASS: TestSearch_Results (8.15s)
    === RUN   TestSearch_Interop
    --- PASS: TestSearch_Interop (6.35s)
    === RUN   TestTestRuns
    --- PASS: TestTestRuns (5.97s)

**Comment by lukebjerring** [comment]
Curiously, #984 missed a flag, and we've been silently "failing" to deploy. I'll fix deployment, and we can see whether the Polymer 3 migration improves things.

**Comment by lukebjerring** [comment]
I can't prove it yet, but I think we're potentially looking at a partial rollout of a buggy update to dev_appserver (similar to #616, which was also very flaky at the time, but repro'd consistently on my machine at home).

The issue is actually that memcache isn't working (locally), which causes 500s to the /api/search endpoint, which in turn causes the elements to never load.
